### ISSUE TITLE
Cache: Transaction write object results in no change.

### ISSUE THREAD

**Issue by pggawlowski** [apollographql/apollo-ios#1336] opened 2020-07-30 21:15 UTC
```
                do {
                    var response = try transaction.readObject(ofType: Package.self, withKey: packageId)
                    response.status = entry.status
                    
                    try transaction.write(object: response, withKey: packageId)                    
                    let confirmChange = try transaction.readObject(ofType: Package.self, withKey: packageId)
                    print(confirmChange)
                } catch {
                    print(error)
                }

```

I digged down until ApolloStore -> `func mergePromise(records: RecordSet)`.
Result is giving me succes `fulfill(cacheKey)` with cacheKey "123.status" which is correct packageId and correct field I was trying to manipulate. 

However confirmChange object has unchanged status. My `cacheKeyForObject` for both store and client are set. 
Is it sth I am doing wrong or writeObject is not working the way I think?

**Comment by designatednerd** [comment] 2020-07-31 01:51
The issue is that the transactions aren't guaranteed to be synchronous, so `transaction.write` may not have finished before `transaction.read` is called. 

You'd need to use [`withinWriteTransaction`](https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/ApolloStore.swift#L149) in order to validate the change.

**Comment by pgawlowski** [comment] 2020-08-05 08:33
Actual problem was: invalid cacheKeys. Sorry for wasting Tour time.

**Comment by designatednerd** [comment] 2020-08-05 15:15
No worries - thanks for following up with what actually happened! I'm gonna go ahead and close this issue out.

**Closed by designatednerd** 2020-08-05 15:15 UTC
Labels: caching, question
