### ISSUE TITLE
CLI generate code that can't compile when using `fragment` in query

### ISSUE THREAD

**Issue by anhlq-supp** [apollographql/apollo-ios#3024] opened 2023-05-18 07:27 UTC
### Summary

I'm define a new `fragment` in my query in the CLI generate the code that Xcode can't compile
The error is from Xcode is 
`Cannot convert value of type 'myFragment.Type' to expected argument type 'any Fragment.Type'`
 &
`Instance method '_toFragment()' requires that 'myFragment' conform to 'Fragment'`

### Version

1.2

### Steps to reproduce the behavior

My query is something like this
```
query permAdPrefill($id: PermAdId!) {
	PermAd {
		prefill(id: $id) {
			listingPeriod {
				...ListingPeriod
			}
		}
	}
}

query permAdListingPeriod {
	PermAd {
		listingPeriods {
			...ListingPeriod
		}
	}
}

fragment ListingPeriod on PermAdListingPeriod {
	id
	descriptionLabel
	summaryLabel
}
```

**Comment by calvincestari** [comment] 2023-05-18 17:13
Hi @anhlq-supp, thanks for creating the issue. I can replicate the issue and will work through potential solutions with the rest of the team.

**Comment by calvincestari** [comment] 2023-05-18 21:56
@anhlq-supp there are two issues in the operation that are causing the build errors:
1. Field name matching a fragment name
```
			listingPeriod {
				...ListingPeriod
			}
```
The resulting problem here is having two types with the same name (`ListingPeriod`) and trying to refer to the fragment type from within the operation which cannot be found, and the operation type is not a fragment so it does not conform to the fragment protocol.

2. The singularized named of the list type conflicts with the fragment name
```
		listingPeriods {
			...ListingPeriod
		}
```
When the codegen engine creates the type for a list object it singularizes the type name so you end up with `[ListingPeriod]` instead of `[ListingPeriods]`. This again causes a conflict of type names.

The solution to both these issues is to use a field alias in your operation, or rename the fragment. Both give you full control over the naming and will avoid the typename conflict.

**Comment by calvincestari** [comment] 2023-05-18 21:57
Closing this issue as it's a duplicate of #2405 and that issue can instead be followed for progress on the implementation of a warning during code generation to highlight the problem and recommend a solution to the user.

**Closed by calvincestari** 2023-05-18 21:57 UTC
Labels: bug, codegen

**Comment by anhlq-supp** [comment] 2023-05-25 02:39
Thanks for your support @calvincestari
