### ISSUE TITLE
Issue when compiling generated files.

### ISSUE THREAD

**Issue by kc-bandari** [apollographql/apollo-ios#2968] opened 2023-04-18 15:54 UTC
### Summary

Am able to successfully generate queries and mutation files. But when compiling am facing issues

`
Initializer 'init(_dataDict:)' has different argument labels from those required by protocol 'AnySelectionSet' ('init(data:)')
`

` 'Schema' is not a member type of type 'Self'`

Please help me fix the issue.

Thanks in advance.

### Version

1.0.7

### Steps to reproduce the behavior

Generated files with codegen and compiled.

**Comment by calvincestari** [comment] 2023-04-18 19:17
@kc-bandari, that seems like it's caused by an out-of-date dependency. Are you sure you've updated both the CLI for code generation and the Apollo dependency version you're linking to?

**Comment by kc-bandari** [comment] 2023-04-20 09:20
Yes am using latest version of apollo.

**Comment by calvincestari** [comment] 2023-04-20 23:01
> Version
> 1.0.7

Then which part is `1.0.7` because the selection set initializers were only introduced in `1.1.0`?

**Comment by kc-bandari** [comment] 2023-04-21 02:48
Updated with version 1.1.2.. where the issue occurs. And worked fine when using 1.0.7

**Comment by calvincestari** [comment] 2023-04-21 06:34
After you update to 1.1.2 you must regenerate the models for them to be able to work with the new version. Did you do that?

**Comment by calvincestari** [comment] 2023-04-21 16:57
I use an M1 machine daily and have not been able to reproduce this build error. It would help to narrow it down if you could provide a standalone sample project that demonstrates this issue.

**Comment by stefannilsson** [comment] 2023-04-22 09:19
I was having the same issue with `apollo-ios-cli` **1.1.2**, and `Apollo` **1.0.7** dependency in Xcode project.
Updated `Apollo` **1.0.7** -> **1.1.2** and then it compiled!

**Comment by calvincestari** [comment] 2023-04-24 16:35
> I was having the same issue with apollo-ios-cli 1.1.2, and Apollo 1.0.7 dependency in Xcode project.
> Updated Apollo 1.0.7 -> 1.1.2 and then it compiled!

I recommend executing code generation every time you update the Apollo iOS dependency because even patch releases could alter the generated code if a bug fix is included.

**Closed** 2023-04-24 16:36 UTC
Labels: bug, awaiting response, needs investigation
