### ISSUE TITLE
Expose whether a particular result was served from cache or fetched from the server

### ISSUE THREAD

**Issue by AnandWalvekar** [apollographql/apollo-ios#170] opened 2017-10-25 03:42 UTC
**What**
iOS client want to have custom TTL(Time To Live) policy for caching

**Current Behavior**
When cachePolicy = .returnCacheDataAndFetch, client.fetch API gives 2 callbacks. The client has don't have information regarding the source of data in the closure callback

**Expected Behavior**
It would be nice if the closure give 3 params (result, dataStore, error). 
dataStore = ( .cache or .server)

**Comment by martijnwalraven** [comment] 2017-10-25 04:18
I understand your expected behavior, but I'm not sure how that relates to custom TTL. As far as I can see, that would only tell you whether data came from the cache or the network. So really curious about your reasoning and use case.

You may also be interested in the recent [Apollo Cache Control](https://github.com/apollographql/apollo-tracing) format, which it would be great to take advantage of on the client as well.

**Comment by AnandWalvekar** [comment] 2017-10-25 04:56
Apollo Cache Control => Gives performance metrix in response. This part is more of a server teams responsibility which iOS client to worry about(unless it is job is to check API performance)

**Use case**
Client maintains a cache time (say 10 sec) for a particular query. After fetching from server for the first time it would update **lastFetchedTime** . Client keep querying for the data from cache till cache time expires. Once that time expires it would make server request with .returnCacheDataAndFetch policy and updates **lastFetchedTime** again

**Concern**
The client should update **lastFetchedTime** only upon successful server response.

**Comment by martijnwalraven** [comment] 2017-10-25 07:53
Ah, I'm sorry, I included the wrong link for  [Apollo Cache Control](https://github.com/apollographql/apollo-cache-control) (since corrected)! The idea there is that servers can specify which part of a response can be cached, and for how long (TTL). That would be useful for server-controlled cache expiration.

Let's keep this issue focused on the idea of wanting to know whether a particular result was served from cache or fetched from the server. That could also include how long it has been in the cache. 

Instead of adding a third parameter to the closure, I'd prefer to make that part of `GraphQLResult`. What do you think?

**Comment by AnandWalvekar** [comment] 2017-10-25 09:20
That make sense too.

**Comment by AnandWalvekar** [comment] 2017-10-26 09:51
@martijnwalraven 
Could you please confirm when can I expect for it?

**Comment by martijnwalraven** [comment] 2017-10-26 12:37
While feature requests are always welcome, and this sounds like a useful addition, I can't give you any guarantees when it will be implemented. As with any open source project, the quickest way to get your feature in is to open a PR yourself.

**Comment by AnandWalvekar** [comment] 2017-10-27 04:06
Understood.

**Comment by AnandWalvekar** [comment] 2017-10-30 12:04
Hi @martijnwalraven 
I have signed end user license agreement but still not able to push my local branch to remote. For 
"git push -u origin GraphQLResult_Update", it is giving 
fatal: unable to access 'https://github.com/apollographql/apollo-ios.git/': The requested URL returned error: 403
"remote: Permission to apollographql/apollo-ios.git denied to AnandWalvekar."

Could you please grant me the permission

**Comment by martijnwalraven** [comment] 2017-10-30 12:08
@AnandWalvekar: Thanks for working on this! Like most open source projects, the way to contribute is not to push directly to origin, but to open a PR from your branch. That gives us the opportunity to discuss the changes before hey are merged. See [here](https://help.github.com/articles/creating-a-pull-request/) for some docs on how to open a PR on GitHub.

**Comment by AnandWalvekar** [comment] 2017-10-31 11:00
Hi @martijnwalraven 
Can you please review & merge the PR.

**Closed** 2017-10-31 19:24 UTC
