### ISSUE TITLE
Generated Models Will fail to compile on Xcode 15 if you enable ExistentialAny compiler flag 

### ISSUE THREAD

**Issue by BrentMifsud** [apollographql/apollo-ios#3205] opened 2023-08-25 21:31 UTC
### Summary

if you add the following flag to `Other Swift Flags` on Xcode 15, generated models will fail to compile:

`-enable-upcoming-feature ExistentialAny`

They all seem to be failing for the same reason(s):

- `Use of protocol 'ParentType' as a type must be written 'any ParentType'`
- `Use of protocol 'Error' as a type must be written 'any Error'`

Should add a codegen option to enable existential any for generated protocols. Or perhaps this should be the default, and a codegen config item should exist for older swift versions.

### Version

1.3.0

### Steps to reproduce the behavior

in your app build settings, add the following items to `Other Swift Flags`:

-enable-upcoming-feature
ExistentialAny

run code gen

try to compile app.

### Anything else?

Enabling compiler flags for upcoming swift 6 features was recently added in swift 5.8. More details here: https://github.com/apple/swift-evolution/blob/main/proposals/0362-piecemeal-future-features.md

Strangely enough, this issue SHOULD happen on Xcode 14.3 and up, but it only seems to happen on Xcode 15 beta.

**Comment by AnthonyMDev** [comment] 2023-08-28 19:49
Thanks for bringing this to our attention.

We should just add the any keyword to all of these files. The existential any is going to become a requirement in Swift 6, it’s just suggested for now. We should get ahead of the game and add it.

In fact, we should actually just turn the `-enable-upcoming-feature ExistentialAny` flag on in our project settings and CI tests so that we catch any more of these we may introduce in the mean time.

**Comment by BrentMifsud** [comment] 2024-02-25 16:51
@AnthonyMDev any updates on this?

Swift team just announced that Swift 6 is coming in September. So this will start to become an error in June with the Xcode 16 beta.

**Comment by AnthonyMDev** [comment] 2024-03-08 21:03
We had made a mistake in our setup when we were trying to reproduce this before. Just took another look at it today, and I see the issue now. We've bumped up the priority on this, and we'll make sure to get this done before it officially launches in Xcode 16.

If you'd like to see it happen earlier than that, we would be happy to accept a PR from you to contribute the fixes. If you want to make a contribution, I'd be happy to chat with you about what parts of the code need changes in order to make a suitable PR for this.

**Comment by BrentMifsud** [comment] 2024-03-08 23:33
Great! Thanks for the update. I'm not in too much of a rush right now. I'm still in the process of making the rest of our codebase compliant with the other Swift 6 changes.

If this becomes a blocker in future I can try and take a crack at it.

**Comment by calvincestari** [comment] 2024-04-24 21:04
Adding a note here that it looks like `ExistentialAny` [will not be in the Swift 6 release](https://forums.swift.org/t/progress-toward-the-swift-6-language-mode/68315#the-swift-6-migration-2). This _should_ be an easy enough change to make but since it was dropped from Swift 6 that may influence the priority assigned to this issue.

**Closed** 2024-06-06 18:23 UTC
Labels: bug, medium-priority
