### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code ( on version 0.13.0)

### ISSUE THREAD

**Issue by sovannarithsok** [apollographql/apollo-ios#664] opened 2019-07-24 06:59 UTC
Currently I use **Apollo 0.11.1** with pod, It works well. After I upgrade to a new version **0.13.0** I got error when build as below:

    Duplicate "graphql" modules cannot be used at the same time since different
    versions may have different capabilities and behavior. The data from one
    version used in the function from another could produce confusing and
    spurious results.
    at instanceOf (~/Desktop/App-iOS/node_modules/apollo/node_modules/graphql/jsutils/instanceOf.js:28:13)
    at isInputObjectType (~/Desktop/App-iOS/node_modules/apollo/node_modules/graphql/type/definition.js:146:34)
    at isType (~/Desktop/App-iOS/node_modules/apollo/node_modules/graphql/type/definition.js:82:120)
    at isNullableType (~/Desktop/App-iOS/node_modules/apollo/node_modules/graphql/type/definition.js:331:10)
    at assertNullableType (~/Desktop/App-iOS/node_modules/apollo/node_modules/graphql/type/definition.js:335:4)
    at new GraphQLNonNull (~/Desktop/App-iOS/node_modules/apollo/node_modules/graphql/type/definition.js:299:19)
    at GraphQLNonNull (~/Desktop/App-iOS/node_modules/apollo/node_modules/graphql/type/definition.js:301:12)
    at Object.typeFromAST (~/Desktop/App-iOS/node_modules/apollo/node_modules/graphql/utilities/typeFromAST.js:27:56)
    at ~/Desktop/App-iOS/node_modules/apollo/node_modules/apollo-codegen-core/lib/compiler/index.js:73:36
    at Array.map (<anonymous>)

    Command PhaseScriptExecution failed with a nonzero exit code

- This is my current version on system
        - apollo/2.16.1 darwin-x64 node-v12.1.0
        - xcode 10.3

Until now I didn't solve it yet. so what should I do? Please leave any comment. Thanks

**Comment by victormihaita** [comment] 2019-07-24 07:05
I think you have to delete all the `node_modules`, change the build phase to the new one and that's it.

**Comment by designatednerd** [comment] 2019-07-24 07:41
@sovannarithsok  - Yep, if you look for the `node_modules` that lives in your source root and delete it, the next time you rebuild it'll check out a fresh copy and you won't have the conflict anymore. Please confirm that this worked and we can close this one out!

**Comment by sovannarithsok** [comment] 2019-07-24 08:10
@designatednerd @victormihaita I already tried to replace a new script as below:

    SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
    cd "${SRCROOT}/${TARGET_NAME}"
    "${SCRIPT_PATH}"/check-and-run-apollo-cli.sh codegen:generate --target=swift -- 
    includes=./**/*.graphql --localSchemaFile="schema.json" API.swift

And also delete node module in source project, delete Derived data, clean project but unlucky I still get an error with build.

    Error: Can only create NonNull of a Nullable GraphQLType but got: EventInput.
    at invariant (~/node_modules/graphql/jsutils/invariant.js:18:11)
    at new GraphQLNonNull (~/node_modules/graphql/type/definition.js:779:84)
    at Object.typeFromASTImpl (~/node_modules/graphql/utilities/typeFromAST.js:39:25)
    at ~/node_modules/apollo-codegen-core/lib/compiler/index.js:73:36
    at Array.map (<anonymous>)
    at Compiler.compileOperation (~/node_modules/apollo-codegen-core/lib/compiler/index.js:71:75)
    at Object.compileToIR (~/node_modules/apollo-codegen-core/lib/compiler/index.js:15:44)
    at Object.generate [as default] (~/node_modules/apollo/lib/generate.js:29:36)
    at write (~/node_modules/apollo/lib/commands/client/codegen.js:67:54)
    at Task.task (~/node_modules/apollo/lib/commands/client/codegen.js:86:46)

    Command PhaseScriptExecution failed with a nonzero exit code

**Comment by designatednerd** [comment] 2019-07-24 08:17
So that appears to be a different error - `Error: Can only create NonNull of a Nullable GraphQLType but got: EventInput.`. Have you made any changes to your `.graphql` files since they were successfully building with the old version of the CLI?

**Comment by sovannarithsok** [comment] 2019-07-24 08:26
@designatednerd I didn't change any code in my   `.graphql` files. Why it affect to them?

**Comment by designatednerd** [comment] 2019-07-24 08:33
Just trying to narrow down what might be causing the problem! Are you able to tell which `.graphql` file is making it throw this error?

**Comment by sovannarithsok** [comment] 2019-07-24 08:40
@debergalis I have 1 `graphql` file called `Event.graphql` contains:

```
mutation AddNewEvent($eventInput: EventInput!) {
    addEvent(input: $eventInput) {
         id
    }
}
```

Then build failed with EventInput above.

**Comment by designatednerd** [comment] 2019-07-24 08:44
What happens if you remove the `!` on the parameter in `AddNewEvent`? It looks like the error is essentially saying "Can't force-unwrap something that's not optional"

**Comment by sovannarithsok** [comment] 2019-07-24 08:55
@designatednerd after remove `!` I get a new error.
`GraphQLError: Cannot query field "addEvent" on type "Mutation"`

In my `schema.json` also contains that mutation.

**Comment by designatednerd** [comment] 2019-07-24 09:02
Yeah that's damned weird - I'll ping some colleagues and see if they've got any ideas as well

**Comment by martijnwalraven** [comment] 2019-07-24 09:21
@sovannarithsok What does your schema look like? Does your `Mutation` type contain an `addEvent` field?

**Comment by sovannarithsok** [comment] 2019-07-24 09:41
@martijnwalraven Sure it contains `addEvent` I tried add `?` it show another error. 

```
Error: No operations or fragments found to generate code for.
    at write (~/node_modules/apollo/lib/commands/client/codegen.js:61:39)
    at Task.task (~/node_modules/apollo/lib/commands/client/codegen.js:86:46)
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by designatednerd** [comment] 2019-07-24 09:44
Hm - that's odd. are you using `--input=./**/*.graphql`? We ran into some issues yesterday where the previous glob I'd had in the set up wasn't searching recursively. I updated the docs but maybe you have the old glob?

**Comment by sovannarithsok** [comment] 2019-07-24 09:48
@designatednerd  in apollo documentation I see only `--includes=./**/*.graphql` not  `--input=./**/*.graphql`

**Comment by designatednerd** [comment] 2019-07-24 10:32
🤦‍♀️`--includes` is what I meant - sorry, been working with a bunch of different CLIs and I keep getting them mixed up.

**Comment by martijnwalraven** [comment] 2019-07-24 12:26
@sovannarithsok `?` is not valid GraphQL syntax, so that may explain the error you're getting after adding that, it won't be able to parse your file.

Could you post the `Mutation` and `EventInput ` types from your schema here just in case?

**Comment by sam961** [comment] 2019-07-24 13:03
Iam facing this error  after i updated pod to latest version
``++ npx --no-install apollo codegen:generate --target=swift '--includes=./**/*.graphql' --localSchemaFile=schema.json API.swift
Loading Apollo Project [started]
Loading Apollo Project [completed]
Generating query files [started]
Generating query files with 'swift' target [title changed]
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/CategoryDetailsViewController.graphql:4: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/ProductDetailsViewController.graphql:4: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/ProductDetailsViewController.graphql:11: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/SearchViewController.graphql:3: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/CartViewController.graphql:35: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/ConciergeListViewController.graphql:19: error: Unknown fragment "ProductDetails".
{ ToolError: Validation of GraphQL query document failed
    at Object.validateQueryDocument (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/errors/validation.js:29:19)
    at Object.generate [as default] (/usr/local/lib/node_modules/apollo/lib/generate.js:22:18)
    at write (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:67:54)
    at Task.task (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:86:46) name: 'ToolError' }
Generating query files with 'swift' target [failed]
→ Validation of GraphQL query document failed
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/CategoryDetailsViewController.graphql:4: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/ProductDetailsViewController.graphql:4: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/ProductDetailsViewController.graphql:11: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/SearchViewController.graphql:3: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/CartViewController.graphql:35: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/ConciergeListViewController.graphql:19: error: Unknown fragment "ProductDetails".
{ ToolError: Validation of GraphQL query document failed
    at Object.validateQueryDocument (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/errors/validation.js:29:19)
    at Object.generate [as default] (/usr/local/lib/node_modules/apollo/lib/generate.js:22:18)
    at write (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:67:54)
    at GraphQLClientProject.project.onDiagnostics [as _onDiagnostics] (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:84:29)
    at GraphQLClientProject.validate (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/project/client.js:140:18)
    at GraphQLClientProject.validateIfNeeded (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/project/base.js:136:14)
    at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/project/base.js:128:22)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5) name: 'ToolError' }
ToolError: Validation of GraphQL query document failed
    at Object.validateQueryDocument (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/errors/validation.js:29:19)
    at Object.generate [as default] (/usr/local/lib/node_modules/apollo/lib/generate.js:22:18)
    at write (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:67:54)
    at Task.task (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:86:46)
(node:45931) UnhandledPromiseRejectionWarning: ToolError: Validation of GraphQL query document failed
    at Object.validateQueryDocument (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/errors/validation.js:29:19)
    at Object.generate [as default] (/usr/local/lib/node_modules/apollo/lib/generate.js:22:18)
    at write (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:67:54)
    at GraphQLClientProject.project.onDiagnostics [as _onDiagnostics] (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:84:29)
    at GraphQLClientProject.validate (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/project/client.js:140:18)
    at GraphQLClientProject.validateIfNeeded (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/project/base.js:136:14)
    at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/project/base.js:128:22)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
(node:45931) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:45931) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.``

**Comment by designatednerd** [comment] 2019-07-24 13:49
@sam961 I recall getting something like this when I wasn't passing the correct path to my `schema.json` file - can you double check that a) The path hasn't changed and b) You're passing the path using quotation marks? ie, `--localSchemaFile="path/to/schema.json"`

**Comment by sam961** [comment] 2019-07-24 13:53
the schema.json is inside the folder of the ios project Ex: Desktop/MainProject/A/schema.json should i add path ?

**Comment by designatednerd** [comment] 2019-07-24 13:56
@sam961 The path should be relative to wherever you're running the CLI from. So if `MainProject` is your root, your path would be  `"A/schema.json"`

**Comment by sam961** [comment] 2019-07-24 14:00
<img width="597" alt="Screen Shot 2019-07-24 at 4 58 38 PM" src="https://user-images.githubusercontent.com/4921874/61799747-576ffc00-ae34-11e9-9089-9e392b4a1176.png">

I a screenshot for the path ... i added the path as u stated but i got this
`Error: Error initializing Apollo GraphQL project "Unnamed Project": Error: 
 ›   Error in "Loading schema for Unnamed Project": Error: Unable to read file 
 ›   EasyGifts-Newschema.json. ENOENT: no such file or directory, open 
 ›   'EasyGifts-Newschema.json'
Command PhaseScriptExecution failed with a nonzero exit code`

**Comment by sam961** [comment] 2019-07-24 14:04
I added the schema to the root ... but i dont know why iam getting this error too `++ npx --no-install apollo codegen:generate --target=swift '--includes=./**/*.graphql' --localSchemaFile=schema.json API.swift
Loading Apollo Project [started]
Loading Apollo Project [completed]
Generating query files [started]
Generating query files with 'swift' target [title changed]
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/CategoryDetailsViewController.graphql:4: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/ProductDetailsViewController.graphql:4: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/ProductDetailsViewController.graphql:11: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/SearchViewController.graphql:3: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/CartViewController.graphql:35: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/ConciergeListViewController.graphql:19: error: Unknown fragment "ProductDetails".
`

**Comment by designatednerd** [comment] 2019-07-24 14:04
It looks like it's looking specifically for a file called `EasyGifts-Newschema.json` - if the file you're trying to  load is `schema.json` and it's in the `EasyGifts-New` folder (can't really tell from this screenshot) you need to add a slash in there - `EasyGifts-New/schema.json`. 

^This is all assuming you're running the script from the `EasyGifts` folder. If you're running from the `EasyGifts-New` folder, you only need to pass in `schema.json`

**Comment by designatednerd** [comment] 2019-07-24 14:07
With the stuff you just posted it does seem like it's still not quite finding the schema properly. Can you please paste in your exact build script?

**Comment by sam961** [comment] 2019-07-24 14:07
```SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
cd "${SRCROOT}/${TARGET_NAME}"
"${SCRIPT_PATH}"/check-and-run-apollo-cli.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift
```
This is from the documentation

**Comment by sam961** [comment] 2019-07-24 14:09
I removed the node_modules from the project then i run this command :
`sudo npm install -g apollo` inside the PROJECT
also  i updated the pod to 0.13.0 
is it correct procedure ?

**Comment by designatednerd** [comment] 2019-07-24 14:10
OK, just trying to narrow down possibilities of what's happening. If you're still getting that error when your `schema.json` file is in the same folder as the script is being run from (basically whatever `echo $(pwd)` returns if you add it right below the `cd` command), then it sounds like you may need to re-download a newer version of the schema from your backend. 

And the pod has to be 0.13.0 for those commands to work, otherwise it looks for an older version and installs it locally. You may want to try deleting the `node_modules` in your root folder before running again.

**Comment by sam961** [comment] 2019-07-24 14:13
node_modules is deleted from the project .... could these node_modules be in another location ?

**Comment by designatednerd** [comment] 2019-07-24 14:15
If you've installed globally and the build script is finding it, then yes, they're in another location but you don't need to delete them. Are you able to build with v0.13.0? If not, which error are you receiving?

**Comment by sam961** [comment] 2019-07-24 14:20
Actually i cannot figure what is going on 
I entered this : `MacBook-Pro:~ samkad$ apollo -v
apollo/2.16.1 darwin-x64 node-v10.15.1`
outside the root file ... and the command still work ....
My project now has no node_modules
I added the schema.json to the root and inside  another folder in order to make sure that the localschema path is correct...
Now i got this error `++ npx --no-install apollo codegen:generate --target=swift '--includes=./**/*.graphql' --localSchemaFile=schema.json API.swift
Loading Apollo Project [started]
Loading Apollo Project [completed]
Generating query files [started]
Generating query files with 'swift' target [title changed]
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/CategoryDetailsViewController.graphql:4: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/ProductDetailsViewController.graphql:4: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/ProductDetailsViewController.graphql:11: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/SearchViewController.graphql:3: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/CartViewController.graphql:35: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/ConciergeListViewController.graphql:19: error: Unknown fragment "ProductDetails".
{ ToolError: Validation of GraphQL query document failed
    at Object.validateQueryDocument (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/errors/validation.js:29:19)
    at Object.generate [as default] (/usr/local/lib/node_modules/apollo/lib/generate.js:22:18)
    at write (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:67:54)
    at Task.task (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:86:46) name: 'ToolError' }
Generating query files with 'swift' target [failed]
→ Validation of GraphQL query document failed
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/CategoryDetailsViewController.graphql:4: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/ProductDetailsViewController.graphql:4: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/ProductDetailsViewController.graphql:11: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/SearchViewController.graphql:3: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/CartViewController.graphql:35: error: Unknown fragment "ProductDetails".
file:///Users/samkad/Desktop/EasyGifts/EasyGifts-New/GraphQL/ConciergeListViewController.graphql:19: error: Unknown fragment "ProductDetails".
{ ToolError: Validation of GraphQL query document failed
    at Object.validateQueryDocument (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/errors/validation.js:29:19)
    at Object.generate [as default] (/usr/local/lib/node_modules/apollo/lib/generate.js:22:18)
    at write (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:67:54)
    at GraphQLClientProject.project.onDiagnostics [as _onDiagnostics] (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:84:29)
    at GraphQLClientProject.validate (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/project/client.js:140:18)
    at GraphQLClientProject.validateIfNeeded (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/project/base.js:136:14)
    at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/project/base.js:128:22)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5) name: 'ToolError' }
ToolError: Validation of GraphQL query document failed
    at Object.validateQueryDocument (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/errors/validation.js:29:19)
    at Object.generate [as default] (/usr/local/lib/node_modules/apollo/lib/generate.js:22:18)
    at write (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:67:54)
    at Task.task (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:86:46)
(node:57034) UnhandledPromiseRejectionWarning: ToolError: Validation of GraphQL query document failed
    at Object.validateQueryDocument (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/errors/validation.js:29:19)
    at Object.generate [as default] (/usr/local/lib/node_modules/apollo/lib/generate.js:22:18)
    at write (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:67:54)
    at GraphQLClientProject.project.onDiagnostics [as _onDiagnostics] (/usr/local/lib/node_modules/apollo/lib/commands/client/codegen.js:84:29)
    at GraphQLClientProject.validate (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/project/client.js:140:18)
    at GraphQLClientProject.validateIfNeeded (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/project/base.js:136:14)
    at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/apollo/node_modules/apollo-language-server/lib/project/base.js:128:22)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
(node:57034) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:57034) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I entered a new schema...

What should i do now ?

**Comment by sam961** [comment] 2019-07-24 14:22
Note : the graphql files are inside a folder ... could this be the problem ? 
Desktop/Project/schema.json
Desktop/Project/A/schema.json
Desktop/Project/A/Graphql/*.graphql

**Comment by designatednerd** [comment] 2019-07-24 14:35
So if you're running the command from `Desktop/Project` that should theoretically find `Desktop/Project/schema.json`. Can you double-check what folder this is running in by adding `echo $(pwd)` between the line where you `cd` and the line where the script is run?

**Comment by sam961** [comment] 2019-07-24 17:32
The path for the echo was :
/Users/samkad/Desktop/EasyGifts/EasyGifts-New

**Comment by Kaakati** [comment] 2019-07-24 19:34
Hello @designatednerd 

I'm facing a problem where it says:
- 
Generic parameter 'Query' could not be inferred
Generic parameter 'Mutation' could not be inferred

nothing really changed in the GraphQL files, except that I updated to 0.13.0 and downloaded the Schema from the backend.

**Comment by designatednerd** [comment] 2019-07-24 19:40
@Kaakati Can you please double-check the update instructions in the [0.13.0 release notes](https://github.com/apollographql/apollo-ios/releases/tag/0.13.0) and then open a new issue if you're still having problems? I'm already having trouble trying to keep things straight here 😛

**Comment by designatednerd** [comment] 2019-07-24 19:43
@sam961 If you're running it from that folder and `schema.json` is directly in that folder (NOT in a subfolder of `EasyGifts-New`, it should be picking it up. 

Can you do me a favor and try the Derived Data Dance (quit xcode, delete `~/Library/Developer/Xcode/DerivedData`, restart Xcode, rebuild)? There's something REALLY bizarre going on here and maybe that'll clear out some cobwebs.

**Comment by sam961** [comment] 2019-07-24 19:59
Yes the `schema.json` is inside `EasyGifts-New` 
From the error it seems it is reading it .... but iam stuck in that error 
`Unknown fragment "ProductDetails"`
I tried deleting the derived data ,,, and restarted the laptop
also i tried to downgrade to 0.10.0
Now iam tring to remove cocoapods and reinstalling it 
:(

**Comment by designatednerd** [comment] 2019-07-24 20:06
You should only need to downgrade to 0.12.0 to have it use the old CLI. I don't know that reinstalling coocapods will do anything because the error is coming from the typescript processor installed via NPM

**Comment by trevor-scheer** [comment] 2019-07-24 20:48
@sam961 can you paste 
1) the fragment it's not able to find? `fragment ProductDetails { ... }`
2) the path where that fragment lives
3) the exact command you're running (I'm interested in the `--includes` flag)

If either of you can create and share a minimum reproduction, that would be very helpful for us to correctly (and quickly!) identify the issue.

**Comment by designatednerd** [comment] 2019-07-24 21:02
I've been working with @sam961 directly and it appears his issue was that the `.graphql` file that had, among other things, the `ProductDetails` fragment, had a syntax error at the top and was not getting parsed correctly. Interestingly, the `.graphql` file that had the syntax error was never mentioned in the errors we hit.

I figured this out this by pasting the contents of the file that contained that fragment into [this lovely GraphQL formatter](http://toolbox.sangria-graphql.org/format), which yelled at me until it actually was valid GraphQL.

Because that wasn't getting parsed, the compiler didn't know what the hell a `ProductFragment` was, and was blowing up everything else. I'll file a bug on the tooling repo because we should definitely be getting something that tells us where there's a syntax error when one occurs.

**Comment by Kaakati** [comment] 2019-07-25 07:19
> @Kaakati Can you please double-check the update instructions in the [0.13.0 release notes](https://github.com/apollographql/apollo-ios/releases/tag/0.13.0) and then open a new issue if you're still having problems? I'm already having trouble trying to keep things straight here 😛

Thanks :D It's all good now, have a great day.

**Comment by designatednerd** [comment] 2019-07-25 12:12
Hey @sovannarithsok were you able to figure out the original issue here?

**Comment by sovannarithsok** [comment] 2019-07-26 01:59
@designatednerd I rolled back to use version 0.11.1 for temporary solution. I will try new version in few day later. Thanks for your time.

**Comment by designatednerd** [comment] 2019-07-26 11:48
@sovannarithsok OK cool - i'm gonna close this issue out since it's gotten a bit confusing with multiple different problems, please open a new issue when you try again if you're still having problems!

**Closed by designatednerd** 2019-07-26 11:48 UTC
Labels: build-issue
