### ISSUE TITLE
1.0.0 Alpha+Beta - Type 'ApolloSchemaDownloadConfiguration.DownloadMethod' has no member 'apolloRegistry(settings:)' Error

### ISSUE THREAD

**Issue by jdm4344** [apollographql/apollo-ios#2376] opened 2022-07-13 20:08 UTC
## Bug report

When attempting to update Apollo to either the 1.0.0 Alpha or Beta versions, I'm receiving a buildtime error: "Type 'ApolloSchemaDownloadConfiguration.DownloadMethod' has no member 'apolloRegistry(settings:)'". Going to the enum's defintion shows the case as being present, however. The specific source is given as "\<unknown\>" but it is listed under my app's custom framework. I don't utilize this case anywhere in my own code. 

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.51.2 updating to 1.0.0-alpha.X, 1.0.0-beta.1
- Xcode version: 13.2
- Swift version: 5.5.2
- Package manager: SPM
- iOS Deployment Target: 15.0

## Steps to reproduce

1. Under Project > Package Dependencies, update apollo-ios from 0.51.2 to latest Alpha or Beta version "exact" - "1.0.0-alpha.8" or "1.0.0-beta.1"
2. In Package.swift under ApolloCodegen, update Apollo package dependency to matching version
3. Reset Package Caches followed by Resolve Package Versions under File > Packages menu
4. Clean build folder
5. Attempt to rebuild project
6. Build fails, error listed under Xcode project Issues Navigator

## Further details

Deleting the DeriveData folder has no effect, error reoccurs when rebuilding. Removing the Apollo package completely, cleaning, removing DerivedData, resetting package cache, closing Xcode, reopening, and re-adding the package also has no effect.

The project is using Swift Scripting codegen following the Codegen template project, including the latest updates under the 1.0.0-alpha branch, commit [8fa37b3](https://github.com/apollographql/iOSCodegenTemplate/commit/8fa37b32b0bddfa5370a786662665d45fcb7a175). I've attempted both updating my current implementation per changes in the updated template as well as starting from scratch by replacing my implementation with the template directly from the repo.

I've also used the RocketReserver example project with the Codegen template to see if the issue was related to the Framework in my own project, but the same error is thrown by the RocketReserver target.

Apollo and ApolloWebSocket are added to ProjectFramework > General > Frameworks and Libraries and ProjectFramework > Build Phases > Link Binary with Libraries settings. 

Project structure: 
Project             
├─ Project.xcodeproj
├─ Project.xcworkspace
├─ Project/      
├─ ProjectIntents/      
├─ ProjectIntentUI/      
├─ ProjectFramework/           
 │  └─ schema.graphqls
├─ ApolloCodegen/

**Comment by calvincestari** [comment] 2022-07-15 07:26
Thanks for the big report @jdm4344. I can't think of any obvious reason for the build error. I'll see if I can replicate through a project but if you already have a sample project with the build error that you can share, that would help speed things up.

**Comment by calvincestari** [comment] 2022-07-20 12:30
Thanks @jdm4344 - I'm not able to replicate the original build error you mentioned "Type 'ApolloSchemaDownloadConfiguration.DownloadMethod' has no member 'apolloRegistry(settings:)'" but I do see a configuration issue.

Namely `operationSearchPaths` of `ApolloCodegenConfiguration.FileInput`. [You're using the convenience initializer](https://github.com/jdm4344/apolloios-1.0.0-error-example/blob/main/ApolloCodegen/Sources/ApolloCodegen/main.swift#L128) of `ApolloCodegenConfiguration.FileInput` which uses the default value of `**/*.graphql` for `operationSearchPaths` combined with the current execution directory, which during the build will be the root of the project.

When codegen starts the following is dumped to the build log:
```
[DEBUG - ApolloCodegenLib:main.swift:62] - Source Root URL: file:///Users/calvincestari/Projects/apolloios-1.0.0-error-example/
[DEBUG - ApolloCodegenLib:ApolloCodegenConfiguration.swift:533] - Validating ApolloCodegenConfiguration(schemaName: "API", input: ApolloCodegenLib.ApolloCodegenConfiguration.FileInput(schemaSearchPaths: ["/Users/calvincestari/Projects/apolloios-1.0.0-error-example/RocketReserver/schema.graphqls"], operationSearchPaths: ["**/*.graphql"]), output: ApolloCodegenLib.ApolloCodegenConfiguration.FileOutput(schemaTypes: ApolloCodegenLib.ApolloCodegenConfiguration.SchemaTypesFileOutput(path: "/Users/calvincestari/Projects/apolloios-1.0.0-error-example/API", moduleType: ApolloCodegenLib.ApolloCodegenConfiguration.SchemaTypesFileOutput.ModuleType.embeddedInTarget(name: "API")), operations: ApolloCodegenLib.ApolloCodegenConfiguration.OperationsFileOutput.relative(subpath: nil), testMocks: ApolloCodegenLib.ApolloCodegenConfiguration.TestMockFileOutput.none, operationIdentifiersPath: nil), options: ApolloCodegenLib.ApolloCodegenConfiguration.OutputOptions(additionalInflectionRules: [], queryStringLiteralFormat: ApolloCodegenLib.ApolloCodegenConfiguration.QueryStringLiteralFormat.multiline, deprecatedEnumCases: ApolloCodegenLib.ApolloCodegenConfiguration.Composition.include, schemaDocumentation: ApolloCodegenLib.ApolloCodegenConfiguration.Composition.include, apqs: ApolloCodegenLib.ApolloCodegenConfiguration.APQConfig.disabled, warningsOnDeprecatedUsage: ApolloCodegenLib.ApolloCodegenConfiguration.Composition.include), experimentalFeatures: ApolloCodegenLib.ApolloCodegenConfiguration.ExperimentalFeatures(clientControlledNullability: false, legacySafelistingCompatibleOperations: false), schemaDownloadConfiguration: nil)
[DEBUG - ApolloCodegenLib:Glob.swift:181] - Matching /Users/calvincestari/Projects/apolloios-1.0.0-error-example/RocketReserver/schema.graphqls
[DEBUG - ApolloCodegenLib:Glob.swift:195] - Matched /Users/calvincestari/Projects/apolloios-1.0.0-error-example/RocketReserver/schema.graphqls
[DEBUG - ApolloCodegenLib:Glob.swift:110] - Expanding globstar **/*.graphql
[DEBUG - ApolloCodegenLib:Glob.swift:167] - Expanded to /Users/calvincestari/Projects/apolloios-1.0.0-error-example/ApolloCodegen/*.graphql
[DEBUG - ApolloCodegenLib:Glob.swift:167] - Expanded to /Users/calvincestari/Projects/apolloios-1.0.0-error-example/ApolloCodegen/.build/*.graphql
[DEBUG - ApolloCodegenLib:Glob.swift:167] - Expanded to /Users/calvincestari/Projects/apolloios-1.0.0-error-example/ApolloCodegen/.build/artifacts/*.graphql
```

The problem is the inclusion of the `ApolloCodegen` folder in the globstar matching path because it eventually finds the schemas and operations we use for internal testing and that's where it fails:
```
[DEBUG - ApolloCodegenLib:Glob.swift:181] - Matching /Users/calvincestari/Projects/apolloios-1.0.0-error-example/ApolloCodegen/.swiftpm/xcode/xcuserdata/calvincestari.xcuserdatad/xcschemes/*.graphql
Error: Syntax Error: Expected Name, found "[".

/Users/calvincestari/Projects/apolloios-1.0.0-error-example/ApolloCodegen/.build/checkouts/apollo-ios/Sources/AnimalKingdomAPI/animalkingdom-graphql/ccnGraphql/ClassroomPetsCCN.graphql:2:16
1 | query ClassroomPetsCCN {
2 |   classroomPets[!]? {
  |                ^
3 |     ...ClassroomPetDetailsCCN
```

The solution is to narrow the scope of the operation search path and you can do that by changing [`ApolloCodegen/main.swift` line 128](https://github.com/jdm4344/apolloios-1.0.0-error-example/blob/main/ApolloCodegen/Sources/ApolloCodegen/main.swift#L128), to the following:
```
        input: ApolloCodegenConfiguration.FileInput(
          schemaPath: SchemaOutputURL.path,
          operationSearchPaths: [SourceRootURL.appendingPathComponent("RocketReserver/**/*.graphql").path]
        ),
```
..which excludes the `ApolloCodegen` folder and finds only the `RocketReserver` operation files.

I wonder if the above configuration error is causing collateral build errors down the line. I'd resolve the above and see if the original error persists. Something else to try is to delete the `.build` and `.swiftpm` folders in `ApolloCodegen`. Since that's executed as an external package it maintains it's own dependency files so things like deleting DerivedData, etc. won't affect that.

**Comment by jdm4344** [comment] 2022-07-20 17:37
Unfortunately neither fixing that input parameter nor clearing the cache folders have resolved it. I had a coworker try building the project himself and he hasn't seen the `ApolloSchemaDownloadConfiguration` error, but did get the one you saw and was able to resolve that. He's on Xcode 13.4.1, so guess updating mine is next on the list to try.

**Comment by jdm4344** [comment] 2022-07-22 13:02
@calvincestari Updating Xcode did the trick. If your team would like to investigate the cause further I can leave this issue open, otherwise I'll go ahead and close it. Thanks again for the help!

**Comment by calvincestari** [comment] 2022-07-22 14:44
Thanks for following up @jdm4344. If it's resolved with the latest Xcode then I'm not too concerned about it; out of interest what version were you using before?

**Comment by jdm4344** [comment] 2022-07-22 14:56
I was on 13.2. It was downloaded directly from Apple's site rather than the App Store, since that release had a bug resolving Swift packages in the App Store version. Stuck with the download rather than App Store as well for updating to 13.4.1

**Closed** 2022-07-25 10:13 UTC
