### ISSUE TITLE
Code generation build script errors on Archive when project name contains a parenthesis: "("

### ISSUE THREAD

**Issue by huyanhh** [apollographql/apollo-ios#175] opened 2017-10-30 21:57 UTC
My project's name is "Project (App Store)". When I try to build a run using the simulator, everything works fine. When I try to archive build it, however, I get this message:

`error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project.`

Upon further inspection of the error, I find this in the log:

```
/Users/huyanh/Library/Developer/Xcode/DerivedData/Project-ftdvyqwnnvpowzhkmqgdtakxkzja/Build/Intermediates.noindex/ArchiveIntermediates/Project (App Store)/IntermediateBuildFilesPath/Hecatea.build/Release-iphoneos/Hecatea.build/Script-3B6ABB0E1F7B274600480825.sh: eval: line 2: syntax error near unexpected token `('
```

line 2:
```
APOLLO_FRAMEWORK_PATH="$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1)"
```

Looking around for similar errors, I find #33 has a similar problem.

Thinking that it was fixed and the problem was the space, I replaced all my spaces with hyphens, leaving me with 

`Project-(App-Store)`

I still get the error, so I renamed my schema to `Project-App-Store`, archived it again, and this time it worked.

I'm a bash newbie, so if someone could give me a hint on how to fix the problem, I'd be more than happy to help out. Other than that, if this isn't an immediately fixable problem, we should note that in the documentation at least.

**Comment by martijnwalraven** [comment] 2017-10-30 22:29
I don't have a real answer either unfortunately. Parentheses are equally problematic to spaces, so I suspect this is the same issue as #33.

**Comment by huyanhh** [comment] 2017-10-31 02:59
Okay! I added the workaround to the documentation for better visibility 😄

**Comment by martijnwalraven** [comment] 2017-12-27 07:10
Closing this as a duplicate of #33.

**Closed by martijnwalraven** 2017-12-27 07:10 UTC
