### ISSUE TITLE
Crash when accessing inner objects

### ISSUE THREAD

**Issue by PedrinhoDS** [apollographql/apollo-ios#3026] opened 2023-05-18 15:11 UTC
### Summary

I'm facing this crash `Thread 1: Fatal error: Address expected DataDict for entity, got Optional<AnyHashable>.
` whenever I try to access any object from a fragment generated through the initializer passing a dictionary or the mock library.

### Version

1.2.0

### Steps to reproduce the behavior

```
let json: [String: AnyHashable] = ["name": "ABC", "innerObject": ["name": "innerABC"]]
let fragment = MyFragmentForExample(_dataDict: DataDict(data: json, fulfilledFragments: []))
```

```
let mock = Mock<MyObject>(name: "Abc", innerObject: .init(name: "innerABC"))
let fragment = MyFragmentForExample(from: mock)
```

```
print(fragment.innerObject.name) < The crash will happen here 
```

**Comment by AnthonyMDev** [comment] 2023-05-18 20:52
Thanks for the bug report @PedrinhoDS!

Using the `SelectionSet.init(_dataDict:)` is not officially supported for external use, and the way you are using it would definitely result in this crash. It's an unsafe API. Instead you should be using `MyFragmentForExample(data: json)` which is a public API that will validate and transform your json object into the correct format for your model. I'm putting up a PR to add some more inline documentation on that internal initializer to point others in the right direction going forward.

The test mock version not working seems like a bug. I'll add it to the list and we will take a look!

**Comment by PedrinhoDS** [comment] 2023-05-19 09:51
thank you for the clarification :)

**Comment by jostster** [comment] 2023-06-02 00:56
Yea I have to say taking about the ability to init the object the old way and forcing us to use a `try` with a json object is making migration a PAIN! We do a ton of swiftUI Previews which show filler data for developing and testing and this is pretty much breaking it.

**Comment by calvincestari** [comment] 2023-06-02 16:03
@jostster - selection set initializers were reintroduced in the [`1.1.0` release](https://github.com/apollographql/apollo-ios/releases/tag/1.1.0). There is an issue with the documentation that we're still trying to figure out but the sample JSON configuration in the [Output options section](https://www.apollographql.com/docs/ios/code-generation/codegen-configuration#output-options) shows basic usage.

**Comment by jostster** [comment] 2023-06-02 18:17
@calvincestari thanks so much for linking that! I created an extension
```swift
extension RootSelectionSet {
    init(data: JSONObject) {
        // swiftlint:disable:next force_try
        try! self.init(data: data, variables: nil)
    }
}
```
which seems like it will not be needed now in place of the selection set initializers.

**Comment by ZsoltMolnarMBH** [comment] 2023-06-09 08:00
I totally agree with jostster, not having normal init method (like we had on 0.51.X) is very counter productive, and doesn't match very well with Swift API design guidelines either.

Moreover, the Mock initialized objects causing crash is another major issue. It is literally blocking our migration, which hinders our cooperation with backend teams.

@AnthonyMDev could you please prioritize this crash? We can literally not work with the current version of Apollo.

**Comment by calvincestari** [comment] 2023-06-09 16:58
> I totally agree with jostster, not having normal init method (like we had on 0.51.X) is very counter productive

@ZsoltMolnarMBH - have you tried the selection set initializers from my [comment](https://github.com/apollographql/apollo-ios/issues/3026#issuecomment-1573970988) earlier?

**Comment by jostster** [comment] 2023-06-09 16:59
Yea the comment from Calvin adds back the set initializers.

**Comment by AnthonyMDev** [comment] 2023-06-09 18:32
The reason it is crashing with `init(_dataDict)` is because that method is not intended to take raw json. That is never going to change. This is not a bug. You have two options:

1. For initializing with JSON, use the `init(data:) throws` initializer with the `try` keyword. This converts the JSON to the proper format and validates that it is well-formed json for the object.

2. Enable generation of selection set initializers and initialize your objects passing values into the parameters for each field.

I'm not clear what it is that you want @ZsoltMolnarMBH. Do these two options not allow you to do what you need to?

The only thing that may be considered a bug here is if the TestMock usage from the original post's example is causing a crash. But that only affects unit tests, and I think that might have already been fixed.

**Comment by ZsoltMolnarMBH** [comment] 2023-06-13 20:42
Hello!

The test mocks causing crashes for unit tests is what I was considering as blocking our migration. Unit tests are integral part of our project, so we cannot move forward without them not workin.

However, @calvincestari pointed out the reintroduction of selection set initializers. This turned out to be exactly what we are looking for, these also allow us to skip using Mock objects, hence I believe now we can move forward. Feel free to point out if something sounds wrong.

Thank you for the help!

**Comment by AnthonyMDev** [comment] 2023-06-13 20:49
Awesome to hear! I'm planning on working on this test mock issues as soon as I finish resolving the last few issues with the selection set initializers that impact production code.

FWIW, because selection set initializers have turned out to work so well, and test mocks have some significant limitations right now, I'm actually considering dropping support for test mocks at some time in the future and recommending people just use the initializers for testing.

However this would not happen without the opportunity for the community to provide feedback first before we drop any existing features. :)

**Comment by BobaFetters** [comment] 2023-06-21 14:09
@PedrinhoDS You also reported that you were seeing this issue with mocks as well? I was trying to replicate this in the mocks since that would definitely be a bug if it is happening there but have been unable to reproduce the issue with mocks. Can you confirm if this crash is still happening in mocks for you and provide a sample that replicates the issue?

**Comment by PedrinhoDS** [comment] 2023-06-21 14:37
hey @BobaFetters, yeah, I managed to reproduce it by using the test mocks library. 

I managed to reproduce it with something like this graphql definition:

```
fragment myFragment on ParentObject {
    id
    child {
      ...childDetailsFragment
    }
}

fragment childDetailsFragment on Child {
  id
}
```

and then on Swift on the host app I have something similar to this: 

```
func parse(myFragment: MyFragment) { 
  let childIds = myFragment.map { $0.childs.map { child in child.id } }
 .....
}
```

So when I'm writing tests for this specific function, by creating my fragment using the mocks library I'll get the error that I mentioned

**Comment by BobaFetters** [comment] 2023-06-21 15:28
@PedrinhoDS I tried setting up a test project with a setup like you described although I am not seeing the described crash. Is there any way for you to provide a small sample project that replicates the issue to aid in tracking down what the issue may be?

**Comment by PedrinhoDS** [comment] 2023-06-26 17:45
Unfortunately I can't provide more details than what I provided, you can also see the crash message that I'm facing here 
```
Thread 12: Fatal error: MyInnerFragment expected DataDict for entity, got Optional<AnyHashable>.
```

and it's crashing on DataDict line 149
```
 fatalError("\(Self.self) expected DataDict for entity, got \(type(of: data)).")
 ```

**Comment by BobaFetters** [comment] 2023-06-26 19:13
The solution regarding selection set initializers covers the regular use case, since we are unable to reproduce a crash when using test mocks I am going to close this issue as no further work is needed currently.

If anyone is still experiencing this issue and can provide a reproduction case I would be happy to re-open this issue and investigate further.

**Closed by BobaFetters** 2023-06-26 19:13 UTC
Labels: bug, awaiting response

**Comment by PedrinhoDS** [comment] 2023-06-27 18:58
Ok, I spent some time setting up a dummy project and I managed to get the same crash that we're facing on our app.
With this investigation, I also noticed that the crash only happens when I link the TestMocks generated package (which is named as `ApolloGraphQLTestMocks` on this project) on the test target. 

I'm attaching the zip with the project, and now that I know that the TestMocks is the one that's causing the issue I'll simply stop using the lib on our project. 

[ApolloIssue.zip](https://github.com/apollographql/apollo-ios/files/11886242/ApolloIssue.zip)

**Comment by BobaFetters** [comment] 2023-06-27 19:49
@PedrinhoDS Thanks for providing a reproduction case! It looks like the crash here is related to some other issues like #2686 and #2813 where the issue has to do with how the SPM dependencies are handled in an Xcode project resulting in duplicate symbols for some code causing the crash. 

I did notice in the sample project you provided if I link against the `Apollo-Dynamic` library instead of the `Apollo` library in the `ApolloIssue` target the crash goes away, not sure if that would work for your actual project or not, but it sounds as if you may have already worked around the issue for now.
