### ISSUE TITLE
Optional variables set to nil are sent as null

### ISSUE THREAD

**Issue by klanchman** [apollographql/apollo-ios#287] opened 2018-06-10 19:58 UTC
When performing a mutation with optional variables, if a variable is set to `nil`, the field is sent as `null` in the request. I expected that variables set to `nil` would be omitted from the request entirely.

Here's an example following the Star Wars schema:
```graphql
# Schema
createReview(
  episode: Episode
  stars: Int!
  commentary: String
): Review

# Client mutation
mutation CreateReviewForEpisode($episode: Episode!, $stars: Int!, $commentary: String) {
  createReview(episode: $episode, stars: $stars, commentary: $commentary) {
    stars
    commentary
  }
}
```

If I perform the above mutation using Apollo and set `commentary` to `nil`, the JSON that is sent has `"commentary": null`. In my case, this causes the API I'm using to throw an error because some of the fields I'm trying to ignore cannot be set to `null`.

---

This might be a duplicate of #185. I wasn't sure if that describes the same problem, and there was no conclusion about if there was a plan to change the behavior.

**Comment by mdilaveroglu** [comment] 2018-07-25 09:07
+1

**Comment by carloxavier** [comment] 2019-04-18 07:28
what about sending a wrapper class in the place of this param?
from the android side this is how we solve it, it gets serialized to json and looks like
 `{"value": <Any>, defined: Boolean }`

**Comment by lekz112** [comment] 2019-07-05 12:11
Issue is still not fixed - `variable` dictionary always contains all input variables even if they were not passed as an argument.

**Comment by designatednerd** [comment] 2019-07-11 14:30
What @mdilaveroglu describes [here](https://github.com/apollographql/apollo-ios/issues/287#issuecomment-407687039) as a workaround is actually expected behavior: If you do not want to send a particular parameter, you should omit it entirely from the GraphQL request. 

Basically, there are three states for anything: 

- Present, has a value
- Present, null value
- Absent

When the code is generated from a query, it assumes you want all variables you pass in to either be sent as `Present, value` or `Present, null` - which would cause them to be sent with the request. If you don't want a particular variable sent, omit it from your query.

This is also why responses are generated with double-optional variables. This allows us to say that the first optional is whether the value is present or absent, and the second optional is basically a "real" Swift optional of `some` or `none`. 

I *believe* you might be able to get this using `String?` for the commentary parameter instead of `String`, but I'm still wrapping my head around all our codegen stuff, unfortunately - leaving the parameter off entirely is probably the better idea if you don't want it sent.

**Comment by designatednerd** [comment] 2019-07-11 14:32
@klanchman or anyone else here: If you've got further questions around this, please stop by our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts) and I'll try to answer them there. I'm trying to keep the issues here for either feature requests or bugs, so I'm going to close this one out. Thank you!

**Closed by designatednerd** 2019-07-11 14:32 UTC
Labels: codegen

**Comment by klanchman** [comment] 2019-07-12 01:35
Thanks for the reply @designatednerd! I figured I'd still follow up here in case people land on this issue in the future. 

Unfortunately I have 6 parameters in this mutation right now, and the list may get larger in the future. I don't always know what attributes will be present until I'm making the request, so I'd have to make multiple permutations of this mutation to omit fields, which could get tough to maintain.

After opening this issue I made quick a workaround that removes `nil` variables before sending the request. Anyone looking for a way around this without making multiple queries can find what I did here: https://github.com/klanchman/apollo-ios/commit/c829df10a4b522e70914ffd97a5d5fc92562be74. By doing this, I'm not sure I have a way to send `null` anymore, but I haven't needed to yet.

Thank you!

**Comment by designatednerd** [comment] 2019-07-12 10:28
Yeah - i'm definitely going to be looking at ways we can handle this better in the future, but that's going to be a bit as I'm still gonna be in 🐛🔨 mode for a while. Thanks for sharing your solution!

**Comment by odanu** [comment] 2019-11-22 09:03
@designatednerd omitting the argument from GraphQL query is a workaround, but which works only in several use cases. Let me explain why it doesn't work, in our case.
We have a query, which represents a filter, has 6 optional arguments. Each of the argument corresponds to a UI field. Following your suggestion, we need to create exclude the argument from the query when we don't want to send it. Which means we need to build all possible combinations of queries out of these 6 fields. That's 6! = 720 queries.
In addition to this, I googled a bit, and it seems this behaviour is working differently in other GraphQL client environments. I think I have seen a thread where it was stated that GraphQL Android query is actually not sending `null` argument values.
I have also noticed that this is not the same with Mutations, where if the field is `nil` it is not sent as a `null`.

**Comment by designatednerd** [comment] 2019-11-24 22:25
@odanu  So this issue is about objects with Mutations, which do use the double-optional method which has the behavior described above. 

I'll respond to you in the spectrum chat with some thoughts about what's going on over on your end.

**Comment by AndyIbanez** [comment] 2020-01-06 02:52
Hi, I am currently facing this issue with a query rather than a mutation.

I have a query that currently takes 6 arguments. They can be `null`.  The request is causing the server to return a 500 error, because I'm sending the variables, but they have no value. Even if I create a query without passing anything to the constructors, the variables are still being sent with a `null` value.

Is there another workaround for this? Naturally I want to avoid modifying anything generated by the framework, so I am not doing @Klanchman's workaround just yet. The other alternative is to create queries for each possible combination of parameters, but that won't be pretty.

**Comment by odanu** [comment] 2020-01-06 06:38
@AndyIbanez please go through this [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios/is-there-a-way-to-omit-sending-null-query-argument-values~c4b2a4c3-1717-4917-90cc-611fed8dc5d3) to find the workaround.

**Comment by AndyIbanez** [comment] 2020-01-12 04:47
An update for those having the same problem.

I checked the Spectrum chat linked above. I couldn’t try the recommended workaround because I don’t control the GraphQL API that’s giving me troubles. I tried a bunch of workarounds including modifying the generated API file, creating a query manually based on the generate one, and modifying a part of the code to remove nil values, and nothing worked.

So, unfortunately, if you need to not send variables that are null, and you don’t control the API, it looks like you are SOL. I ended up spending the day removing Apollo from my app and implementing my own lightweight GraphQL wrapper.

Hopefully someday, Apollo will have proper support for this for those people who want to use it with APIs they do not control. In the meantime, writing your own wrapper seems to be the most reasonable response to the problem.

**Comment by designatednerd** [comment] 2020-01-12 21:03
Bummer - since Apollo makes a server we're generally operating under the assumption that you have *some* way of modifying your schema in partnership with whoever owns it, if only by asking them to add support for upload objects that allow this code to be generated properly.

**Comment by john-lanticse** [comment] 2020-12-11 14:12
I have to say, the Builder in Apollo-android does not send the one that was not included when building it. Wonder why this is not the case for Apollo-ios. Took me a while to finally see the issue.

**Comment by lukasz-szyszkowski** [comment] 2022-09-05 08:31
Hi, 

any news on this issue? It looks like this is still not working properly.
It shouldn't be closed without any information about this.

**Comment by klanchman** [comment] 2022-09-05 19:35
Hey @lukasz-szyszkowski, there is actually some news!

The upcoming release of v1 will solve this issue, since we'll need to explicitly pass parameters to the query that say whether the parameter should be omitted or sent as `null` 🎉 
Here's an example of how that looks:

```swift
GetAnimeDetailQuery(
    id: id,
    isAuthenticated: isAuthenticated,
    scoreFormat: scoreFormat ?? .none
)
``` 

Here, `scoreFormat` is optional. If it's `nil`, I send `GraphQLNullable.none` to omit the parameter entirely. If I needed to, I could send `GraphQLNullable.null` to send the parameter as `null` instead.

I'd recommend checking out the betas if you can, there are a lot of changes on the way!

***

If you'll be staying on v0.x for a while, I have a workaround that doesn't require forking the framework anymore. Back when Apollo changed up the underlying network layer (v0.34.0 I think), they opened up new spots for us to patch in our own behavior. In my case, I made a new `RequestBodyCreator` that omits `nil` parameters.

You can plug in your own `RequestBodyCreator` using [the advanced client creation](https://www.apollographql.com/docs/ios/initialization/#advanced-client-creation):

```swift
let transport = RequestChainNetworkTransport(
    interceptorProvider: provider,
    endpointURL: endpointURL,
    requestBodyCreator: MyRequestBodyCreator()
)
```

To make `MyRequestBodyCreator`, I just copied the default one from the framework and changed the variables to omit `nil` values. Here's what `MyRequestBodyCreator` looks like (collapsed since it's long):

<details>
  <summary>MyRequestBodyCreator.swift, <strong>click to expand</strong></summary>

```swift
import Apollo
import Foundation

// Essentially: https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/RequestBodyCreator.swift
// But with nil variables removed.

struct MyRequestBodyCreator: RequestBodyCreator {
    func requestBody<Operation: GraphQLOperation>(
        for operation: Operation,
        sendOperationIdentifiers: Bool,
        sendQueryDocument: Bool,
        autoPersistQuery: Bool
    ) -> GraphQLMap {
        // This function implementation should match upstream, except that we remove nil values from
        // the variables parameter

        var body: GraphQLMap = [
            "variables": operation.variables?.withNilValuesRemoved,
            "operationName": operation.operationName,
        ]

        if sendOperationIdentifiers {
            guard let operationIdentifier = operation.operationIdentifier else {
                preconditionFailure(
                    "To send operation identifiers, Apollo types must be generated with operationIdentifiers"
                )
            }

            body["id"] = operationIdentifier
        }

        if sendQueryDocument {
            body["query"] = operation.queryDocument
        }

        if autoPersistQuery {
            guard let operationIdentifier = operation.operationIdentifier else {
                preconditionFailure(
                    "To enable `autoPersistQueries`, Apollo types must be generated with operationIdentifiers"
                )
            }

            body["extensions"] = [
                "persistedQuery": ["sha256Hash": operationIdentifier, "version": 1]
            ]
        }

        return body
    }
}

// From: https://github.com/apollographql/apollo-ios/blob/main/Sources/Apollo/GraphQLMap.swift
fileprivate extension Dictionary where Key == String, Value == JSONEncodable? {
    var withNilValuesRemoved: [String: JSONEncodable] {
        filter { $0.value != nil }
    }
}
```
</details>

This has been working great in my app for a while now, I just forgot to post about it in this thread 😰 

Hope that helps!

**Comment by lukasz-szyszkowski** [comment] 2022-09-06 05:05
wow, that's what I call the ANSWER! Thank you, I'll check it out 👌
