### ISSUE TITLE
Quotes in operation identifers is not escaped

### ISSUE THREAD

**Issue by shkhaliq** [apollographql/apollo-ios#3268] opened 2023-10-30 15:31 UTC
### Summary

Seems like its a regression and it was previously fixed in https://github.com/apollographql/apollo-ios/issues/2671.

Using `operationIdentifiersPath` or `operationManifest` both don't handle double quotes correctly.

```
  "bbaca28047784aaadd194fb4ad2b59b63a9f327cd3026f464169bf9271ff7b63" : {
    "name": "SomeLayout",
    "source": "query SomeLayout { viewLayout { __typename someDetails(variant: "create") { __typename confirm { __typename title return description textButton someImage { __typename url } } } } }"
  },
```

apollo-ios SDK version: 1.6.1
Xcode version: 14.3.1
Swift version: 5.8.1
Package manager: SPM

### Version

1.6.1

### Steps to reproduce the behavior

1. Generate code for an operation which contains a string literal value, like "query Sections($id: String!, platform: \"ios\")"
2. Add generated code to project
3. Attempt to build project
4. Observe compiler error; generated code will contain String with non-escaped quotes like "query Sections($id: String!, platform: "ios")"

**Comment by AnthonyMDev** [comment] 2023-10-30 18:39
Thanks for bringing this regression to our attention. I'm working on getting this resolved today!

**Comment by AnthonyMDev** [comment] 2023-10-30 19:35
@shkhaliq I think I need a little clarification here. I'm unable to reproduce an error in the actual generated code.

It does seem that we aren't escaping the `"` properly in the operation manifest JSON file, making the JSON invalid. I'm going to get that fixed ASAP.

But it sounds like you're saying that there is a compilation error in the actual generated operation files. I'm not able to reproduce that. The operation files are using [Swift Raw Strings](https://www.hackingwithswift.com/articles/162/how-to-use-raw-strings-in-swift) which should not need the special characters to be escaped. In my tests, they are compiling and working just fine. 

Can you confirm if you are just reporting the invalid JSON manifest file, or is there some other error you're experiencing in the actual generated Swift operation files?

**Comment by shkhaliq** [comment] 2023-10-30 20:35
Sorry I am not getting a compilation error. I should have corrected myself. I am getting an error when I am trying persist the queries to production. After running `apollo-ios-cli generate-operation-manifest`. I am trying  to parse the JSON file using ruby

```
require 'JSON'
JSON.parse(File.read(some_file))

```
This ends up throwing an exception which it didn't before and escaping the "" fixes the issue

**Comment by AnthonyMDev** [comment] 2023-10-30 21:05
Got it. Thanks for clarifying. The fix for this is up [here](https://github.com/apollographql/apollo-ios-dev/pull/111)! I'll be getting this into the next release 1.7.0, which is coming this week.

**Closed** 2023-10-30 22:08 UTC
Labels: bug, needs investigation, planned-next
