### ISSUE TITLE
ApolloWebSocket cocoapods integration

### ISSUE THREAD

**Issue by SzymonWojcikCrustlab** [apollographql/apollo-ios#1581] opened 2020-12-17 16:39 UTC
## Bug report

Hi there! I have a problem with the integration of ApolloWebSocket via cocoapods. When I create a brand new iOS project I get `No such module 'ApolloWebSocket'` error message. Not sure what information you would need but this is a basic setup: new project -> pod init -> apollo pods -> pod install -> no module error.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.38.3
- Xcode version: 12.1
- Swift version: 5.3
- Package manager: cocoapods

## Steps to reproduce

Just create a brand new project and add `pod "Apollo"` `pod "Apollo/WebSocket"` via cocoapods
<img width="765" alt="Zrzut ekranu 2020-12-17 o 17 37 55" src="https://user-images.githubusercontent.com/76172721/102515979-a7390e00-408e-11eb-8f82-27babae05cff.png">
<img width="812" alt="Zrzut ekranu 2020-12-17 o 17 37 40" src="https://user-images.githubusercontent.com/76172721/102515990-aa33fe80-408e-11eb-9db6-db0b22077faf.png">

**Comment by SzymonWojcikCrustlab** [comment] 2020-12-17 16:57
A similar configuration for a Swift Package Manager works just fine. (Apollo + ApolloWebSocket)

**Comment by designatednerd** [comment] 2020-12-17 17:45
This is (presently) an issue because of how we have the pods set up. I should really look into fixing this but in the meantime all you have to do is remove `ApolloWebSocket` because CP merges all apollo subspecs into a single `Apollo` module.

**Comment by SzymonWojcikCrustlab** [comment] 2020-12-17 17:57
Thanks for a quick response :) I'm aware of this workaround. However, in my particular case, it's more complicated since I'm trying to build a package that supports both SPM and Cocoapods and uses Apollo for a backend connection. So in one case (building with SPM) I have to use `ApolloWebSocket` and while building with cocoapods I'm unable to use it. Any suggestions on how to work around this issue?

**Comment by designatednerd** [comment] 2020-12-17 18:17
I'm a bit confused - in theory you should only be using Apollo through one or the other, so building in something that used both shouldn't cause an issue. 

Can you tell me a bit more about your setup?

**Comment by SzymonWojcikCrustlab** [comment] 2020-12-17 19:08
Sure. I want to support cocoapods and SPM to distribute MyPackage. I have to define package dependencies:
- for cocoapods, in podspec file: `spec.dependency "Apollo/WebSocket", "~> 0.36.0"`
- for SPM, in Package.swift file: `.package(name: "Apollo", url: "https://github.com/apollographql/apollo-ios.git", from: "0.36.0")`

Let's say I have just one file `Service.swift` which depends on these web socket functionalities, so I have to use:` import Apollo` and `import ApolloWebSocket` on top of the file. 

Now, as a user who wants to install MyPackage. :
- in user's SPM based project: `Service.swift` compiles fine 
- in user's cocoapods based project: `Apollo` import is fine but `ApolloWebSocket` in `Service.swift` throws `No module...` error

Let me know if now it's clear enough or you need more information :)

**Comment by designatednerd** [comment] 2020-12-17 21:04
Got it. What we do at the moment is gate things with an `#if COCOAPODS` macro [like so](https://github.com/apollographql/apollo-ios/blob/eb323375f4f9a4df90edf528945b7df399bb240a/Sources/ApolloCodegenLib/StaticString%2BApollo.swift#L2)

**Comment by designatednerd** [comment] 2020-12-17 23:12
And, just confirmed - if we don't want to break it out into multiple pods instead of subspecs (which I don't), we'll need to keep doing that. So that is, in fact, what you should do.

**Comment by designatednerd** [comment] 2020-12-17 23:54
Can you confirm the macro works for you in your dependent library, and then we can close this out?

**Comment by SzymonWojcikCrustlab** [comment] 2020-12-18 10:44
Neat! That would do the job. Thanks for the quick responses. Fell free to close the issue :)

**Closed** 2020-12-18 18:58 UTC
Labels: dependency-management

**Comment by juliantellez** [comment] 2021-03-24 22:39
Hey guys 👋  
I am trying to implement websockets with apollo and I have run into the same problem.
Are we meant to be using the swift package manager instead?

I am learning swift at the moment and I don't understand the difference or if they can/should be combined? (cocoapods + swift package manager)
 
At the moment the Apollo module is discoverable but the websocket's source isn't

```
# Podfile
target 'MY TARGET' do
  use_frameworks!
  pod "Apollo", "~> 0.36.0"
  pod "Apollo/WebSocket"
end
```

```
# MyFile.swift
import Apollo
import ApolloWebSocket #  -> Error : No such module 'ApolloWebSocket'

```

I can see the modules in the pod folder but is not clear to me how to access them?
Thanks for your help :)

**Comment by designatednerd** [comment] 2021-03-25 20:09
Unfortunately for cocoapods this gets a little confusing, since it recompiles all the modules into a single `Apollo` module. If you use `import Apollo` and you have `Apollo/WebSocket` in your pod file, you should have access to the classes in `ApolloWebSocket`.

**Comment by ygag-vincent** [comment] 2024-05-23 11:24
Hi, I am currently using 'Apollo', '1.9.0', yet am unable to access the classes in ApolloWebSocket.

**Comment by BobaFetters** [comment] 2024-05-23 12:09
@ygag-vincent Without more detail of your project setup its hard to know specifically what the issue is, are you using SPM? CocoaPods?, however I assume its likely that you are not importing/including the ApolloWebSocket library.

Also in the future I would recommend opening a new question.

**Comment by ygag-vincent** [comment] 2024-05-24 05:20
@BobaFetters sorry next time if anything comes I will raise a new question.
I am using cocoapods, by the way, what do you mean by "including the ApolloWebSocket library"? this library comes along with Apollo itself, right? So why it should be included separately?

**Comment by BobaFetters** [comment] 2024-05-24 11:05
@ygag-vincent Can you share your podspec or a sample project demonstrating the issue? In quick testing I am able to successfully use the WebSocket code in a project. Attaching the sample project for reference.
[Uploading PodSocketTest.zip…]()
