### ISSUE TITLE
Pagination: Pager does not provide updates during a refresh

### ISSUE THREAD

**Issue by pixelmatrix** [apollographql/apollo-ios#3387] opened 2024-05-24 18:16 UTC
### Summary

It looks like `AsyncGraphQLQueryPager` does not provide updates to previously fetched objects that have changed while it's being refreshed.

I'm not sure if this is more of a bug or a feature request, but it's causing problems for our use case.

**Expected behavior:**
Changes to the data originally provided from the pager is updated while an in-flight refresh request is active.

**Actual behavior:**
The data provided from the pager does not update until the refresh is complete.

### Version

1.10.0

### Steps to reproduce the behavior

We're using the pager to fetch all pages for a particular query. Later, when we need to refresh the data we call `loadAll(fetchFromInitialPage: true)`. This particular query is a bit slow, so it can take a couple of seconds before it completes. In the meantime, we allow the user to interact with the items in the pager, which results in mutations.

It seems while the query is being refreshed, the pager does not clear the results via the `subscribe` callback, but it also does not emit any updates for local cache mutations or updates received from subscriptions until the pager completes its work.

**Repro steps:**
1. Setup an `AsyncGraphQLQueryPager` with a subscribe handler.
2. Load all the data using `loadAll(fetchFromInitialPage: true)`.
3. Start a refresh using `loadAll(fetchFromInitialPage: true)`.
4. While the refresh is pending, make a local cache mutation. You should observe that the subscribe handler is not called.
5. When the refresh has completed, you should observe that the subscribe handler is called.

**Comment by BobaFetters** [comment] 2024-05-25 03:17
@pixelmatrix Thanks for the detailed description and reproduction steps, as you said I'm not sure if this is a bug or a feature request. I will check with the team so we can see what the path forward here is.

**Comment by Iron-Ham** [comment] 2024-05-25 15:07
@pixelmatrix Ah, I see exactly what you mean. I think we can change this logic to allow cache-updates through. The intention was to not allow network updates while fetching new data (to prevent inconsistent state). 

See: 

https://github.com/apollographql/apollo-ios-dev/blob/8c01583947d96ee35b60cba0e1a61a900f0db42a/apollo-ios-pagination/Sources/ApolloPagination/AsyncGraphQLQueryPagerCoordinator.swift#L170-L182

I think we can change this logic to allow cache updates through. Thanks for calling this out!

**Comment by pixelmatrix** [comment] 2024-05-28 22:13
Yeah, this does seem like a difficult problem. As you mentioned, the old state is deleted in the pager, while the new state is still pending. However, the UI / consumer of the pager is still using on the old state, so it's in this limbo. 

In my specific use case, doing a full refresh typically does not change the data much, but we need to occasionally refresh still to ensure things are up to date. It's transparent to the user, since refreshing happens automatically. This makes it feel like a bug when data on screen does not immediately respond to mutations or subscriptions.

To your note about allowing progressive updates while loading all – that would actually be preferred in my case. Loading all the pages can take several seconds, and the first page generally includes enough data to fill the screen. It could be nice to see updates sooner.

> You could fire off the optimistic update and allow the mutation to respond with the updated data, which should trigger a cache mutation without needing to reload all data.

The problem with this is that we trigger the refresh automatically when the screen appears. While the refresh is ongoing, the user performs a mutation, which results in an update to the cache, but that update does not come through the pager until the full refresh is complete. The goal of the refresh is to sync with other clients, rather than to update the data as a result of the mutation.

> You could keep your existing logic in full, but otherwise just make an in-memory change of your data, so that your UI can update while you're re-fetching in the background.

Do you mean just updating the UI's copy of the data with the change based on the user's action? There are a couple of hurdles there. One problem is that the generated models are not mutable, so it either requires some hacks, or an abstraction to even change the data. The other challenge is that the component that owns the pager may not be aware that something has changed directly. Another view might have made the update, so we rely on the watchers to signal when something has changed.

The workaround I have implemented for now is to observe the ApolloStore directly and fetch from the cache again when a change is detected. That solves the issue for me, but it would be convenient if the pager could do it automatically, since it's a bit tedious to detect the changes and refetch.

**Comment by AnthonyMDev** [comment] 2024-05-29 19:46
@Iron-Ham I think I'm in favor of removing the `subscribe` methods. It would simplify a lot of the implementation, and I'm usually in favor of having one opinionated way of doing things rather than giving too many options (and then have to maintain support for all of them).

I'm wondering if there is another solution for this though. While waiting for all of the pages to reload, two types of changes to the data could occur.

1. Changes to the contents of individual items in the paginated list
2. Changes to the order of items in the list (inserts, removes, moves, page cursor changing, etc.)

While reloading all pages, changes to the order of the list (#2) are going to cause issues, which is why we are vacating the watchers during that time. But what if we continued to watch all of the _items_ for pages already queried for changes during a refresh (#1), and then return the entire new list only after the entire refresh is done (#2)? We could then propagate updates from the cache to the existing list while waiting for the reload to occur.

This would probably require us to go the route of an internal `ApolloStoreSubscriber` and keeping track of the list of actual items and their cache keys, rather than just using a `GraphQLQueryWatcher` for each page's query. But that's something that we have already been talking about exploring for other reasons anyways.

One limitation here is that this would require the entities in your list to have their own unique cache keys configured, but that limitation could be well documented (and even validated at run time if need be).

**Comment by Iron-Ham** [comment] 2024-06-10 14:05
I'm glad that removing the `subscribe` methods seems like the right path forward. 

In general, inserts/removals can happen even when we're paging manually and can cause issues that aren't well handled by Apollo in general now; the problem is no better or worse here than it would be otherwise. A consumer of Apollo can handle this, but it's not easy unless they're using custom models. For consumers that primarily rely on the generated models, this introduces an issue – and one that we could solve by introducing custom directives to be added as decorators to the user's query. 

I am curious to dive a bit deeper into the `ApolloStoreSubscriber` approach. My gut feeling is that I'm not sure it would work well for schemas that make heavy use of connection types (like GitHub's). Connection types don't have any identifier on them, and so wouldn't be able to update with any reorder/insertion/removal unless the calling query updates them (or a local cache mutation keyed with the query's variables mutates them).

**Comment by Iron-Ham** [comment] 2024-07-03 13:44
Related to this – and part of why I think `loadAll` returning on each fetched page is a net positive – we could add a `loadAll(until predicate: @autoclosure (Output) -> Bool)` function that lets users load all until some condition is met – either with the response data _or_ external to Apollo operations.

**Comment by AnthonyMDev** [comment] 2024-11-08 20:24
I believe this work was completed in https://github.com/apollographql/apollo-ios-dev/pull/428. We'll be releasing a new minor version of the pagination library shortly that includes the change. I'll close this issue.

If there is other work captured in this issue that has not been completed, we can re-open this.

**Closed by AnthonyMDev** 2024-11-08 20:24 UTC
Labels: bug, needs investigation
