### ISSUE TITLE
PrivacyInfo.xcprivacy file is invalid for Apollo and ApolloApi.

### ISSUE THREAD

**Issue by azilbershtein** [apollographql/apollo-ios#3359] opened 2024-03-20 19:04 UTC
### Summary

TMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/Apollo.framework/PrivacyInfo.xcprivacy”.
ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/ApolloAPI.framework/PrivacyInfo.xcprivacy”. 

### Version

1.9.2

### Steps to reproduce the behavior

Submit a version the includes the Apollo SDK to the store.

**Comment by calvincestari** [comment] 2024-03-21 01:29
Thanks for reporting the issue @azilbershtein.

> TMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/Apollo.framework/PrivacyInfo.xcprivacy”.
> ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/ApolloAPI.framework/PrivacyInfo.xcprivacy”.

This doesn't give us much detail to work with unfortunately. Is there anything else related to the error? Have you confirmed that the privacy manifest files are in those locations and look like valid xml if you manually inspect them?

> Submit a version the includes the Apollo SDK to the store.

We don't submit apps to the App Store so we cannot confirm this reproduction step; is there another way to reproduce this validation? Does Xcode have a standalone validation step that produces the same error?

**Comment by azilbershtein** [comment] 2024-03-21 08:03
The file is there, it's just invalid.
You can also see it in Xcode.
![Screenshot 2024-03-21 at 10 01 29](https://github.com/apollographql/apollo-ios/assets/64828042/5c684ccd-d3ea-4c28-a863-2c3e9f4c6a99)
API types for example have to be type and a reason.

**Comment by azilbershtein** [comment] 2024-03-21 16:11
Also, starting May 1 this will be requirement by Apple, this is next part of their warning.
While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, keys and values in your app’s privacy manifest must be in a valid format. For more details about privacy manifest files, visit: [https://developer.apple.com/documentation/bundleresources/privacy_manifest_files](https://urldefense.com/v3/__https://developer.apple.com/documentation/bundleresources/privacy_manifest_files__;!!OH6fMn4!G5jJUGbYbhoF74FakVoBTwNKDVB0Ppz89xDyiqF3fEvMijYz-DB9IUc7XRP8LX_LxEVornfXrglGBlxjDQ$)
Can you prioritize this fix?

**Comment by calvincestari** [comment] 2024-03-21 23:21
> The file is there, it's just invalid.

That is what is unclear to me - how is it invalid?

Apollo iOS does not do any tracking of any sort, nor does it use any of the reason required APIs. After reading through Apple's privacy manifest documentation again I _think_ it might be because we have arrays for the `NSPrivacyCollectedDataTypes` and `NSPrivacyAccessedAPITypes` but they don't declare any of the required types because they don't use any. Maybe we're not meant to have those arrays and they parent keys are just empty?

I made that [change](https://github.com/apollographql/apollo-ios/compare/main...fix/privacy-manifests) and pushed it up to the [fix/privacy-manifests](https://github.com/apollographql/apollo-ios/tree/fix/privacy-manifests) branch. Try point your project at that branch and see if it resolves the validation issue? If it does then I'll merge it into `main` and we can make a patch release.

**Comment by azilbershtein** [comment] 2024-03-22 08:12
The fix on your branch looks good, I don't get any warnings with it.

**Comment by calvincestari** [comment] 2024-03-22 16:21
That's great news! I'll get that merged into `main` and we'll make a patch release so everyone can get the fix.

**Closed** 2024-03-22 17:19 UTC
Labels: bug
