### ISSUE TITLE
No such module 'SQLite'

### ISSUE THREAD

**Issue by maximedegreve** [apollographql/apollo-ios#799] opened 2019-10-01 07:13 UTC
To continue the issue that I brought up in: https://github.com/apollographql/apollo-ios/issues/749
We can reproduce it on two computers (prob even more) here at work with an empty directory with a Carthage file in it:

```
github "apollographql/apollo-ios" "0.12.0"
```

and command:

```
carthage update --platform macOS --verbose
```

Result: 
![screenshot_2019-09-27_at_15 40 24](https://user-images.githubusercontent.com/980622/65778376-b9532780-e13d-11e9-8ed9-ee0ab876305d.png)

When opening the `ApolloSQLite.xcodeproj` and trying to build it the same error appears:

<img width="1512" alt="Screenshot 2019-10-01 at 08 11 26" src="https://user-images.githubusercontent.com/980622/65941578-4f7b9c00-e423-11e9-9687-a4fd28081e00.png">

Building the SQLite Mac scheme seems to work fine. 

<img width="1512" alt="Screenshot 2019-10-01 at 08 14 54" src="https://user-images.githubusercontent.com/980622/65941737-a2edea00-e423-11e9-977a-0752db2686d7.png">

**Both devices are on:**
MacOS:  10.14.6
Carthage: 0.33.0
Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
Target: x86_64-apple-darwin18.7.0
One device is a MacBook 15 inch with Touch Bar the other one is the model before without Touch Bar.

**Comment by designatednerd** [comment] 2019-10-01 14:26
Aha! Thanks for the detail - I think you've found a hole in our Carthage instructions. Try adding the `SQLite` dependency that's in [`Cartfile.private`](https://github.com/apollographql/apollo-ios/blob/master/Cartfile.private) to your own Cartfile. 

Basically, we moved that to a `Cartifle.private` so that people only using the `Apollo` lib don't have to deal with the `SQLite` and `Starscream` dependencies, but it does mean if you're using `ApolloSQLite` or `ApolloWebSocket` with Carthage, you need to add those to your own `Cartfile` as well. 

Let me know if that works - if it does, I'll leave this open until I can update the docs.

**Comment by maximedegreve** [comment] 2019-10-01 16:05
@designatednerd I've just tried again but still seem to get the same issue:

**Cartfile**:
```
github "stephencelis/SQLite.swift" "0.12.2"
github "apollographql/apollo-ios" "0.12.0"
```

**Comment by designatednerd** [comment] 2019-10-01 17:59
That's very odd. I just got it to build without issue in the dir for a new project, now trying it in a totally empty dir with that cartfile and `carthage update --platform macos,ios`. I'm running version `0.33.0` of Carthage and I'm on macOS 10.14.6, what versions of each of those are you running?

**Comment by maximedegreve** [comment] 2019-10-01 21:45
All the same.

<img width="1073" alt="Screenshot 2019-10-01 at 22 45 25" src="https://user-images.githubusercontent.com/980622/66003162-39aabd00-e49d-11e9-82f9-cb691c13b82c.png">

**Comment by maximedegreve** [comment] 2019-10-01 21:50
I've also just tried to clean
```
rm -rf ~/Library/Caches/org.carthage.CarthageKit
```

But not luck... 😭

**Comment by designatednerd** [comment] 2019-10-01 21:50
I see the folder you're using has spaces in it (`untitled folder 11.22.57`) - my recollection is Carthage doesn't play super-nice with that in all circumstances. Do you mind adding underscores in place of spaces and seeing if that fixes the issue?

**Comment by designatednerd** [comment] 2019-10-01 21:51
For what it's worth, here's what I'm seeing:
<img width="846" alt="Screen Shot 2019-10-01 at 4 50 52 PM" src="https://user-images.githubusercontent.com/1976498/66003400-a60cc880-e46b-11e9-88d7-f4b2db2c831f.png">

**Comment by maximedegreve** [comment] 2019-10-01 21:52
I got very excited about what you said but no luck. 😞
<img width="1172" alt="Screenshot 2019-10-01 at 22 52 00" src="https://user-images.githubusercontent.com/980622/66003485-22200400-e49e-11e9-98a1-b803936b0a43.png">

**Comment by designatednerd** [comment] 2019-10-01 21:57
@maximedegreve What's the exact command you're using - is it `carthage update --platform macOS --verbose` or `carthage update --platform macos --verbose`? In theory the capitalization shouldn't matter (and if it did it should just cause the damned build to fail), but as you can see I'm running the same command on my end and not reproducing the issue

**Comment by maximedegreve** [comment] 2019-10-01 22:00
I'm using 

```
carthage update --platform macos --verbose
```
Also tried without verbose.

Probably won't make a difference but here are the files and logs: https://www.dropbox.com/s/18y9fjams6ukufz/files.zip?dl=0

**Comment by designatednerd** [comment] 2019-10-01 22:30
The good news is I downloaded the files from Dropbox and was able to build just fine: 

<img width="828" alt="Screen Shot 2019-10-01 at 5 24 46 PM" src="https://user-images.githubusercontent.com/1976498/66005277-8f1ca500-e470-11e9-8610-44575ea8a79a.png">

The bad news is this really doesn't help in terms of figuring out why it's not working on your end. 

One thing I noticed in your screenshot here that isn't there on my end: The orange hammer in the top right side of the "indexing" bar (I forget what the real name of that thing is). I *think* that means you have the legacy build system turned on rather than the new build system. 

Try going to `File > Project Settings...` and validating you're using the `New Build System (Default) and not the `Legacy Build System` in the top drop-down.

**Comment by maximedegreve** [comment] 2019-10-02 06:01
Both for my own project as the `Apollo.xcworkspace` is showing the new one.
<img width="1512" alt="Screenshot 2019-10-02 at 06 59 43" src="https://user-images.githubusercontent.com/980622/66021373-6d5c0600-e4e2-11e9-85f8-726dbdde771f.png">

**Comment by designatednerd** [comment] 2019-10-02 16:32
Yep I've also installed Carthage with Homebrew, so that's not the difference either. I'm still seeing that orange hammer in the top right - if you mouse over that, does it give you details of why it's appearing?

**Comment by maximedegreve** [comment] 2019-10-03 06:53
When I hover it nothing appears, but clicking on it shows the same modal.
<img width="1512" alt="Screenshot 2019-10-02 at 06 59 43" src="https://user-images.githubusercontent.com/980622/66105219-d4e18680-e5b2-11e9-9c84-4f68362d2fb9.png">

**Comment by maximedegreve** [comment] 2019-10-03 10:53
I've got a fresh installed MacBook in the office and just installed Xcode + Carthage. Building works fine so there is likely some other stuff on our computers here that's clashing badly.

**Comment by designatednerd** [comment] 2019-10-03 15:02
OK - do you mind if we close this issue out then? (Also I'm damned curious to hear what it is if you ever figure it out, even if we do close this issue if you don't mind posting back what it was I'd appreciate it)

**Comment by maximedegreve** [comment] 2019-10-04 09:59
Yeah I don't think we'll find what the real issue was. I've even chatted to my brother who is working on Xcode at Apple and he neither got where my issue came from. If it even pops up again and I understand what's triggering it I will send you a private message. Thank you for all the help!

**Comment by designatednerd** [comment] 2019-10-04 15:02
Hah yeah your brother would definitely be the better equipped to answer that than me, then. Thank you!

**Comment by maximedegreve** [comment] 2019-10-23 12:53
After a few days the error returned, I'm really clueless why this is happening. But I know it's because ApolloSQLite is missing the framework in "Link Binary With Libraries"

See the screenshot below, it's missing the SQLite.framework
![Screenshot 2019-10-23 at 13 50 48](https://user-images.githubusercontent.com/980622/67394673-806f6c80-f59c-11e9-8409-4a5128a93184.png)

**Comment by designatednerd** [comment] 2019-10-23 16:24
Hey Maxime - can you try running `carthage build  --platform macos,ios` with this project: [Archive.zip](https://github.com/apollographql/apollo-ios/files/3763382/Archive.zip)

This is the app I've been using to check that new versions of the library are building with Carthage, and it's definitely been working on my end without any need to add the Apollo SQLite framework. I'd be curious to hear what's not working for you with this specific project, and what differences you're seeing.

**Comment by maximedegreve** [comment] 2019-10-23 20:12
Build didn't do that much because I didn't have the checkout yet I think.
But update gives me the same error see below:
<img width="675" alt="Screenshot 2019-10-23 at 21 10 52" src="https://user-images.githubusercontent.com/980622/67430202-abc47c80-f5d9-11e9-8b20-8a185c4d4cc3.png">

The error in the logs: https://www.dropbox.com/s/prbso0ur2xym1kc/carthage-xcodebuild.qjzVLk.log?dl=0

**Comment by designatednerd** [comment] 2019-10-23 20:22
Very weird. And I'm guessing since carthage isn't yelling at you about upgrading, when you run `carthage version` you now get `0.34.0`, correct? What about where your Xcode is when you run `xcode-select -p`? 

I would also try running `carthage checkout` to check out exactly the versions I've been using rather than `carthage update`. 

Are you also seeing this on machines other than the one you've been using? I ask mostly because I'm not seeing it on my end and we've not received any other complaints about it.

**Comment by maximedegreve** [comment] 2019-10-23 20:30
<img width="566" alt="Screenshot 2019-10-23 at 21 29 07" src="https://user-images.githubusercontent.com/980622/67431429-2a221e00-f5dc-11e9-80fa-ba7db9a8b1c7.png">

We've got a iOS dev in our office having the exact same issue. All those packages are not affected by node (through nvm), yarn, npm...? Right?

I have a feeling it all started happening after running the below script in our project:

```
#!/bin/sh

RED=`tput setaf 1`
GREEN=`tput setaf 2`
RESET=`tput sgr0`
CHECK="✅"
MAINTENCE="🤖"

echo "${MAINTENCE}${GREEN}   Running Dependencies script.${RESET}"
carthage version
set -e

# Check if it's a Circle build
IS_CIRCLE=false
if [[ $1 = "circle" ]]; then
   IS_CIRCLE=true
fi

if [[ ${IS_CIRCLE} == true ]]; then
  cp -r ./Marvel-Shape-shifter/Fonts ~/Library/Fonts
fi

# Install tools
# If on circle don't run certain parts because they could come preinstalled. (Eg. Carthage)
if [[ ${IS_CIRCLE} == false ]]; then
    brew update
    if brew ls --versions carthage > /dev/null == false; then
      brew install carthage
    else
      brew upgrade carthage
    fi
    brew cask install google-cloud-sdk

    if [ ! -f /usr/local/bin/sentry-cli ]; then
      curl -sL https://sentry.io/get-cli/ | bash
    fi

fi

echo "${CHECK}${GREEN}    Start carthaging...${RESET}"

carthage bootstrap --no-build --use-ssh --new-resolver
carthage build --no-use-binaries --cache-builds --platform Mac --verbose

echo "${CHECK}${GREEN}   Finished installing...${RESET}"
```

**Comment by designatednerd** [comment] 2019-10-23 22:07
If you're using a version of the library with `run-bundled-codegen.sh` then it should be using a locally bundled copy of Node and all dependencies to avoid making iOS devs deal with Node Hell™, so that shouldn't be it.

And if you've been running `carthage update` straight from the command line, it should avoid that whole script, since it's building directly off the `Apollo` project in `Carthage/Checkouts` and never coming anywhere near your project. You also indicated you nuked your carthage cache so I doubt that's it.

When the other developer having issues opens the `Apollo.xcworkspace` file, do they see the little orange hammer that you're seeing?

**Comment by maximedegreve** [comment] 2019-10-28 12:45
The hammer was indeed the issue. Even changing it to the non legacy setting it wouldn't get away so I focused today on deleting all Xcode related settings and reinstall Xcode from scratch. This resolved the issue instantly. I'm pretty certain it will come back but hopefully below will help someone else running into the exact same issue.

1) Use command:

```sudo rm -r /Applications/Xcode.app /Library/Preferences/com.apple.dt.* ~/Library/Caches/com.apple.dt.Xcode ~/Library/Application Support/Xcode ~/Library/Developer/Xcode ~/Library/Developer/CoreSimulator```

2) Restart MacOS
3) Download & reinstall Xcode
4) Start Xcode (This will also ask you to reinstall tools)

**Closed** 2019-10-28 12:49 UTC
Labels: dependency-management

**Comment by designatednerd** [comment] 2019-10-28 15:20
Oh yay! I'm glad that finally hammered it 😆

I'm really surprised it managed to get stuck in that setting so thoroughly, but I'm glad nuking it from orbit just to be sure worked!

**Comment by maximedegreve** [comment] 2019-10-29 10:54
Hahahah `nuking it from orbit`. Thank you for all the help @designatednerd
