### ISSUE TITLE
Unable to resolve build file: XCBCore.BuildFile...

### ISSUE THREAD

**Issue by DrLou** [apollographql/apollo-ios#796] opened 2019-09-27 14:57 UTC
The workspace has a reference to a missing target..
PACKAGE-TARGET:ApolloTestSupport
PACKAGE-TARGET:StartWarsAPI

where are these targets?

Xcode 11 (fresh install)

**Comment by designatednerd** [comment] 2019-09-27 14:59
Hey Lou, can you describe a bit more what you're trying to do here? Are you trying to download and open the workspace from this repo? Are you trying to add Apollo to your project through a dependency manager?

**Comment by DrLou** [comment] 2019-09-27 15:55
Git clone, directly from within Xcode - attempt to Build, install on iPhone device. Initial build successfully pulls in: Starscream and SQLite.swift. Seems perfectly reasonable so far...

Build of targets: Apollo, ApolloSQLite, ApolloWebSocket all build without error - (with, I imagine, nothing to install directly onto phone?)

I understood the project to be a standalone iOS app - have I got it wrong?

Perhaps seeing some new constraints introduced by Xcode 11 (with whcih I am not quite so familiar yet...)

**Comment by designatednerd** [comment] 2019-09-27 16:01
Yeah `Apollo`, `ApolloSQLite`, and `ApolloWebSocket` are all frameworks. The app is `TestHostiOS` in the list of targets in the `Apollo` project. You'll need to install that if you want to stuff on device, but IIRC it doesn't really do anything other than provide a blank test host to make sure we can run stuff on iOS devices. 

What are you trying to figure out?

**Comment by DrLou** [comment] 2019-09-27 16:11
Really only trying to do this, per your docs:

> Some of the tests run against a simple GraphQL server serving the Star Wars example schema

(Already running the StarWars example server)

**Comment by designatednerd** [comment] 2019-09-27 16:28
Yeah in theory you should be able to each lib on device by selecting its scheme from the drop-down, and using the test option (the wrench) instead of the run option (the play button). 

If that's not working in practice still, let me know.

**Comment by DrLou** [comment] 2019-09-27 17:09
Not working. Testing Overview:
I see four targets - all being built for _real_ device iPhone7
First: **_Build for Testing:_**
Apollo: Succeeds
ApolloSQLite: Succeeds
ApolloWebSocket: Succeeds
(in no case is anything installed onto iPhone7 device)

Apollo-package: FAIL
ApolloTests and ApolloPerformanceTests BOTH report:
Unable to resolve build file: XCBCore.BuildFile (The workspace has a reference to a missing target with GUID 'PACKAGE-TARGET:ApolloTestSupport')
Unable to resolve build file: XCBCore.BuildFile (The workspace has a reference to a missing target with GUID 'PACKAGE-TARGET:StarWarsAPI')

Testing couldn't begin on the device "iPhone7": Logic Testing Unavailable Logic Testing on iOS devices is not supported. You can run logic test on the simulator.

Shouldn't we just be able to deploy/install to a local iPhone (as we do for many other things)?

(I'm really just looking for any working Best Practices App upon which to base further, deeper testing)

**Comment by designatednerd** [comment] 2019-09-27 17:46
Aha, looks like I forgot something crucial: If you run the tests from the framework's scheme on a device, it won't work because of that error you're getting about "logic testing not supported".

Because of some silliness with Carthage, the scheme for `Test Host iOS` isn't shared. You'll need to create one locally, then in the test section of the scheme set it up to run `ApolloTests` and `ApolloCacheDependentTests`: 

<img width="894" alt="Screen Shot 2019-09-27 at 12 40 04 PM" src="https://user-images.githubusercontent.com/1976498/65789907-f90d1580-e123-11e9-9229-280c41e7071a.png">

You'll also need to set the `APOLLO_TEST_CACHE_PROVIDER` environment variable to `ApolloTestSupport.InMemoryTestCacheProvider` or it won't know what tests to run with the cache-dependent tests. 

I'm not sure why you'd be seeing an error building for iPad air, though. I just ran the tests locally on an Air simulator and it's working fine.

**Comment by DrLou** [comment] 2019-09-27 20:26
OK. To keep things consistent with your device, I've changed destination to iPhone 11 Pro Max (Simulator)- easy enough to do (but the goal remains to run/test on real iPhone device, of course)

Have got no target called **TestHost iOS**, as your screenshot shows...

Here's the project view blowup:
![image](https://user-images.githubusercontent.com/153913/65798027-aab94000-e13e-11e9-9bd9-a2c3e704fe97.png)

More importantly, I see no way to select test Target **ApolloCacheDependentTests**, even after creating a new target of _any_ name... Here's a snap of what my Apollo-Package Scheme looks like:
![image](https://user-images.githubusercontent.com/153913/65800037-78f6a800-e143-11e9-82f1-67075d5c514d.png)

A bit disoriented here. Your environment appears to be significantly different to project I've just pulled from master branch. I've added to the Apollo-Package target (to no effect), but this is not precisely what your instructions indicate.

**Comment by designatednerd** [comment] 2019-09-28 01:29
Aha! That screenshot helps immensely - I think the issue is that you've opened `Package.swift` rather than `Apollo.xcworkspace`. The way this project is set up, you'll want to use the workspace rather than just the package setup. 

SPM support is designed to allow easy *integration*, but if you want to run the tests, you'll need to use the full workspace.

**Comment by DrLou** [comment] 2019-09-28 03:33
Can you give me a clear list of bullet point items to execute?

IE; I have _no idea_ what you're talking about...

What is SPM? And I have zero interest in running any tests at all. What I do want? Is the simplest example of an iOS app, deployed to a physical iPhone7, which will show us an interface to the StarWars server - which we have running.

Specifically, what does 'use the full workspace' mean? Can you give us specific, step-by-step items to execute to - simply - make this thing _deploy and run_ on a physical iOS device?

Frankly, I don't want anything else at this point. I have zero interest in running 'tests' per se, unless they are a _sine qua non_.  _IS THIS a standalone iOS app which will give me that?_ Seems like a lot of time wasted on _it should run out of the box..._

(May I suggest that you clone your own master branch and see what builds?)

**Comment by designatednerd** [comment] 2019-09-28 15:09
Hi Lou - sorry for the frustration. I made some assumptions about your prior experience with iOS in my answers, and it also appears some Xcode behavior has changed recently. Let me back up a little and explain a couple things: 

- `SPM` is Swift Package Manager, which was integrated into Xcode with Xcode 11, which was released last week. It allows you to integrate swift "packages" (ie, dependencies) into your own code easily. Its main file is the `Package.swift` definition of what's in the library.
- Prior to the release of SPM as part of Xcode, the primary way to open a project was to open an `.xcodeproj` file or an `.xcworkspace`. 

  The `xcworkspace` is what I was referring to when I said "Workspace". In our case, the file you should open is `Apollo.xcworkspace`, since this has all the info about the targets you want to run. As of Xcode 10, this is what would open when you cloned the repo using the built-in Git checkout mechanism
- I tried cloning the repo into a new directory directly from Xcode, and it appears that in Xcode 11 because it contains a `Package.swift` in the root folder, it entirely ignores the `xcworkspace` and uses the `Package.swift` to open the project, leading to the structure you're seeing. 

  For development purposes, Apollo is using the Workspace rather than the raw package structure, so several targets visible in the workspace (including the iOS Test Host app) are not really visible to the package structure.
- Unfortunately, due to the way an older dependency manager (Carthage) works, we can't leave the scheme for the iOS Test Host application checked in to Git, so you have to create it yourself. 

One thing to be aware of before you continue: The application in this repo that I'm about to give you instructions to run doesn't actually do anything on its own, it's only there to be a host for tests. **You would need to run tests to see anything happen against the server**, which it sounds like is what you're looking for. 

Here are step by step instructions if you still need them: 

1. Close the window Xcode opened when you checked out the repo.
2. In Finder, go to where you checked out the `apollo-ios` repo. In the root of the repo you will see a file called `Apollo.xcworkspace`. Double-click that to open it. 
3. You should now see a workspace that has three Xcode projects in it: <br/><img width="306" alt="Screen Shot 2019-09-28 at 9 39 24 AM" src="https://user-images.githubusercontent.com/1976498/65818100-e7834680-e1d3-11e9-8b51-6f94b5bcf4d2.png">
4. In the drop-down in the top left of that screenshot, go down to the bottom and select `New Scheme...`: <br/><img width="232" alt="Screen Shot 2019-09-28 at 9 42 34 AM" src="https://user-images.githubusercontent.com/1976498/65818150-5c568080-e1d4-11e9-9f0b-1767268dd11f.png">
5. In the drop-down that shows up at that point, select the `TestHost iOS` application target: <br/><img width="423" alt="Screen Shot 2019-09-28 at 9 41 18 AM" src="https://user-images.githubusercontent.com/1976498/65818160-73956e00-e1d4-11e9-8d97-39bf0c51e266.png">
6. Once that scheme is created, it should be selected. Click on the drop-down again and go to `Edit Scheme...`: <br/><img width="231" alt="Screen Shot 2019-09-28 at 9 47 45 AM" src="https://user-images.githubusercontent.com/1976498/65818239-5d3be200-e1d5-11e9-902e-3fe9c5ab80eb.png">
7. Select `Test` in the left sidebar, and `Info` in the top navigation. This will allow you to add test targets to run when tests run. Click the plus sign to select targets: <br/><img width="895" alt="Screen_Shot_2019-09-28_at_9_48_09_AM_edit" src="https://user-images.githubusercontent.com/1976498/65818279-c15ea600-e1d5-11e9-88d9-92e5f09d2886.png">
8. Select the `ApolloTests` and the `ApolloCacheDependentTests` in order to get a good representation of things hitting the Star Wars server: <br/><img width="401" alt="Screen Shot 2019-09-28 at 9 48 20 AM" src="https://user-images.githubusercontent.com/1976498/65818299-eeab5400-e1d5-11e9-8a6a-2bbf611f70ec.png">
9. One those have been selected, you will need to go to the `Arguments` tab at the top of the scheme and make a couple adjustments. You will need to uncheck the `Use the Run Action's Arguments and Environments` checkbox, then hit the plus sign under `Environment Variables`. Set the key to `APOLLO_TEST_CACHE_PROVIDER` and the value to `ApolloTestSupport.InMemoryTestCacheProvider`: <br/><img width="901" alt="Screen_Shot_2019-09-28_at_9_55_45_AM_edit" src="https://user-images.githubusercontent.com/1976498/65818360-80b35c80-e1d6-11e9-9c88-598df5296d45.png">
10. Now you should be ready to test!

**Comment by designatednerd** [comment] 2019-10-08 16:14
Hi @DrLou is there anything else here I can help with, or do you mind if I close this issue out?

**Comment by DrLou** [comment] 2019-10-08 17:08
Will try this again shortly, but it's definitely an _open issue_ as far as I'm concerned. For the moment, I can't even get a faithful reproduction of the environment you illustrate above.

**Comment by designatednerd** [comment] 2019-10-08 17:17
OK. If you could share where you're getting hung up, that would be helpful.

**Comment by DrLou** [comment] 2019-10-08 17:21
Ellen - Tks for your replies… Of course I will provide detail - but am nowhere near that project at the moment, and can only play with experiments a tightly-controlled schedule. I would have hoped that would be easier out-of-the-box.

Will be in touch.

**Comment by designatednerd** [comment] 2019-10-14 19:45
Hey Lou, I get it. I'm just trying to get a better idea of what you're trying to do, and where things are tripping you up.

One thing that occurred to me: If you're looking for an example of a working application which *uses* the SDK, this repo is probably not the best place to look for it since the main thing we're doing here is building and testing the SDK, not really trying to actively consume it in a working application. 

At the moment our working sample is the [Frontpage App](https://github.com/apollographql/frontpage-ios-app), although it's not very complex. You should be able to check out that repo and open the `.xcworkspace` in there, and build and run to any device or simulator that can see your `localhost` and see an actual working application.  

Hoping to have a better example app with more complex examples up soon, but nothing specific I can tell you at this time. 

Does that help?

**Comment by designatednerd** [comment] 2019-12-11 00:36
Hey @DrLou - do you mind if we close this out for now and you can re-open a new issue if you're still having problems with this when you have time to retry?

**Comment by designatednerd** [comment] 2019-12-19 22:21
Since I haven't heard back in a few weeks, I'm gonna close this - @DrLou, please reach back out when you take another stab at this - hoping to have some better stuff set up soon in terms of getting started, hopefully that will be more of a help than this has been.

**Closed by designatednerd** 2019-12-19 22:21 UTC
Labels: build-issue, dependency-management

**Comment by noway** [comment] 2021-02-22 23:02
Switching to legacy build system in workspace settings helped me
