### ISSUE TITLE
Getting the error "Module ApolloAPI was not compiled for testing" while compiling swift package in "Release" mode in apollo v1.7.0.

### ISSUE THREAD

**Issue by divyansh0201** [apollographql/apollo-ios#3401] opened 2024-07-02 04:59 UTC
### Summary

We have recently updated Apollo to version 1.7.0 in our project. We are not willing to update it further for now. We have encountered an issue that requires resolution. Our project setup involves adding _ApolloTestSupport_ and _ApolloAPI_ as targets in our Swift Package Manager (SPM) package along with other targets. This setup is necessary because we need to generate mock responses, and we are using mocks at various places in our code.

Here is a summary of our configuration:

We have added ApolloTestSupport and ApolloAPI as targets in our SPM package.
Inside this SPM, there are multiple targets, each with separate test mock folders generated using ApolloCodegen.
The issue arises when we try to compile the project. The error messages indicate that ApolloAPI was not compiled for testing.

Error Messages:

"Module 'ApolloAPI' was not compiled for testing"
Steps to Reproduce:

Screenshots:

Error Messages:
![image](https://github.com/apollographql/apollo-ios/assets/155806539/fa0642f8-d389-4d84-a43b-7aa1616068b1)

We seek guidance on how to resolve this error without removing ApolloTestSupport and ApolloAPI from our SPM targets since mock responses are a requirement for our project. 
Any advice or suggestions would be highly appreciated.

### Version

Apollo v1.7.0

### Steps to reproduce the behavior

Update Apollo to version 1.7.0.
Add ApolloTestSupport and ApolloAPI as targets in the SPM package.
Attempt to build the project.

**Comment by calvincestari** [comment] 2024-07-02 20:52
Hi @divyansh0201 - this is being caused by the [`@testable` attribute on the import of `ApolloAPI` in `TestMock`](https://github.com/apollographql/apollo-ios-dev/blob/1.7.0/apollo-ios/Sources/ApolloTestSupport/TestMock.swift#L2). As you're finding out, release builds do not enable testability by default. `ApolloTestSupport` was originally intended only for test cases but it's use has grown outside of that.

We switched to using an [SPI](https://github.com/swiftlang/swift/blob/main/docs/ReferenceGuides/UnderscoredAttributes.md#_spispiname) import in [PR #362](https://github.com/apollographql/apollo-ios-dev/pull/362/files#diff-099e737cfdb89494fc6b5f260ceb297595ccb77dccf94bb092e2f4a8a735be0a) which was released in version [1.12.0](https://github.com/apollographql/apollo-ios/releases/tag/1.12.0). That should resolves the issue for you.

If you're not willing to move further past `1.7.0` you will need to fork from `1.7.0` and attempt to cherry-pick the PR but I'm not sure whether it's compatible.

**Closed by calvincestari** 2024-07-02 20:52 UTC
Labels: bug, needs investigation

**Comment by divyansh0201** [comment] 2024-07-03 09:52
Thanks, it worked like a charm!

> Hi @divyansh0201 - this is being caused by the [`@testable` attribute on the import of `ApolloAPI` in `TestMock`](https://github.com/apollographql/apollo-ios-dev/blob/1.7.0/apollo-ios/Sources/ApolloTestSupport/TestMock.swift#L2). As you're finding out, release builds do not enable testability by default. `ApolloTestSupport` was originally intended only for test cases but it's use has grown outside of that.
> 
> We switched to using an [SPI](https://github.com/swiftlang/swift/blob/main/docs/ReferenceGuides/UnderscoredAttributes.md#_spispiname) import in [PR #362](https://github.com/apollographql/apollo-ios-dev/pull/362/files#diff-099e737cfdb89494fc6b5f260ceb297595ccb77dccf94bb092e2f4a8a735be0a) which was released in version [1.12.0](https://github.com/apollographql/apollo-ios/releases/tag/1.12.0). That should resolve the issue for you.
> 
> If you're not willing to move further past `1.7.0` you will need to fork from `1.7.0` and attempt to cherry-pick the PR but I'm not sure whether it's compatible.
