### ISSUE TITLE
Apollo 0.33.0 + Xcode 11.7. Use of unknown directive '#filePath'.

### ISSUE THREAD

**Issue by Hazeaze** [apollographql/apollo-ios#1391] opened 2020-09-16 07:58 UTC
Hi.
I use SPM for the third-party libraries, updated Apollo from 0.32.1 to 0.33.0, and on the app build, I faced with the problem in the `FileFinder.swift`, where received an error `Use of unknown directive '#filePath'`.

![image](https://user-images.githubusercontent.com/8351874/93308812-91fcdb00-f824-11ea-9050-275be2b39282.png)

**Comment by Parilar** [comment] 2020-09-16 12:14
I got the same error

**Comment by designatednerd** [comment] 2020-09-16 19:19
`#filePath` is new in Swift 5.3, which ships with Xcode 12. You will need to use Xcode 12 for versions `0.33.0` and higher.

**Comment by designatednerd** [comment] 2020-09-17 03:31
I'm going to close this out since this is intended behavior. Enjoy Xcode 12!

**Closed by designatednerd** 2020-09-17 03:31 UTC
Labels: build-issue

**Comment by dalmatele** [comment] 2020-09-18 03:18
@designatednerd I don't think so. I used Xcode 11.7 and got the same error.
