### ISSUE TITLE
Codegen tool singularizes pluralized field names in Auto Generated Apollo GraphQL field. 

### ISSUE THREAD

**Issue by rajivd15** [apollographql/apollo-ios#1825] opened 2021-06-10 19:27 UTC
## Bug report

Pluralized field names are being singularized in Auto generated Apollo graphql file. We found the issue where two fields named - 
**badge** & **badges** are generating same struct - **struct Badge** rather than generating struct Badge and struct Badges. 

We discussed it with @AnthonyMDev and first level RCA was Codegen is not honoring the plural field names and Apollo is auto generating with singularized name. 
This same issue is also happening when using **alias** in .graphql file. 

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 2.29.0
- Xcode version: 12.3
- Swift version: 5.3.2
- Package manager: Carthage

## Steps to reproduce

Please replace this line with steps to reproduce the problem.
1. Create two objects in schema -> 
![Screen Shot 2021-06-10 at 12 21 34 PM](https://user-images.githubusercontent.com/10971883/121584539-66d79e80-c9e6-11eb-8df7-2c950c074b63.png)

2. Add to query to fetch the objects - badges & badge 
![Screen Shot 2021-06-10 at 12 22 55 PM](https://user-images.githubusercontent.com/10971883/121584681-971f3d00-c9e6-11eb-8220-ea17aef9a42a.png)

3. Build, check the auto generated code - Both objects are of the same type **Badge**
<img width="1423" alt="Auto-generated-gql file" src="https://user-images.githubusercontent.com/10971883/121584815-bddd7380-c9e6-11eb-8107-96d12a3f065c.png">

**Comment by hwillson** [comment] 2022-06-09 18:22
Will be addressed in https://github.com/apollographql/apollo-ios/issues/2101.

**Comment by AnthonyMDev** [comment] 2022-06-21 18:47
This should be working as intended in the 1.0 release currently. I'm going to add an explicit unit test for this case to ensure that it does not regress when we implement the pluralization rules.

**Comment by AnthonyMDev** [comment] 2022-06-28 23:12
This was actually still a bug in the new codegen... Fixed in #2345. Thanks so much @rajivd15 for making us aware of this issue! 1.0 will not have this bug anymore.

**Closed by AnthonyMDev** 2022-06-28 23:12 UTC
Labels: codegen

**Comment by rajivd15** [comment] 2022-06-30 19:37
@AnthonyMDev Wow. That's awesome. Thanks a lot :) 
Now, time to remove those aliases. 👍
