### ISSUE TITLE
Cannot find module '@oclif/command'

### ISSUE THREAD

**Issue by mmadjer** [apollographql/apollo-ios#1570] opened 2020-12-10 05:32 UTC
## Bug report

Build is failing with the following outcome.

```
Checking if CLI needs to be downloaded...
Zip file already downloaded!
Correct version of the CLI tarball is downloaded locally, checking if it's already been extracted...
Current verson of CLI is already extracted!
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@oclif/command'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/<REDACTED>/Pods/Apollo/scripts/apollo/bin/run:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Apollo CLI Information: 
+ /<REDACTED>/Pods/Apollo/scripts/apollo/bin/run codegen:generate --target=swift '--includes=./**/*.graphql' --localSchemaFile=schema.json GraphQLGeneratedGateway.swift --passthroughCustomScalars
```

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.38.3
- Xcode version: 12.2
- Swift version: 5
- Package manager: Cocoapods 1.10.0

## Steps to reproduce

Updated to the latest apollo-ios SDK, remove derived data, clean build folder and build.

**Comment by designatednerd** [comment] 2020-12-10 16:54
Hi - can you please share what package manager you're using to integrate apollo?

**Comment by mmadjer** [comment] 2020-12-10 21:06
Updated in initial comment

**Comment by designatednerd** [comment] 2020-12-11 03:27
Cool - in theory everything necessary to run it should be bundled with it. I just tried this on my CocoaPods-based test project and was not able to reproduce the error you saw. 

I don't *think* it's that I've got something `npm install`ed globally since I'm pretty sure we'd have had bugs on it ages ago since most iOS developers wish to avoid touching NPM with a 20 foot pole. (Not without reason)

My mind jumps to a couple possibilities: 

1. Something got borked in the download, and you need to redownload it. 
2. Something weird is going on with your script. 

Can you please try deleting the zip file and `apollo` folder in `Pods/Apollo/scripts` and then building again? That should force a redownload. 

If that doesn't work, can you share the exact script you're using to run codegen, along with the outputs of `node --version` and `npm --version`? Thank you!

**Comment by mmadjer** [comment] 2020-12-13 23:08
Deleting the zip and `apollo` folder seemed to do the trick.

However, strange is that it occurs on our CI/CD (Bitrise) platform at the same time as well.
`Pods` folder is included as part of the git repo but not the `node_modules` folder.
After deleting those files and folder and rebuilding (which should have been redownloaded), Git does not tell of any changes.
To get Bitrise working I had to commit the deleted files and rebuild on Bitrise and then re-add those files again.
So not sure what is happening there

Node version: v15.3.0
NPM version: 7.0.14

**Build phase script:**
```
SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"

cd "${SRCROOT}/${TARGET_NAME}/API/"

cd gateway
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" GraphQLGeneratedGateway.swift --passthroughCustomScalars

cd ../syndicate
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" GraphQLGeneratedSyndicate.swift --passthroughCustomScalars
```

**Comment by mmadjer** [comment] 2020-12-13 23:16
Actually, it keeps failing on Bitrise with the same error. I had a test branch to try that abov scenario out. Which was green. Merged that to master and failing. Same Bitrise workflow. hmm...

**Comment by mmadjer** [comment] 2020-12-14 01:12
If I exclude `zip` file and apollo folder in `Pods/Apollo/scripts` from git, then it works everytime.

So something odd is going on which was not the case before.
Let me know if you want/need more information to potentially trace it down.

**Comment by designatednerd** [comment] 2020-12-14 02:22
I wonder if there's some weird caching happening on the bitrise end. In theory, the bash script or the swift script should be checking the hash of the zip file to determine if it needs to be deleted and replaced before it tries to run anything, so I'm not sure why that wouldn't be working.

**Comment by mmadjer** [comment] 2020-12-14 03:53
Any particular order the build phase script should run?
Further to that, I just noticed the checkbox `Based on dependency analytics` is ticked on for that Apollo build phase script. The hint of that checkbox says `Will skip in incremental builds if inputs, context, or outputs haven't changed`.

**Comment by designatednerd** [comment] 2020-12-14 04:23
it needs to run prior to trying to actually compile your classes, but that shouldn't have any effect on whether the CLI itself builds or not. 

In theory the dependency analytics shouldn't have anything to do with the error you're seeing,  but it certainly could be worth unchecking to see if that's the problem.

**Comment by mmadjer** [comment] 2020-12-15 09:38
Well, now it doesn't occur / can't replicate it anymore.

**Comment by designatednerd** [comment] 2020-12-15 23:40
Weird! That does sort of reinforce my hunch that there was some kind of caching issue going on. 

Do you mind if we close this issue out?

**Comment by mmadjer** [comment] 2020-12-16 00:04
Yeah very weird.

Sure close it off.

Thanks a lot for you help.

**Closed** 2020-12-16 02:58 UTC
Labels: build-issue

**Comment by ignkarman** [comment] 2022-05-10 21:25
Leaving this here in case it helps anyone else in the future.

This error occurred for me after updating from a very old version of Apollo to the latest, and this issue was only occurring on our CI/CD Platform, Bitrise. 

I resolved this issue by fully removing and then reinstalling the Apollo CocoaPod, and also adding `apollo.tar.gz` to our gitignore, forcing CI to download a fresh copy when running the `run-bundled-codegen.sh` script.
