### ISSUE TITLE
Xcode Install CLI fails for versions >=1.8

### ISSUE THREAD

**Issue by pjf-amexgbt** [apollographql/apollo-ios#3333] opened 2024-02-09 19:54 UTC
### Summary

Xcode is unable to download/install CLI from Xcode from version 1.8 on.

This is what happened in previous versions (including 1.7):

<img width="357" alt="Screenshot 2024-02-08 at 17 07 06" src="https://github.com/apollographql/apollo-ios/assets/159570584/14c26ec7-8e87-4c22-b6ba-d82e7797499d">

This is what happens now (including 1.9):

<img width="632" alt="Screenshot 2024-02-08 at 17 05 37" src="https://github.com/apollographql/apollo-ios/assets/159570584/2c24539b-a9f9-4cf5-a54b-68ae917288f7">

### Version

1.9

### Steps to reproduce the behavior

Now:
1. Add Apollo library to iOS App with version 1.9
<img width="787" alt="image" src="https://github.com/apollographql/apollo-ios/assets/159570584/ad235cb5-18f0-4d98-85e5-572d5ba498a0">
2. Install CLI:
<img width="392" alt="image" src="https://github.com/apollographql/apollo-ios/assets/159570584/174fd427-b65b-4322-bf07-6dcd8a20f6d5">
3. Error received and CLI not created:
<img width="632" alt="Screenshot 2024-02-08 at 17 05 37" src="https://github.com/apollographql/apollo-ios/assets/159570584/c25e7d75-fe26-41a1-a9ac-6b0182c6e426">

1. Add Apollo library to iOS App with version 1.7
<img width="772" alt="image" src="https://github.com/apollographql/apollo-ios/assets/159570584/529519cf-bf3a-4f15-bd5e-d389e4411ebd">
2. Install CLI:
<img width="392" alt="image" src="https://github.com/apollographql/apollo-ios/assets/159570584/174fd427-b65b-4322-bf07-6dcd8a20f6d5">
3: CLI Created
<img width="480" alt="image" src="https://github.com/apollographql/apollo-ios/assets/159570584/8c7344e0-cdc1-4b8f-bbc7-510215fe6278">

### Anything else?

Confirmed with a coworker and it's happening for them as well. It's possible this is being stopped by the corporate VPN, but it's unclear based on the error shown

**Comment by BobaFetters** [comment] 2024-02-09 20:09
@pjf-amexgbt Hmm the error seems to think its an issue unpacking the .tar.gz, but it could honestly also be a download issue like you mentioned as well. I can look into some and see if I can reproduce, and also maybe improve the error logging some to be more clear, in the meantime can you take a look in your project directory while running the plugin and see if you see a `apollo-ios-cli.tar.gz` file show up and maybe be deleted? That would help tell us if the download is actually happening or not.

**Comment by BobaFetters** [comment] 2024-02-10 07:16
The `tar: Error opening archive: Failed to open 'apollo-ios-cli.tar.gz'` can definitely be thrown if the .tar.gz file is missing which would give further evidence that the download just isnt happening. @pjf-amexgbt Possible you could try to just manuall run the curl command to do the download in terminal and see what kind of errors/issues it gives you maybe related to your VPN?

`curl -L https://www.github.com/apollographql/apollo-ios/releases/download/1.8.0/apollo-ios-cli.tar.gz`

**Comment by BobaFetters** [comment] 2024-02-16 03:36
Closing this since there hasn't been any activity, if this is still an issue feel free to reopen.

**Comment by pjf-amexgbt** [comment] 2024-02-20 17:48
@BobaFetters Apologies for the slow response, forgot to link accounts so didn't get a notification.

Yeah it does seem to be a download issue. A VPN block was my guess, but I did test with
`curl -L "https://www.github.com/apollographql/apollo-ios/releases/download/1.8.0/apollo-ios-cli.tar.gz" -s -o "apollo-ios-cli.tar.gz"` and it downloads the file without issue.

I did a bit of additional investigation playing with "download-cli.sh" am getting some odd results.

- When run from Xcode with curl -v:  "SSL certificate problem: self signed certificate in certificate chain"
- When running the script directly from the terminal: The file downloads/saves, but `tar -xvf "$FILE_PATH"` unpacks it in the `script` folder instead of in place. (probably not relevant to the issue)
- When "apollo-ios-cli.tar.gz" is in the project, the Xcode command works correctly.

So it seems it may be caused by some combination of running it through Xcode and the wonderful corporate laptop "Security" 🫠

However, wondering if there's a reason to download the file? Especially when it seems to (currently) be included in the repo: https://github.com/apollographql/apollo-ios/tree/main/CLI

**Comment by pjf-amexgbt** [comment] 2024-02-20 17:51
Also, I apparently am unable to re-open. Feel free to do so, I should be more responsive now :)

**Comment by BobaFetters** [comment] 2024-02-20 18:36
Ah thanks for the callout on the documentation needing updated, will take care of that. As far as being able to build it yourself, that isn't possible with the plugin anymore because of the changes that were made to our git structure to modularize our libraries, more info on that [here](https://github.com/apollographql/apollo-ios/issues/3240) TLDR; the executable is now part of a separate repo/spm package than the main client library that contains the plugin. So technically you could still download that package and build it yourself you would just need to ensure you pull a matching version.

Also it looks like we should be able to fix the Cocoapods issue we had so the plan currently is to move forward with fixing that and then working on fixing the curl command for the plugin to resolve the issue you are seeing.

**Closed** 2024-05-17 17:40 UTC
Labels: bug, needs investigation
