### ISSUE TITLE
Codegen generating double optionals

### ISSUE THREAD

**Issue by malonehedges** [apollographql/apollo-ios#1529] opened 2020-11-19 07:11 UTC
Apollo iOS 0.36.0

Generation script:
```sh
"${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" --passthroughCustomScalars "Path/To/My/GraphQLAPI.swift"
```

With my schema that looks like this
<img width="319" alt="image" src="https://user-images.githubusercontent.com/12092296/99633069-2a653680-29f3-11eb-8f50-989badc46f22.png">

The generated code looks like this
<img width="858" alt="image" src="https://user-images.githubusercontent.com/12092296/99633136-4537ab00-29f3-11eb-8a72-522d2c7dc6c6.png">

when it should just be `Bool?` instead of `Bool??`

**Comment by designatednerd** [comment] 2020-11-19 16:02
This is expected behavior for input objects. 

`Boolean` is optional, but for input objects, you also have the option of not passing any value at all. If you pass a value of `null`, it will overwrite whatever is already on the server. If you do not pass any value at all, it will not affect what's already on the server.

In future codegen we'll be working with a custom enum that makes this clearer, but for what we've got now, the double-optional is the best way to represent it.

**Comment by malonehedges** [comment] 2020-11-19 18:38
Ah gotcha, that makes sense 👍

**Comment by malonehedges** [comment] 2020-11-19 18:40
The codegen init doesn't allow me to pass some of the values though, changing my schema to have develop required means it takes in a `String` in swift instead of `String?`

**Comment by malonehedges** [comment] 2020-11-19 18:42
<img width="339" alt="image" src="https://user-images.githubusercontent.com/12092296/99709287-d76f9b80-2a53-11eb-8c63-eee5250c4f73.png">

<img width="614" alt="image" src="https://user-images.githubusercontent.com/12092296/99709306-dccce600-2a53-11eb-9535-9981f3f3323e.png">

**Comment by malonehedges** [comment] 2020-11-19 18:43
Or do you mean I keep the schema as it was originally and use the double optionals with that context

**Comment by designatednerd** [comment] 2020-11-19 19:48
@malonehedges mind if we close this out?

**Comment by designatednerd** [comment] 2020-11-23 22:24
Closing this out as intended behavior.

**Closed by designatednerd** 2020-11-23 22:24 UTC
Labels: codegen
