### ISSUE TITLE
conflicting types String! and String

### ISSUE THREAD

**Issue by IvanovDeveloper** [apollographql/apollo-ios#69] opened 2017-03-09 12:19 UTC
I cant generate code with some fields

![2017-03-09 14 18 47](https://cloud.githubusercontent.com/assets/14201895/23749953/5fad06cc-04d3-11e7-9c30-0b0f08f8f373.png)

**Comment by martijnwalraven** [comment] 2017-03-09 12:22
This is a GraphQL validation error, so it isn't Apollo specific. If you try to run the query in GraphiQL, you should get the same error.

I don't know what your schema looks like, but there seems to be a conflict between `name` fields coming from different types (probably interfaces?), with one being non-null (`String!`).

**Comment by IvanovDeveloper** [comment] 2017-03-09 12:23
at GraphiQL a have not this problem

**Comment by martijnwalraven** [comment] 2017-03-09 12:24
Then maybe the `schema.json` is not up to date?

**Comment by IvanovDeveloper** [comment] 2017-03-09 12:25
I will try update

**Comment by IvanovDeveloper** [comment] 2017-03-09 13:03
![2017-03-09 15 03 03](https://cloud.githubusercontent.com/assets/14201895/23751343/8b322d44-04d9-11e7-8377-6a3fe42f9f7e.png)

**Comment by martijnwalraven** [comment] 2017-03-09 13:11
That's another GraphQL validation error, so I suspect the problem is with your schema.

**Comment by martijnwalraven** [comment] 2017-03-09 13:18
Oh wait, I should have looked better, that is an error in the generated Swift code. Can you post some more context?

**Comment by IvanovDeveloper** [comment] 2017-03-09 14:49
Of course

**Comment by IvanovDeveloper** [comment] 2017-03-09 14:50
I will prepare all necessary information and send tomorrow

**Comment by martijnwalraven** [comment] 2017-03-15 07:36
@IvanovDeveloper: Any updates? Is this still an issue for you?

**Comment by IvanovDeveloper** [comment] 2017-03-15 10:10
At the moment I have not yet encountered this problem again

**Comment by martijnwalraven** [comment] 2017-03-15 10:37
I'll close the issue then, and you can always reopen it when you encounter it again.

**Closed by martijnwalraven** 2017-03-15 10:37 UTC
