### ISSUE TITLE
Trailing newline thrash with Xcode 10.2

### ISSUE THREAD

**Issue by erikstrottmann** [apollographql/apollo-ios#531] opened 2019-05-01 00:35 UTC
I’m setting up Apollo in an app for the first time, and I have noticed that Apollo and Xcode 10.2 disagree about whether a file should end in a trailing newline, causing the file to be modified every time it is opened or the project is built.

**Intended outcome:**
Apollo should generate an `API.swift` with a newline `\n` character at the end of the file.

**Actual outcome:**
Apollo generates an `API.swift` that does not have a newline `\n` character at the end of the file. Every time Xcode 10.2 opens the file, it adds a newline to the end of the file. Every time the project is built, Apollo removes the trailing newline.

**How to reproduce the issue:**
- Use Apollo 0.10.1 and Xcode 10.2
- Add your Apollo-generated `API.swift` to your Xcode project
- Open `API.swift` in Xcode, and see that Xcode adds a newline to `API.swift`
- Build the project, and see that Apollo regenerates `API.swift` without a newline

**Comment by michaelnisi** [comment] 2019-05-02 09:30
What Text Editing Preferences are you using? I could not reproduce this with Xcode Version 10.2.1 (10E1001).

![Screenshot 2019-05-02 at 11 14 19](https://user-images.githubusercontent.com/108903/57066511-a7737280-6ccc-11e9-8b03-4259d0437360.png)

Anyone else seeing this issue?

**Comment by erikstrottmann** [comment] 2019-05-02 17:35
It looks like, while Xcode automatically modifies the file when it’s opened (see screenshot indicating modified file), I still have to save the file for the additional whitespace to be reflected on the filesystem.

<img width="190" alt="modified file" src="https://user-images.githubusercontent.com/2874864/57094167-b35b3680-6cc4-11e9-8053-2c4132a05b2e.png">

I have “Automatically trim trailing whitespace” and “Including whitespace-only lines” enabled, but “Convert existing files on save” disabled. However, I still experience the issue if I copy your settings exactly. I also experience the issue when I use Xcode 10.1.

<img width="800" alt="Xcode Text Editing Preferences" src="https://user-images.githubusercontent.com/2874864/57093782-a5f17c80-6cc3-11e9-985c-44f9366ea751.png">

To better illustrate my issue, here’s the end of the output of `cat API.swift` as generated by Apollo:

<img width="570" alt="Apollo-generated" src="https://user-images.githubusercontent.com/2874864/57094279-07feb180-6cc5-11e9-9324-7431763a6103.png">

And here’s the end of the output of `cat API.swift` after Xcode appends a trailing newline:

<img width="570" alt="Xcode-modified" src="https://user-images.githubusercontent.com/2874864/57094284-0b923880-6cc5-11e9-82d6-3ed3efa2d6ec.png">

Note how the last brace of the Apollo-generated file appears on the same line as my command prompt, while the last brace of the Xcode-modified file appears on its own line, as expected.

[According to the POSIX standard, each line in a file, including the last line, should end in a newline `\n` character.](https://stackoverflow.com/a/729795) GNU and Unix tools like `cat` expect this behavior, so they don’t behave nicely when a file does not end in a trailing newline.

**Comment by michaelnisi** [comment] 2019-05-03 09:44
Thank you for the detailed follow-up. Sounds like I should be able to reproduce it.

**Comment by erikstrottmann** [comment] 2019-05-03 16:55
When I use Vim with `:set list!`, my freshly generated file shows a newline `$` too, but if I save the file from Vim, Git shows that there’s now a new line. It looks like Vim also inserts the newline if it isn’t already present.

I think that’s default behavior, but just in case, here’s my `~/.vimrc`:

```vim
syntax enable

set incsearch
set hlsearch

autocmd FileType gitcommit setlocal spell textwidth=72
```

**Comment by michaelnisi** [comment] 2019-05-03 17:20
Confirmed 😅

![Screenshot 2019-05-03 at 19 18 54](https://user-images.githubusercontent.com/108903/57154103-50f35a80-6dd8-11e9-809d-4fd135920256.png)

**Comment by michaelnisi** [comment] 2019-05-03 17:45
Although, from a quick glance, I reckon this is not Swift specific, I will try expose this issue with a test for [apollographql/apollo-tooling/packages/apollo-codegen-swift](https://github.com/apollographql/apollo-tooling/tree/master/packages/apollo-codegen-swift).

**Comment by michaelnisi** [comment] 2019-05-04 05:59
I guess writing TypeScript is a thing I do now. 🤷‍♂️

**Comment by designatednerd** [comment] 2019-07-24 07:57
This has been addressed by switching to the updated code generation in 0.13.0!

**Closed by designatednerd** 2019-07-24 07:57 UTC
Labels: codegen
