### ISSUE TITLE
Generate Apollo GraphQL API phase not executing properly

### ISSUE THREAD

**Issue by attheodo** [apollographql/apollo-ios#34] opened 2016-12-13 20:57 UTC
I am having trouble getting the build phase execute prperly. I have properly created the build script and using default paths for my `*.graphql` and `schema.json`. It looks like Xcode is running the generation phase but no `API.swift` file is generated.

Any directions on how to debug this?

 Using Apollo `0.3.1` and `apollo-codegen` `0.8.2`

**Comment by martijnwalraven** [comment] 2016-12-13 21:06
Could you have a look at the command arguments in the build output (see screen shot)?

<img width="984" alt="screen shot 2016-12-13 at 22 04 40" src="https://cloud.githubusercontent.com/assets/54485/21159165/5d6a5a2c-c180-11e6-90b7-3773adbeed4e.png">

**Comment by attheodo** [comment] 2016-12-13 21:14
@martijnwalraven it only displays `+exec apollo-codegen` ...weird. Any ideas why is this happening?

**Comment by martijnwalraven** [comment] 2016-12-13 21:22
@attheodo: It seems like `check-and-run-apollo-codegen.sh` somehow isn't picking up the rest of the arguments. Are you sure this is the last line of the build script:

```sh
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate $(find . -name '*.graphql') --schema schema.json --output API.swift
```

**Comment by attheodo** [comment] 2016-12-13 21:23
This is exactly what's inside the script:
```
APOLLO_FRAMEWORK_PATH="$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1)"

if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
exit 1
fi

cd "${SRCROOT}/${TARGET_NAME}"
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate $(find . -name '*.graphql') --schema schema.json --output API.swift
```

**Comment by martijnwalraven** [comment] 2016-12-13 21:26
Not sure what could be going on here then. So the command output is just `+exec apollo-codegen`, without `generate` or any of the other arguments?

**Comment by attheodo** [comment] 2016-12-13 21:28
Exactly
![image](https://cloud.githubusercontent.com/assets/881195/21159945/c9a952fa-c18b-11e6-80f0-1d44dfd75157.png)
![image](https://cloud.githubusercontent.com/assets/881195/21159970/e0d065ea-c18b-11e6-91b3-744dd8740b7e.png)

**Comment by martijnwalraven** [comment] 2016-12-13 21:34
Anything special about the name of the directory the project or the target is in maybe? I'm just guessing now, no idea why that would cause this behavior.

**Comment by attheodo** [comment] 2016-12-13 21:47
@martijnwalraven not really

```
$ pwd 
/Users/thanosth/Documents/dev/waldo/WaldoMini/WaldoMini
```

By deleting and re-adding the script I somehow arbitrarily got it to work. It compained about not finding schema. But then, subsequent builds was just not spitting any errors, still ignoring the rest of the arguments.

Does that tell you anything?

**Comment by martijnwalraven** [comment] 2016-12-14 09:11
@attheodo: Have you been able to get this to work, or do you still experience the same issue? Really no idea what could be causing this.

**Comment by attheodo** [comment] 2016-12-14 09:37
Not really. For now I just extracted the apollo-codegen part into a shell script and run it manually whenever I want to generate the files.
Really frustrating

Get Outlook for iOS




On Wed, Dec 14, 2016 at 11:11 AM +0200, "Martijn Walraven" <notifications@github.com> wrote:












@attheodo: Have you been able to get this to work, or do you still experience the same issue? Really no idea what could be causing this.

**Comment by martijnwalraven** [comment] 2016-12-14 10:32
@attheodo: I'm sorry to hear that. You mentioned you did get it to work at some point. Is there any way you can retrace your steps and find out what changed?

**Comment by attheodo** [comment] 2017-01-30 14:00
@martijnwalraven I still have the same issues in a different project. Any help on how I could debug this?

**Comment by martijnwalraven** [comment] 2017-01-30 14:09
Hmmm, I'm just as confused as before. Are you running the latest versions? Do you still get `+exec apollo-codegen` without any arguments?

**Comment by attheodo** [comment] 2017-01-30 14:11
@martijnwalraven yes I am on the latest versions. Actually I am getting `++exec apollo-codegen` (with an extra `+` in the beginning)

**Comment by martijnwalraven** [comment] 2017-01-30 14:24
No idea what the difference is, but I'm also getting `xx` now:
<img width="1948" alt="screen shot 2017-01-30 at 15 19 54" src="https://cloud.githubusercontent.com/assets/54485/22426491/afff55ea-e6ff-11e6-8f43-5a67b0c8ad3a.png">

Are you running a custom shell environment or Bash version?

**Comment by attheodo** [comment] 2017-01-30 14:30
@martijnwalraven I am running `zsh` with `oh-my-zsh` on my terminal. I am not sure whether this is an issue though since on the "Build Phase" the script is directed to use `/bin/sh` as the shell.

**Comment by martijnwalraven** [comment] 2017-01-30 14:36
Yeah, that shouldn't be an issue. I'm also running `zsh` with `oh-my-zsh`.

I don't really know how to debug this. Shell scripts aren't one of my strongest points :)

Have you had a look at [`check-and-run-apollo-codegen.sh`](https://github.com/apollostack/apollo-ios/blob/master/scripts/check-and-run-apollo-codegen.sh) to see if anything jumps out to you?

**Comment by jzhw0130** [comment] 2017-05-18 05:38
@attheodo  @martijnwalraven 

I'm getting the same problem?
Is there any way to solve the problem?

Thanks a lot.

Jing

**Comment by martijnwalraven** [comment] 2017-05-18 05:42
@jzhw0130: Are you sure it's the same problem? What do the command arguments in the build output look like for you (see [above](https://github.com/apollographql/apollo-ios/issues/34#issuecomment-266862014))?

**Comment by jzhw0130** [comment] 2017-05-18 05:49
@martijnwalraven 

Sure

Only says :   
++ exec apollo-codegen

No arguments

Jing

**Comment by martijnwalraven** [comment] 2017-05-18 06:03
@jzhw0130: I still don't know what causes that for some people, but now that I think of it, we may have a workaround in recent versions of `apollo-codegen`.

Could you try replacing the last line of the build script with:

```
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate '**/*.graphql' --schema schema.json --output API.swift
```

**Comment by jzhw0130** [comment] 2017-05-18 06:33
@martijnwalraven 

Hi 
Also get the same result.

Script as :
APOLLO_FRAMEWORK_PATH=$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1)

if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
exit 1
fi

cd ${SRCROOT}/Tests/StarWarsAPI
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate '**/*.graphql' --schema schema.json --output API.swift

Jing

**Comment by martijnwalraven** [comment] 2017-05-18 06:37
@jzhw0130: Why does it say `cd ${SRCROOT}/Tests/StarWarsAPI`? That doesn't seem right, because you probably don't want to generate files for the test queries. You probably want to replace this with `cd "${SRCROOT}/${TARGET_NAME}"`.

**Comment by jzhw0130** [comment] 2017-05-18 06:41
@martijnwalraven 

Yes   I just do a test with the test queries.  If it does work, I will do my query. 
But now, demo does not work.

**Comment by jzhw0130** [comment] 2017-05-18 06:43
@martijnwalraven 
<img width="762" alt="719d0d18-4f71-49cf-b4d9-d42aa84c9573" src="https://cloud.githubusercontent.com/assets/12521790/26189657/4b8b3fd8-3bd8-11e7-9def-b76d44be23e9.png">

**Comment by martijnwalraven** [comment] 2017-05-18 06:53
@jzhw0130: I have no idea how to debug this, because I can't reproduce it and I've only heard it happen with you and @attheodo so far. Is there anything about your setup that might explain this? OS X version, the shell you use, how you installed Node?

**Comment by jzhw0130** [comment] 2017-05-18 07:28
@martijnwalraven 
Thanks for your patience.

OS: mac os 10.11.6  
Node: v7.10.0
shell: bash
apollo-codegen --version: 0.10.13
npm -v : 4.2.0

Just download the frontage demo from : https://github.com/apollographql/frontpage-ios-app

Then nothing change,  just build to get the API.swift.

Jing

**Comment by jzhw0130** [comment] 2017-05-18 07:46
@martijnwalraven  

As @attheodo  said, I have to do the process of 'apollo-codegen' on the Terminal as follows:
apollo-codegen generate *.graphql *.graphql --schema schema.json --output API.swift

Although it is a little trouble, but it works.

Jing

**Comment by martijnwalraven** [comment] 2017-05-18 07:51
@jzhw0130: I'd really like to understand what is going on. But I just tried it again, cloning a fresh copy of `frontage-ios-app` and reinstalling `apollo-codegen` 0.10.3 from npm, and everything seems to work for me.

For some reason, the arguments passed to `$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh` are not passed on to `apollo-codegen` in certain environments. We execute it with `exec apollo-codegen "$@"`, which seems pretty standard, so I don't know why that doesn't work in your case.

**Comment by jzhw0130** [comment] 2017-05-18 08:29
Sorry 

I'm not familiar with shell script, can not get the problem...

**Comment by jzhw0130** [comment] 2017-05-18 09:51
@martijnwalraven 

One more detail:

check-and-run-apollo-codegen.sh change  as:
# Print commands before executing them (useful for troubleshooting)
set -x

echo $0
echo $1
echo $@
echo $*

Result:

Showing All Messages

Showing All Messages
++ echo /Users/jing/Library/Developer/Xcode/DerivedData/FrontPage-bmlzfqrnzbhvyqacptgxyziypyqq/Build/Products/Debug-iphonesimulator/Apollo.framework/check-and-run-apollo-codegen.sh


/Users/jing/Library/Developer/Xcode/DerivedData/FrontPage-bmlzfqrnzbhvyqacptgxyziypyqq/Build/Products/Debug-iphonesimulator/Apollo.framework/check-and-run-apollo-codegen.sh


++ echo


++ echo


++ echo




Only get the first parameter...

**Comment by martijnwalraven** [comment] 2017-05-18 12:48
@jzhw0130: Hmmm, so the parameters aren't even passed to `check-and-run-apollo-codegen.sh`.

Could you try echoing `$APOLLO_FRAMEWORK_PATH` from the build script phase?

**Comment by jzhw0130** [comment] 2017-05-18 13:51
@martijnwalraven 
Input:
echo $0
echo $1
echo $@
echo $*
echo $APOLLO_FRAMEWORK_PATH


Output:

Showing All Messages
++ echo /Users/jing/Library/Developer/Xcode/DerivedData/FrontPage-bmlzfqrnzbhvyqacptgxyziypyqq/Build/Products/Debug-iphonesimulator/Apollo.framework/check-and-run-apollo-codegen.sh


/Users/jing/Library/Developer/Xcode/DerivedData/FrontPage-bmlzfqrnzbhvyqacptgxyziypyqq/Build/Products/Debug-iphonesimulator/Apollo.framework/check-and-run-apollo-codegen.sh


++ echo


++ echo


++ echo


++ echo

**Comment by martijnwalraven** [comment] 2017-05-18 14:00
@jzhw0130: I meant putting `echo $APOLLO_FRAMEWORK_PATH` in the build script phase in Xcode, not `check-and-run-apollo-codegen.sh`.

**Comment by jzhw0130** [comment] 2017-05-18 14:46
@martijnwalraven 
Sorry

cd ${SRCROOT}/${TARGET_NAME}
echo $APOLLO_FRAMEWORK_PATH
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate $(find . -name '*.graphql') --schema schema.json --output API.swift



Showing All Messages
/Users/jing/Library/Developer/Xcode/DerivedData/FrontPage-bmlzfqrnzbhvyqacptgxyziypyqq/Build/Products/Debug-iphonesimulator/Apollo.framework


++ echo /Users/jing/Library/Developer/Xcode/DerivedData/FrontPage-bmlzfqrnzbhvyqacptgxyziypyqq/Build/Products/Debug-iphonesimulator/Apollo.framework/check-and-run-apollo-codegen.sh


/Users/jing/Library/Developer/Xcode/DerivedData/FrontPage-bmlzfqrnzbhvyqacptgxyziypyqq/Build/Products/Debug-iphonesimulator/Apollo.framework/check-and-run-apollo-codegen.sh


++ echo


++ echo


++ echo

**Comment by pavelshadrin** [comment] 2017-05-22 14:02
Getting the same issue: 
++ exec apollo-codegen

No API.swift generated.

**Comment by dylanmoo** [comment] 2017-08-16 22:17
I'm getting a similar issue. I've installed apollo-codegen using `npm install -g apollo-codegen` and it seems to install correctly.

But when I try to build my project (with the correct build run script), I get `error: Can't find apollo-codegen command; make sure to run 'npm install -g apollo-codegen' first.` 

I'm running:
Xcode 8.3.3
node v8.4.0
npm 5.3.0

Have you found the solution to this?

**Comment by shelldonhu** [comment] 2018-03-23 09:42
It can be built successfully when I firstly create an empty .graphql file on ${SRCROOT}/${TARGET_NAME}.

**Comment by NiltiakSivad** [comment] 2018-04-12 20:36
I experienced multiple errors while attempting to get the auto-generation working. Including the following:
1. An already open current issue involving whitespace #33 
  - Removing all whitespace in names from my targets, schemas, and build configurations, re-running pod install, and cleaning, resolved this.
2. Afterwards, I received an error saying that `Apollo.framework` does not support the latest version of `apollo-codegen`.
  - I had to downgrade the version installed on my machine to 0.18.8. 
3. Finally afterwards, I got the error which brought me to this thread: 
```
TypeError: Cannot read property 'length' of undefined
    at Object.yargs.command.command.command.argv [as handler] (/usr/local/lib/node_modules/apollo-codegen/src/cli.js:186:17)
    at Object.runCommand (/usr/local/lib/node_modules/apollo- codegen/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/apollo-codegen/lib/cli.js:197:5)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
Command /bin/sh failed with exit code 1
```
@shelldonhu's  suggested fix of adding a `.graphql` file fixed it for me. The documentation is out of order and asks you to verify that `API.swift` is generated before adding a .graphql file.

Hope this helps someone.

**Comment by yanshiyason** [comment] 2018-06-10 23:21
with the following versions 
```
 - Apollo (0.8.0):
    - Apollo/Core (= 0.8.0)
  - Apollo/Core (0.8.0)
```

I had to change

```
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh ...

to:

$APOLLO_FRAMEWORK_PATH/Resources/check-and-run-apollo-codegen.sh ...
```

**Comment by i-Roma** [comment] 2018-06-16 08:48
@NiltiakSivad, thank you! I spent lot of time to find the issue! And finally, I came across with @NiltiakSivad answer. Apollo team should warn their users about such possible case in installation tutorial!

**Comment by Edwardharpham** [comment] 2018-06-29 15:34
Still stuck on this. Can you please provide a little more explanation on how to fix this? 

Is it best to create a blank .graphql file in a text editor then move this into the project directory in Finder?

Which folder does ${SRCROOT}/${TARGET_NAME}. relate to?

Thanks

**Comment by i-Roma** [comment] 2018-07-03 12:03
@Edwardharpham, With the blank .graphql file you probably will get error like "Syntax Error: Unexpected <EOF>"

Just create an empty file in your left navigation panel in Xcode with .graphql extension, and add in the file query or mutation that contains your schema.json. 

Also, [you can check my answer](https://stackoverflow.com/questions/51153455/apollo-ios-command-bin-sh-failed-with-exit-code-1-command-phasescriptexecuti/51153928#51153928) where I describe how to avoid this problem. Of course with words of gratitude to @NiltiakSivad :)

**Comment by tormic** [comment] 2018-07-05 11:28
@i-Roma , I am also still stuck on this, how did you add in the file query in the graphql file? Could you maybe provide som screenshots of how you did this?

Thanks:)

**Comment by intoxicated** [comment] 2018-07-15 12:37
Ok, I was not alone to struggle with this issue. I'm not sure who is in charge to maintain apollo documentation but it seems like the installation order is not properly align. Can anyone have a full steps to fix this issue?

**Comment by MrMatten** [comment] 2018-07-17 20:43
I don't know if it is relevant, but I had to change the button line of my script to 
`$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate *.graphql --schema schema.json --output API.swift`
That made everything run for me.

**Comment by Cybernization** [comment] 2018-07-19 19:53
`$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-cli.sh codegen:generate --queries=\"$(find . -name '*.graphql')\" --schema=schema.json API.swift`

**Comment by designatednerd** [comment] 2019-07-15 10:25
I've recently updated the setup instructions for the build phase setup [here](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step) - I'm going to close this out since that should solve a fair number of these issues. Please open a new issue if you're still encountering problems. Thank you!

**Closed by designatednerd** 2019-07-15 10:25 UTC
Labels: codegen
