### ISSUE TITLE
Missing API reference link?

### ISSUE THREAD

**Issue by Jarred-Sumner** [apollographql/apollo-ios#604] opened 2019-07-01 23:56 UTC
Is there a link to the API reference anywhere? The link to "API reference" from https://www.apollographql.com/docs/ios points to http://cocoadocs.org/docsets/Apollo/0.7.0/ which doesn't show the list of classes:
![image](https://user-images.githubusercontent.com/709451/60473382-b1a8e300-9c21-11e9-8634-b0f5e8acd613.png)

![out](https://user-images.githubusercontent.com/709451/60473346-8a521600-9c21-11e9-9929-0c8e16a046dc.gif)

**Comment by designatednerd** [comment] 2019-07-02 07:13
Unfortunately this is a dupe of #171. CocoaPods deprecated CocoaDocs ages ago, so I'm going to be looking for a way to regenerate the docs in something more sustainable. I'm leaving this one open too as a reminder to get on this sooner rather than later.

**Comment by designatednerd** [comment] 2019-07-11 11:18
I've at least managed to update the API reference file to no longer send people to a dead link in #618. I'll open a new issue to get those docs regenerating in a useful fashion.

**Comment by designatednerd** [comment] 2019-07-11 11:23
I'm going to close this one out and track through #622. Thanks for reporting!

**Closed by designatednerd** 2019-07-11 11:23 UTC
Labels: docs
