### ISSUE TITLE
Pruning generated files for .relative(subpath:) operations deletes only

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/apollo-ios#2969] opened 2023-04-20 05:05 UTC
### Summary

When generating code with `operations: .relative(subpath: "somepath")`, and with `pruneGeneratedFiles` not set (assuming defaulting to true), the after 1 generate run it only deletes the operations. Then after a second run it regenerates them.

If you repeat this process it should repeat the pattern, i.e. delete only -> regenerate -> delete only -> regenerate -> etc.

### Version

1.0.7

### Steps to reproduce the behavior

Create a codegen project with `operations: .relative(subpath: "somepath")`, and with `pruneGeneratedFiles` not set, then repeatedly execute codegen. You should see the operations be deleted and regenerated on each subsequent execution.

**Comment by AnthonyMDev** [comment] 2023-04-20 18:06
Ooooh! Thanks for this @jimisaacs! We definitely will look into it.

**Comment by calvincestari** [comment] 2023-04-20 22:56
Huh! We've struggled to be able to replicate this behaviour in the past - thank you for narrowing it down to a particular configuration setting @jimisaacs!

**Comment by BobaFetters** [comment] 2023-05-02 19:10
@jimisaacs I am investigating the issue currently, and wondering if you could provide a little more info about your setup. Are any of the paths in your file structure Symlinks to another path? Possibly the "subpath" given in the `operations: .relative(subpath: "somepath")` or maybe some higher in the directory structure?

**Comment by jimisaacs** [comment] 2023-05-03 12:59
@BobaFetters no symlinks, just a subpath that ends up in the Sources of multiple swift packages.

**Comment by BobaFetters** [comment] 2023-05-03 13:51
@jimisaacs Would you be able to provide a small sample setup that replicates what you have in your project with the subpath and a swift package that uses that in its Sources to be able to test against? This would help in verifying the cause of the issue and ensuring the fix covers all use cases.

**Comment by jimisaacs** [comment] 2023-05-03 16:50
@BobaFetters here you go! If you do this...
```sh
cd ReducedCase/librares/Codegen
swift run
```
Or...
```sh
open ReducedCase/ReducedCase/ReducedCase.xcworkspace`
```
then run `GraphQLCodegenExe` from within Xcode.

Both should alternate removing and creating generating files upon repeated execution.
[apollo-ReducedCase.zip](https://github.com/apollographql/apollo-ios/files/11385000/apollo-ReducedCase.zip)

**Comment by BobaFetters** [comment] 2023-05-03 17:07
@jimisaacs Thanks so much for providing that! I believe I have a fix for the issue, few more tests to run to verify for sure, but this is super helpful.

**Comment by BobaFetters** [comment] 2023-05-04 17:34
The fix for this has been merged into main and will go out in our next release

**Closed** 2023-05-04 17:33 UTC
Labels: bug, planned-next
