### ISSUE TITLE
RootEntityType of some inline fragments has a wrong type

### ISSUE THREAD

**Issue by martin-muller** [apollographql/apollo-ios#2949] opened 2023-04-11 13:19 UTC
### Summary

I've tried migrating from 1.0.7 to 1.1.1, but stumbled upon an issue with generated models

Some inline fragments generated using `ApolloCodegen` 1.1.1 point to a type that doesn't exist in that context resulting in a `'...' is not a member type of struct 'GQLClient.SomeQuery.Data....'` compile-time error.

### Version

1.1.1

### Steps to reproduce the behavior

The issue does not exhibit with all models, so far it seems like its only inline union types:

```graphql
query Article($id: ID!) {
  article(where: { id: $id }) {
    article {
      ... on SomeArticle {
        id
        title
      }
    }
  }
}
```
(made up query that's not far off the one we're having issue with, happy to provide the concrete query in private channels)

Maybe worth mentioning that some root fields share the same name as our query types, maybe that's confusing the code gen?

Providing the full path to the type fixes the issue, eg. replacing `public typealias RootEntityType = Article.Article` with `public typealias RootEntityType = ArticleQuery.Data.Article`.

### Anything else?

In one query we have the same issue with a type in `__mergedSources`.

**Comment by calvincestari** [comment] 2023-04-11 17:19
Thanks for reporting this @martin-muller, we'll take a look into it asap.

cc. @AnthonyMDev

**Comment by AnthonyMDev** [comment] 2023-04-11 18:17
We can probably just fully qualify these names, but I'd really like a reproduction case so our unit tests can ensure this doesn't regress.

I haven't been able to come up with a reproduction quickly with the examples I have. @martin-muller could you send me your codegen configuration file so I can try to replicate this? If you don't want to post it here, sending it to me at Anthony@apollographql.com would be great!

**Comment by tahirmt** [comment] 2023-04-12 05:35
I have a similar issue where some inline fragments will have a type like this `public typealias RootEntityType = Query.ExpectedType` or `public typealias RootEntityType = Mutation.ExpectedType`


So far I haven't been able to create an isolated schema and queries to to be able to send over.

**Comment by martin-muller** [comment] 2023-04-12 10:38
Thanks for taking a look @AnthonyMDev, I've sent you an email with our config and query.

**Comment by AnthonyMDev** [comment] 2023-04-14 21:40
This fix for this is merged into main! A new patch version will likely go out early next week.

**Closed** 2023-04-14 21:39 UTC
Labels: bug, codegen

**Comment by tahirmt** [comment] 2023-04-15 17:38
@AnthonyMDev I'm trying out the main branch now and the codegen still produces my issue as described above. The code does not compile because instead of having the operation name from the same file it just has `Query` in the `RootEntityType` generation. Where `Node` here represents an interface

```
public typealias RootEntityType = Query.Node // causes a build error here due to not being able to find the type
```

I was able to reproduce it in an isolated project with only one query and interface. Would you be able to take a look

[apollo-codegen-issue.zip](https://github.com/apollographql/apollo-ios/files/11240216/apollo-codegen-issue.zip)

**Comment by AnthonyMDev** [comment] 2023-04-17 17:18
Thank you so so much for the reproduction case! Will look into this ASAP.

**Comment by ay8s** [comment] 2023-04-17 17:51
@AnthonyMDev Fix is working well for us. Thanks 👍

**Comment by tahirmt** [comment] 2023-04-17 17:51
Thank you! I suspect it's due to the `RootQueryType` in our schema and it is related to #2955

**Comment by AnthonyMDev** [comment] 2023-05-25 20:49
Looking into this one now. Sorry I missed this. 

Think I should have a fix for it shortly.

**Comment by AnthonyMDev** [comment] 2023-05-30 23:31
@martin-muller PR #3045 should fix the issue you're having here as well. Should be merged into `main` soon and included in our next patch release.
