### ISSUE TITLE
GraphQLNullable<Decimal> conversion

### ISSUE THREAD

**Issue by satyaaiosdev** [apollographql/apollo-ios#3305] opened 2023-12-20 15:00 UTC
### Question

The conversion of **Decimal** to **GraphQLNullable<Decimal>** resulted in odd behavior, such as the addition of extra numbers to the value as shown below.
Take GraphQLNullable, for instance.A portion (0.84) receives 0.83999999999999997 
However, after conversion, 0.84 was our need.How can one resolve this kind of problem?

**Comment by AnthonyMDev** [comment] 2023-12-20 22:00
Can you provide a code sample of what you are doing when this conversion occurs? That is definitely very odd behavior...

**Comment by satyaaiosdev** [comment] 2023-12-21 07:01
let decimal: Decimal = 0.84
let unwrapDecimal = GraphQLNullable.some(0.84)
this is getting 0.83999999999999997 and this value send to backend

**Comment by satyaaiosdev** [comment] 2024-01-01 21:50
@AnthonyMDev waiting for your response, **FloatingType** values are wrong precision after using .some(0.84).

**Comment by satyaaiosdev** [comment] 2024-01-01 21:56
> [!IMPORTANT]
@AnthonyMDev waiting for your response, **FloatingType** values are wrong precision after using .some(0.84).

**Comment by AnthonyMDev** [comment] 2024-01-02 18:09
Hi there. Sorry for the slow response, we've been off for the holidays. Now that we are back, we've got a lot of catch up to do this week. But we'll get someone to look into this further as soon as we can. If you end up finding anything else out in the mean time, please update us here!

**Comment by satyaaiosdev** [comment] 2024-01-02 18:44
Hi @AnthonyMDev , not only GraphQLNullable<Decimal>, while sending **Decimal(decimal: 0.83)**  is converted into **8.0299999999999994**

**Comment by BobaFetters** [comment] 2024-01-03 06:12
@satyaaiosdev Can you provide a sample project that demonstrates this issue? In my testing using `Decimal` and passing it into `GraphQLNullable` as described doesn't demonstrate the issue so I assume the issue is coming from somewhere this variable is being used or acted upon in some way in your code. A sample project that demonstrates the issue would be helpful for us to determine the cause of the issue.

**Comment by satyaaiosdev** [comment] 2024-01-05 03:23
MocupInput(__data: ApolloAPI.InputDict(data: [ "currentBalance": GraphQL.Decimal(decimal:0.83)]))

Than while sending this input request query creating like this
requestBody -----
 {
  "operationName" : "MocupAggtegate",
  "query" : "query ShoppingCartAggregate($input: MocupAggregateInput!) {\n  mocupAggregate(input: $input) {\n    __typename\n    totalValue\n }\n}",
  "variables" : {
    "input" : {
      "totalValue" : 8.0299999999999994,
    }
  }

**Comment by BobaFetters** [comment] 2024-01-16 18:28
@satyaaiosdev sorry for the delayed response ive been out of office dealing with a death in the family.

so you are using `GraphQL.Decimal` which I assume is a custom scalar you have implemented? Can you share your implementation of that?

**Comment by BobaFetters** [comment] 2024-01-30 22:47
Closing this under the assumption it is no longer an issue. Feel free to reopen with additional info if needed.

**Closed by BobaFetters** 2024-01-30 22:47 UTC
Labels: bug, question, awaiting response

**Comment by satyaaiosdev** [comment] 2025-03-25 19:43
We have sending GraphQL.Decimal(decimal: 6.99) but backend sending 6.990000000000002, why add more precision of Decimal number need to rounded two decimals, can you help me out this. 

CustomScalors > Decimals automatically genarated SPM side as below

import ApolloAPI
import struct Foundation.Locale
import struct Foundation.Decimal
import struct Foundation.NSInteger
import class Foundation.NSNumber
import class Foundation.NumberFormatter

/// Fixed precision (up to 2 decimal places) numeric value.
public struct Decimal: CustomScalarType, Hashable {
	public let decimal: Foundation.Decimal

	public init(decimal: Foundation.Decimal) {
		self.decimal = decimal
	}

	public init(intValue: Foundation.NSInteger) {
		self.decimal = Foundation.Decimal(intValue)
	}

	public init (_jsonValue value: JSONValue) throws {
		if
			let valueString = value as? String,
			let parseResult = Foundation.Decimal(string: valueString),
			!parseResult.isNaN
		{
			self.decimal = parseResult
		} else if
			let valueDouble = value as? Double,
			let parseResult = valueDouble.truncatedDecimal,
			!parseResult.isNaN
		{
			self.decimal = parseResult
		} else {
			throw JSONDecodingError.couldNotConvert(value: value, to: Decimal.self)
		}
	}

	public var _jsonValue: JSONValue {
		decimal
	}
}

private let truncationFormatter = {
	let formatter = Foundation.NumberFormatter()
	formatter.maximumFractionDigits = 2
	formatter.roundingMode = .up
	formatter.locale = Locale(identifier: "en_US")
	return formatter
} ()

public extension Double {
	var truncatedDecimal: Foundation.Decimal? {
		guard !self.isNaN else {
			return nil
		}

		return truncationFormatter.string(from: self as NSNumber).flatMap { Foundation.Decimal(string: $0) }
	}
}

**Comment by satyaaiosdev** [comment] 2025-03-25 19:43
We have sending GraphQL.Decimal(decimal: 6.99) but backend sending 6.990000000000002, why add more precision of Decimal number need to rounded two decimals, can you help me out this. 

CustomScalors > Decimals automatically genarated SPM side as below

import ApolloAPI
import struct Foundation.Locale
import struct Foundation.Decimal
import struct Foundation.NSInteger
import class Foundation.NSNumber
import class Foundation.NumberFormatter

/// Fixed precision (up to 2 decimal places) numeric value.
public struct Decimal: CustomScalarType, Hashable {
	public let decimal: Foundation.Decimal

	public init(decimal: Foundation.Decimal) {
		self.decimal = decimal
	}

	public init(intValue: Foundation.NSInteger) {
		self.decimal = Foundation.Decimal(intValue)
	}

	public init (_jsonValue value: JSONValue) throws {
		if
			let valueString = value as? String,
			let parseResult = Foundation.Decimal(string: valueString),
			!parseResult.isNaN
		{
			self.decimal = parseResult
		} else if
			let valueDouble = value as? Double,
			let parseResult = valueDouble.truncatedDecimal,
			!parseResult.isNaN
		{
			self.decimal = parseResult
		} else {
			throw JSONDecodingError.couldNotConvert(value: value, to: Decimal.self)
		}
	}

	public var _jsonValue: JSONValue {
		decimal
	}
}

private let truncationFormatter = {
	let formatter = Foundation.NumberFormatter()
	formatter.maximumFractionDigits = 2
	formatter.roundingMode = .up
	formatter.locale = Locale(identifier: "en_US")
	return formatter
} ()

public extension Double {
	var truncatedDecimal: Foundation.Decimal? {
		guard !self.isNaN else {
			return nil
		}

		return truncationFormatter.string(from: self as NSNumber).flatMap { Foundation.Decimal(string: $0) }
	}
}

**Comment by AnthonyMDev** [comment] 2025-03-25 20:36
Hi @satyaaiosdev. That custom scalar implementation looks correct to me. If your server is sending you a value with too many digits of precision that's not something the client can control.

Is this code not working for you? I'm not sure what question you have exactly.
