### ISSUE TITLE
iOS Cache Serialisation to use custom scalar types

### ISSUE THREAD

**Issue by qalvapps** [apollographql/apollo-ios#329] opened 2018-07-27 15:59 UTC
We use custom scalar type's in our schema which Apollo uses successfully to parse the network response, but it seems when apollo persists this data using the SqlNormalizedCache, the data is stored 'as is' and doesn't use the custom scalar types for serialisation. Apollo reading from cache then ultimately fails.
Any way to get serialisation to use custom scalar types ?

This is similar to issue with Android, which had issue raised last week which subsequently received a PR :
issue: https://github.com/apollographql/apollo-android/issues/1001
PR: https://github.com/apollographql/apollo-android/pull/1010

**Comment by liamjdouglas** [comment] 2018-07-31 10:18
Here maybe? https://github.com/apollographql/apollo-ios/issues/262

**Comment by qalvapps** [comment] 2018-07-31 11:58
thanks Liam, thats not quite the issue. I have custom scalars working when parsing network response as is described in your linked issue. The issue is that Apollo doesn't use custom scalars when serialising persisted data from SqlNormalizedCache

**Comment by qalvapps** [comment] 2018-09-26 15:12
wonder if theres an answer for this ongoing issue yet ?

**Comment by mkv27** [comment] 2018-11-16 21:12
Temporally,
1- You can create a custom store https://github.com/apollographql/apollo-ios/issues/328
2- Then create custom **SQLiteNormalizedCache** based class and review:
https://github.com/apollographql/apollo-ios/blob/4f35f046925d6d89ea0faba39e2e0cd028828033/Sources/ApolloSQLite/SQLiteNormalizedCache.swift#L141

**Comment by niraj1991** [comment] 2019-06-12 06:44
Hello @qalvapps and @liamjdouglas 

I have same issue in version 0.10.1. 

When I am using custom scalar types at that time Watcher is not calling while update the Cache. Do you have any solution?

Thanks

**Comment by designatednerd** [comment] 2019-07-15 09:46
There's definitely some gooberyness going on with this, I'll have to do some excavating to figure out what's going on.

**Comment by ppowers10** [comment] 2019-08-20 12:46
I have been having the same issue as @qalvapps.  His statement: `I have custom scalars working when parsing network response as is described in your linked issue. The issue is that Apollo doesn't use custom scalars when serializing persisted data from SqlNormalizedCache` seems to be the same thing I'm facing.  

A couple things to note:
- We are using ` --passthroughCustomScalars`
- When we fetch the graphql query, it parses properly against our local custom scalar type definition to ensure it is JSONDecodable.
- We are using `SqlNormalizedCache` and we see the ApolloClient.swift fail to fetch from cache at the `client.store.load(query: query) { (result, error) in ... }`.  The error is returning as `GraphQLResultError Apollo.JSONDecodingError.missingValue` against my custom scalar type.

**Comment by designatednerd** [comment] 2019-08-21 08:37
OK thank you very much for the detailed info - I'll see what I can do about this when I get back from moving.

**Comment by ppowers10** [comment] 2019-08-23 20:29
@designatednerd I think we found the underlying issue.  Some of our Queries variables contain `.`.  One of the value is the version of the app which the graphql server wants to know.  In doing this, the `shouldComputeCachePath` check will fetch the variables and create a string for the cacheKey.  The issue is that you have other logic in the framework which will strip the `.` at certain points due to your SQLite record management.  So in the end, adding `.replacingOccurrences(of: ".", with: "-")` fixed the issue.  The section of code in `GraphQLExecutor` now looks like this:

`if shouldComputeCachePath {
      let cacheKey = try firstField.cacheKey(with: info.variables).replacingOccurrences(of: ".", with: "-")
      info.cacheKeyForField = cacheKey
      info.cachePath.append(cacheKey)
    }`

**Comment by designatednerd** [comment] 2019-08-23 20:32
Oof, yeah, that would definitely break the hell out of trying to parse key paths. Thanks for the info!

**Comment by designatednerd** [comment] 2020-04-28 20:46
This issue should be fixed by #1144, which shipped with `0.26.0`. If you're still having issues around this after upgrading, please open a new issue with which version you're using and we'll hunt it down from there. Thank you!

**Closed by designatednerd** 2020-04-28 20:46 UTC
Labels: caching
