### ISSUE TITLE
Codegen skips Objects with similar names

### ISSUE THREAD

**Issue by krin-san** [apollographql/apollo-ios#3248] opened 2023-10-02 11:37 UTC
### Summary

When GraphQL scheme include 2 types with similar camel-cased name `Livestream` and `LiveStream`, Apollo Codegen generates source only for one of those objects (`LiveStream`) in the file named for the other object (`Livestream.graphql.swift`).

### Version

1.5.2

### Steps to reproduce the behavior

Demo project: https://github.com/krin-san/ApolloCodegenObjectsConflict

### Logs

```shell
[DEBUG - ApolloCodegenLib:Glob.swift:211] - Evaluating {REDACTED}/ApolloCodegenObjectsConflict/Sources/ApolloCodegenObjectsConflict/schema.sdl
[DEBUG - ApolloCodegenLib:Glob.swift:225] - Matched {REDACTED}/ApolloCodegenObjectsConflict/Sources/ApolloCodegenObjectsConflict/schema.sdl
[DEBUG - ApolloCodegenLib:Glob.swift:127] - Expanding globstar input/**/*.graphql
[DEBUG - ApolloCodegenLib:Glob.swift:197] - Expanded to {REDACTED}/ApolloCodegenObjectsConflict/Sources/ApolloCodegenObjectsConflict/input/*.graphql
[DEBUG - ApolloCodegenLib:Glob.swift:211] - Evaluating {REDACTED}/ApolloCodegenObjectsConflict/Sources/ApolloCodegenObjectsConflict/input/*.graphql
[DEBUG - ApolloCodegenLib:Glob.swift:225] - Matched {REDACTED}/ApolloCodegenObjectsConflict/Sources/ApolloCodegenObjectsConflict/input/Example.graphql
[DEBUG - ApolloCodegenLib:Glob.swift:127] - Expanding globstar output/**/*.graphql.swift
[DEBUG - ApolloCodegenLib:Glob.swift:197] - Expanded to {REDACTED}/ApolloCodegenObjectsConflict/Sources/ApolloCodegenObjectsConflict/output/*.graphql.swift
[DEBUG - ApolloCodegenLib:Glob.swift:211] - Evaluating {REDACTED}/ApolloCodegenObjectsConflict/Sources/ApolloCodegenObjectsConflict/output/*.graphql.swift
```

**Comment by krin-san** [comment] 2023-10-02 11:39
Is there a short-term workaround available in the current Apollo 1.5.2 release? !2798 would definitely help here, but maybe `additionalInflectionRules` can be used for that too?

**Comment by calvincestari** [comment] 2023-10-02 17:51
Hi @krin-san, thanks for the feedback.

Unfortunately there is no current feature that reliably let's you rename a schema object. We'll consider bumping up the priority of #2798 for a near future release. I'm not sure if your idea of using `additionalInflectionRules` would work because I think we only use that for field name/types and not the schema objects.

**Comment by calvincestari** [comment] 2023-10-02 17:53
I'm going to close this issue as a duplicate of #2798 and you can track the progress in that issue instead.

**Closed by calvincestari** 2023-10-02 17:53 UTC
Labels: bug, needs investigation

**Comment by krin-san** [comment] 2023-10-04 09:22
@calvincestari as I said, https://github.com/apollographql/apollo-ios/issues/2798 could be used as a workaround for this bug, but is it actually a solution?

For this schema from example project:
```sdl
type Livestream {
  id: ID!
}

type LiveStream {
  id: ID!
}

type Query {
  oldLiveStream(id: ID!): Livestream
  newLiveStream(id: ID!): LiveStream
}
```
I would expect Codegen to generate 2 files, one for both types:
1. `Schema/Objects/LiveStream.graphql.swift`
```swift
// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

extension GraphQLAPI.Objects {
  static let LiveStream = Object(
    typename: "LiveStream",
    implementedInterfaces: []
  )
}
```
2. `Schema/Objects/Livestream.graphql.swift`
```swift
// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

extension GraphQLAPI.Objects {
  static let Livestream = Object(
    typename: "Livestream",
    implementedInterfaces: []
  )
}
```

**Comment by krin-san** [comment] 2023-10-04 09:39
`ObjectFileGenerator` uses `GraphQLNamedType.name` as a filename. If `Livestream` and `LiveStream` types have the same `name` value and have been generated into the same `Livestream.graphql.swift` file, then how come the `typename` inside this file match the `formattedName`?

https://github.com/apollographql/apollo-ios/blob/42802f5cbcab4705c73d9d83fbc2bcfab022bc17/Sources/ApolloCodegenLib/FileGenerators/ObjectFileGenerator.swift#L15
https://github.com/apollographql/apollo-ios/blob/42802f5cbcab4705c73d9d83fbc2bcfab022bc17/Sources/ApolloCodegenLib/Templates/ObjectTemplate.swift#L16-L17
https://github.com/apollographql/apollo-ios/blob/42802f5cbcab4705c73d9d83fbc2bcfab022bc17/Sources/ApolloCodegenLib/Frontend/GraphQLSchema.swift#L156-L165
https://github.com/apollographql/apollo-ios/blob/42802f5cbcab4705c73d9d83fbc2bcfab022bc17/Sources/ApolloCodegenLib/Frontend/GraphQLSchema.swift#L32-L33

**Comment by calvincestari** [comment] 2023-10-04 15:25
> @calvincestari as I said, https://github.com/apollographql/apollo-ios/issues/2798 could be used as a workaround for this bug, but is it actually a solution?

It's debatable whether this is a bug or simply something the 1.x codegen engine cannot generate code for. #2798 mentions scalars specifically but I think the solution would be to offer a way to rename any type within a schema, but that's TBD until we design the solution.
