### ISSUE TITLE
Crashed: ApolloStore.swift line 109 - load

### ISSUE THREAD

**Issue by jync** [apollographql/apollo-ios#159] opened 2017-10-11 01:03 UTC
Hey guys...

We're getting a crash with the following stack trace:

```
#9. Crashed: NSOperationQueue 0x174236960 :: NSOperation 0x1702d42e0 (QOS: USER_INTERACTIVE)
0  libswiftCore.dylib             0x101fb7aa8 swift_getTupleTypeMetadata + 288
1  libswiftCore.dylib             0x101fb7a7c swift_getTupleTypeMetadata + 244
2  libswiftCore.dylib             0x101fb7df8 swift_getTupleTypeMetadata2 + 28
3  MyApp                       0x100b0089c ApolloStore.load<A where ...> (query : A) -> Promise<GraphQLResult<A.Data>> (ApolloStore.swift:109)
4  MyApp                       0x100affcac ApolloStore.load<A where ...> (query : A, resultHandler : (GraphQLResult<A.Data>?, Error?) -> ()) -> () (ApolloStore.swift:115)
5  MyApp                       0x100af4e2c FetchQueryOperation.start() -> () (ApolloClient.swift:205)
6  MyApp                       0x100af5584 @objc FetchQueryOperation.start() -> () (ApolloClient.swift)
7  Foundation                     0x1835fcbf0 __NSOQSchedule_f + 228
8  libdispatch.dylib              0x1819e29a0 _dispatch_client_callout + 16
9  libdispatch.dylib              0x1819f0ad4 _dispatch_queue_serial_drain + 928
10 libdispatch.dylib              0x1819e62cc _dispatch_queue_invoke + 884
11 libdispatch.dylib              0x1819f2a50 _dispatch_root_queue_drain + 540
12 libdispatch.dylib              0x1819f27d0 _dispatch_worker_thread3 + 124
13 libsystem_pthread.dylib        0x181beb100 _pthread_wqthread + 1096
14 libsystem_pthread.dylib        0x181beacac start_wqthread + 4
```

We're using the SQLLite cache implementation as well. Running on Apollo 0.6.4. Is this something that might be fixed in later versions?

**Comment by martijnwalraven** [comment] 2017-10-11 01:15
This seems like a duplicate of https://github.com/apollographql/apollo-ios/issues/140?

**Comment by designatednerd** [comment] 2019-06-25 13:11
Closing this as a dupe of #140, please follow changes there as I try to figure out what's going on here.

**Closed by designatednerd** 2019-06-25 13:11 UTC
Labels: crash, duplicate
