### ISSUE TITLE
XCode 12 : Could not find module ‘Apollo’ for target ‘arm64-apple-ios-simulator’; found: x86_64-apple-ios-simulator, x86_64

### ISSUE THREAD

**Issue by poorvasingh04** [apollographql/apollo-ios#1485] opened 2020-10-30 09:49 UTC
## Bug report

XCode 12 : Could not find module ‘Apollo’ for target ‘arm64-apple-ios-simulator’; found: x86_64-apple-ios-simulator, x86_64
Unable to build app against iOS simulator using XCode 12.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.27.1 and 0.36.0
- Xcode version: 12
- Swift version: 5

## Steps to reproduce
Build code against iOS simulator. I am using app to build against iOS simulator for UI tests.

## Further details

Code fails to compile. I also added following post install script in podfile:

post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
end

**Comment by poorvasingh04** [comment] 2020-10-31 21:33
@designatednerd yes. To compile with Xcode 12 against iOS simulator, we need to exclude arm64 architecture in app and all the linked pods. This is same issue as described here: https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios

**Comment by designatednerd** [comment] 2020-11-01 22:36
Interesting - there's a related suggestion in there about making sure that `ONLY_ACTIVE_ARCH` is set to yes for your debug setup. In a sample CocoaPods app I've got where that's set up I have not seen this issue.

I *think* as long as you're not building on a developer transition kit, setting that up should help with this, since it seems like Xcode is trying to build the universe, then complaining that the thing you specifically told it not to build isn't there.

**Comment by poorvasingh04** [comment] 2020-11-02 08:36
ONLY_ACTIVE_ARCH is already set to Yes

**Comment by designatednerd** [comment] 2020-11-02 19:00
🤔 That's...very odd if you're not on a developer transition kit. Are you on a developer transition kit?

**Comment by poorvasingh04** [comment] 2020-11-02 19:23
@designatednerd no. I am not in a developer transition kit. I am trying to build app against simulator for my UI tests but it fails with Xcode 12.1

**Comment by designatednerd** [comment] 2020-11-02 20:08
Here's a couple other things I can think of that are unlikely but worth checking: 

- If there's more than one target in your project, are all targets in your project set for `ONLY_ACTIVE_ARCH`, or just the main application?
- Is your scheme set to run the tests in release mode rather than debug mode? 
- Is there something about XCUI tests that's trying to build the app for release even though your tests are set in debug?

If none of those turn up the problem, do you mind either emailing me your project or a sample project that reproduces this issue? ellen at apollographql dot com.

**Comment by designatednerd** [comment] 2020-11-10 23:31
Were you ever able to figure this out?

**Comment by poorvasingh04** [comment] 2020-11-13 16:20
@designatednerd yes, my solution also worked. So, if some of the pods in the app still support arm64, you need to exclude it in podfile and build active architecture only for your main target. But I upgraded the libraries including Apollo and now it works for us. Thanks for your support!

**Comment by designatednerd** [comment] 2020-11-13 20:36
Great - mind if we close this one out?

**Comment by poorvasingh04** [comment] 2020-11-20 09:48
@designatednerd yes, we can close this now. Thanks you!

**Closed** 2020-11-20 19:09 UTC
Labels: build-issue, dependency-management
