### ISSUE TITLE
Code generation throwing an error in 1.2.1 only

### ISSUE THREAD

**Issue by tahirmt** [apollographql/apollo-ios#3071] opened 2023-06-13 17:21 UTC
### Summary

I'm getting this error during generation of mocks. in only 1.2.1. This works well in 1.2.0.

```
Range requires lowerBound <= upperBound
```

This is what the log looks like when it happens. For reference I'm calling `try ApolloCodegen.build(with: config)` from a swift tools package myself by importing `ApolloCodegenLib`.

```
.
.
.
[DEBUG - ApolloCodegenLib:Glob.swift:225] - Matched /<file-path>/Mocks/<type-name>+Mock.graphql.swift
[DEBUG - ApolloCodegenLib:Glob.swift:225] - Matched /<file-path>/Mocks/<type-name>+Mock.graphql.swift
[DEBUG - ApolloCodegenLib:Glob.swift:225] - Matched /<file-path>/Mocks/<type-name>+Mock.graphql.swift
Swift/arm64e-apple-macos.swiftinterface:15840: Fatal error: Range requires lowerBound <= upperBound
```

### Version

1.2.1

### Steps to reproduce the behavior

I'm still working on isolating a project where I can reproduce it.

### Logs

```shell
.
.
.
[DEBUG - ApolloCodegenLib:Glob.swift:225] - Matched /<file-path>/Mocks/<type-name>+Mock.graphql.swift
[DEBUG - ApolloCodegenLib:Glob.swift:225] - Matched /<file-path>/Mocks/<type-name>+Mock.graphql.swift
[DEBUG - ApolloCodegenLib:Glob.swift:225] - Matched /<file-path>/Mocks/<type-name>+Mock.graphql.swift
Swift/arm64e-apple-macos.swiftinterface:15840: Fatal error: Range requires lowerBound <= upperBound
```

### Anything else?

The generated mock from 1.2.0 looks like this

```swift
import Apollo
import ModuleName

public class TypeName: MockObject {
  public static let objectType: Object = ModuleName.Objects.TypeName
  public static let _mockFields = MockFields()
  public typealias MockValueCollectionType = Array<Mock<TypeName>>

  public struct MockFields {
  }
}

// The original Object 

public extension Objects {
  static let TypeName = Object(
    typename: "TypeName",
    implementedInterfaces: [Interfaces.InterfaceName.self]
  )
}
```

Another thing to add is that this type does not add anything on top of the fields from the interface itself. All the fields that are part of this type are from the interface.

**Comment by AnthonyMDev** [comment] 2023-06-13 19:31
Thanks for the bug! I'm trying to look into this. Would definitely be really helpful to have a reproduction case that I can debug. Let me know if you come up with anything to reproduce this. I'll keep looking as well.

**Comment by tahirmt** [comment] 2023-06-13 20:00
I'm definitely looking into that. Will add more details as I can figure it out. I ran it from the command line so don't have a stack trace but I'll see if I can get it.

**Comment by AnthonyMDev** [comment] 2023-06-13 20:01
Okay, gotcha. Yeah to get a stack track you'd need to run it in Xcode for sure.

**Comment by AnthonyMDev** [comment] 2023-06-13 20:08
@dafurman is also experiencing a similar issue, though it's in generation of operations, not mocks. 

I think I have some idea of what's going on in the code to cause this, but I can't reason through what sort of query shape would surface this. My assumption was that it would be impossible to get this range error (given a valid query definition).

I'll keep thinking on this, but I think I'm going to need a repro to get much farther. 

If either of you are willing to privately send me your projects so I can run it locally and debug, that would also work.

**Comment by AnthonyMDev** [comment] 2023-06-13 20:45
Haha, I definitely understand that. No worries. Thanks so much for working on reproducing this!

**Comment by tahirmt** [comment] 2023-06-14 03:56
@AnthonyMDev I managed to create a schema with the error reproducible. When you open the `Package.swift` file you can run the `codegen` scheme to have it call `ApolloCodegenLib` and that will produce the error. And yes, it wasn't related to mocks at all. I just assumed it ws related because of the logs.

[apollo-codegen-issue-1.2.1.zip](https://github.com/apollographql/apollo-ios/files/11741471/apollo-codegen-issue-1.2.1.zip)

**Comment by AnthonyMDev** [comment] 2023-06-14 19:52
I say this probably once a day, but today I'm saying it to you!

@tahirmt, you are my hero (for today)! 🤟

I'll check this out and work to get a fix up ASAP. Assuming this bug doesn't explode into some really difficult to fix issue, my current plan is to get this and one other bug fixed and release a patch by EOW (6/16)

**Comment by tahirmt** [comment] 2023-06-14 20:22
Happy to help!

**Comment by AnthonyMDev** [comment] 2023-06-14 21:48
The cause of this bug has been identified and fix has been implemented! Writing some unit tests to ensure this does not regress in the future and then I'll have a PR up! Thanks so much @tahirmt!

**Closed** 2023-06-14 23:47 UTC
Labels: bug, needs investigation

**Comment by AnthonyMDev** [comment] 2023-06-14 23:50
PR is in `main` and this is complete! The plan is to push the patch release `1.2.2` tomorrow which will include this fix!

**Comment by tahirmt** [comment] 2023-06-14 23:51
Thanks @AnthonyMDev for the quick fix!

**Comment by AnthonyMDev** [comment] 2023-06-14 23:52
Couldn't have done it without you providing me the reproduction case! You rock @tahirmt!
