### ISSUE TITLE
Proper way to run CLI on CI/CD environment

### ISSUE THREAD

**Issue by ddanielczyk** [apollographql/apollo-ios#2781] opened 2023-01-16 15:44 UTC
### Question

Question: We don't want to commit the generated graphql files but just generate them every time server builds the app. For this we need the apollo-cli, but how to get it from command line ? With Cocoapods, it was already included once pod installed, but I don't see it with SPM. On local machines, we click the Install CLI in xCode - what would be the equivalent to do this from command line ? Maybe I'm missing something, but it seems to be pretty complicated for what it seems to be a very popular use case? (Or are you suggesting, we should keep the generated files on git)

**Comment by calvincestari** [comment] 2023-01-17 06:23
Hi @ddanielczyk - 👋🏻 

> We don't want to commit the generated graphql files but just generate them every time server builds the app.

> Or are you suggesting, we should keep the generated files on git

It doesn't matter how you choose to treat the generated files with regards to source control, you should make a decision that is best for your team and your workflow.

> For this we need the apollo-cli, but how to get it from command line ? With Cocoapods, it was already included once pod installed, but I don't see it with SPM. On local machines, we click the Install CLI in xCode - what would be the equivalent to do this from command line ?

You can use the Swift Package Plugin from the command line. See the documentation - [SPM with Package.swift](https://www.apollographql.com/docs/ios/code-generation/codegen-cli#installation).

**Comment by calvincestari** [comment] 2023-01-17 06:33
If you're not using a Package.swift file though and you want to be able to update Xcode dependencies but from the command line then you could try one of the following:
* Download the CLI from the latest release, which should be at the link https://github.com/apollographql/apollo-ios/releases/latest/download/apollo-ios-cli.tar.gz. This would require you to be using the latest version though, but the CLI will warn you about any version mismatch.
* The CLI can be built manually with the command `make build-cli` but you'll need to find the path to the source, wherever Xcode has put it, and execute the make command there.

**Comment by ddanielczyk** [comment] 2023-01-17 09:04
Yeah, we are not using Package.swift.

> Download the CLI from the latest release, which should be at the link https://github.com/apollographql/apollo-ios/releases/latest/download/apollo-ios-cli.tar.gz. This would require you to be using the latest version though, but the CLI will warn you about any version mismatch.
As you said, while it's easy solution, we would have to manage updating this CLI manually, which is not the best option.

> The CLI can be built manually with the command make build-cli but you'll need to find the path to the source, wherever Xcode has put it, and execute the make command there.
I think I will try and go with this solution. Thank you!


On note side: I still do think it's a bit more complicated than it should tough - compared to cocoapods solution.

**Comment by calvincestari** [comment] 2023-01-17 17:59
> As you said, while it's easy solution, we would have to manage updating this CLI manually, which is not the best option.

I'm confused by what you'd need to update manually? The CLI is attached to each release. You would need a script that runs on CI that downloads the CLI archive, unarchives it and then calls the `generate` command? You shouldn't need to manually update anything, other than your dependency in Xcode which you have to do even if the CLI didn't exist.

> On note side: I still do think it's a bit more complicated than it should tough - compared to cocoapods solution.

If you have any ideas on how to improve this, we're always open to suggestions. The problem is Xcode's internal implementation/use of SPM is not public and there is no Xcode command-line tool to get at those dependencies.

**Comment by calvincestari** [comment] 2023-01-17 18:00
I'm going to close this issue as there is nothing actionable at the moment.

**Closed by calvincestari** 2023-01-17 18:00 UTC
Labels: question
