### ISSUE TITLE
Xcode 16 fails to build with latest Apollo

### ISSUE THREAD

**Issue by alexdmotoc** [apollographql/apollo-ios#3444] opened 2024-09-20 17:02 UTC
### Summary

I just upgraded to Xcode 16 and my app is not building anymore. I even updated the Apollo pod to latest version and still fails.

Podfile.lock
```
- Apollo (1.5.2):
    - Apollo/Core (= 1.5.2)
  - Apollo/ApolloTestSupport (1.5.2):
    - Apollo/Core
  - Apollo/Core (1.5.2)
  - Apollo/SQLite (1.5.2):
    - Apollo/Core
    - SQLite.swift (~> 0.13.1)
```

![Screenshot 2024-09-20 at 19 43 38](https://github.com/user-attachments/assets/1ac334d4-3019-4615-990f-54c37b63c5e2)

### Version

1.5.2

### Steps to reproduce the behavior

- update to Xcode 16
- build

**Comment by calvincestari** [comment] 2024-09-20 17:16
This looks like a duplicate of https://github.com/apollographql/apollo-ios-dev/pull/386.

@alexdmotoc, this was fixed in [1.13.0](https://github.com/apollographql/apollo-ios/releases/tag/1.13.0). You need to update to that version at least; 1.5.2 is not the [latest](https://github.com/apollographql/apollo-ios/releases/).

**Closed by calvincestari** 2024-09-20 17:16 UTC
Labels: bug, needs investigation
