### ISSUE TITLE
Error building latest version with carthage

### ISSUE THREAD

**Issue by yasirmturk** [apollographql/apollo-ios#2699] opened 2022-12-05 14:27 UTC
## Bug report

Unable to compile the libraries from `0.41.0` until `1.0.5` with carthage... last working version is `0.40.0` different versions produce different errors. Tried with xcode 13.4.1 and xcode 14.1

## Versions

- `apollo-ios` SDK version: 1.0.5
- Xcode version: 13.4.1 & 14.1
- Swift version: 
- Package manager: carthage

## Steps to reproduce

- Create a new xcode project
- Create a new Cartfile
- Add `github "apollographql/apollo-ios" == 1.0.5`
- Run `carthage update --use-xcframeworks --platform ios `

## Further details

tail /var/folders/46/y4wtvbms0r11xpb9k593g1s00000gp/T/carthage-xcodebuild.WP8A1f.log

```
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'GraphQLAPI' from project 'CustomTargetProject')
    cd /Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget
    export DEVELOPER_DIR\=/Applications/Xcode13.app/Contents/Developer
    export SDKROOT\=/Applications/Xcode13.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk
    /Applications/Xcode13.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name GraphQLAPI -O -whole-module-optimization -enforce-exclusivity\=checked @/Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/IntermediateBuildFilesPath/CustomTargetProject.build/Release-iphoneos/GraphQLAPI.build/Objects-normal/arm64/GraphQLAPI.SwiftFileList -sdk /Applications/Xcode13.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -target arm64-apple-ios16.0 -g -module-cache-path /Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/ModuleCache.noindex -Xfrontend -serialize-debugging-options -embed-bitcode -swift-version 5 -I /Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/BuildProductsPath/Release-iphoneos -F /Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/BuildProductsPath/Release-iphoneos/PackageFrameworks -F /Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/BuildProductsPath/Release-iphoneos -emit-localized-strings -emit-localized-strings-path /Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/IntermediateBuildFilesPath/CustomTargetProject.build/Release-iphoneos/GraphQLAPI.build/Objects-normal/arm64 -c -num-threads 10 -output-file-map /Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/IntermediateBuildFilesPath/CustomTargetProject.build/Release-iphoneos/GraphQLAPI.build/Objects-normal/arm64/GraphQLAPI-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/IntermediateBuildFilesPath/CustomTargetProject.build/Release-iphoneos/GraphQLAPI.build/Objects-normal/arm64/GraphQLAPI.swiftmodule -Xcc -I/Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/IntermediateBuildFilesPath/CustomTargetProject.build/Release-iphoneos/GraphQLAPI.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/IntermediateBuildFilesPath/CustomTargetProject.build/Release-iphoneos/GraphQLAPI.build/GraphQLAPI-generated-files.hmap -Xcc -I/Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/IntermediateBuildFilesPath/CustomTargetProject.build/Release-iphoneos/GraphQLAPI.build/GraphQLAPI-own-target-headers.hmap -Xcc -I/Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/IntermediateBuildFilesPath/CustomTargetProject.build/Release-iphoneos/GraphQLAPI.build/GraphQLAPI-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/IntermediateBuildFilesPath/CustomTargetProject.build/Release-iphoneos/GraphQLAPI.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/IntermediateBuildFilesPath/CustomTargetProject.build/Release-iphoneos/GraphQLAPI.build/GraphQLAPI-project-headers.hmap -Xcc -I/Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/BuildProductsPath/Release-iphoneos/include -Xcc -I/Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/IntermediateBuildFilesPath/CustomTargetProject.build/Release-iphoneos/GraphQLAPI.build/DerivedSources-normal/arm64 -Xcc -I/Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/IntermediateBuildFilesPath/CustomTargetProject.build/Release-iphoneos/GraphQLAPI.build/DerivedSources/arm64 -Xcc -I/Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/IntermediateBuildFilesPath/CustomTargetProject.build/Release-iphoneos/GraphQLAPI.build/DerivedSources -emit-objc-header -emit-objc-header-path /Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/IntermediateBuildFilesPath/CustomTargetProject.build/Release-iphoneos/GraphQLAPI.build/Objects-normal/arm64/GraphQLAPI-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/yturk/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.5/Build/Intermediates.noindex/ArchiveIntermediates/CustomTargetProject/IntermediateBuildFilesPath/CustomTargetProject.build/Release-iphoneos/GraphQLAPI.build/unextended-module-overlay.yaml -working-directory /Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget
error: Build input files cannot be found: '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Objects/Rat.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Fragments/HeightInMeters.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Operations/Queries/DogQuery.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Interfaces/Pet.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Objects/Height.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Operations/Queries/AllAnimalsQuery.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/SchemaMetadata.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/InputObjects/PetAdoptionInput.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Objects/Human.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Operations/Queries/ClassroomPetsCCNQuery.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/InputObjects/PetSearchFilters.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Operations/Queries/AllAnimalsCCNQuery.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Objects/Mutation.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Operations/Mutations/PetAdoptionMutation.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Objects/Dog.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Fragments/DogFragment.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/LocalCacheMutations/PetDetailsMutation.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Enums/RelativeSize.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Operations/Queries/AllAnimalsIncludeSkipQuery.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Objects/Fish.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Objects/Bird.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/LocalCacheMutations/AllAnimalsLocalCacheMutation.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Interfaces/WarmBlooded.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Objects/PetRock.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Fragments/ClassroomPetDetails.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Interfaces/Animal.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Objects/Crocodile.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Fragments/ClassroomPetDetailsCCN.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Fragments/PetDetails.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/InputObjects/MeasurementsInput.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Operations/Queries/ClassroomPetsQuery.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Objects/Cat.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Enums/SkinCovering.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Unions/ClassroomPet.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Operations/Queries/PetSearchQuery.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Fragments/WarmBloodedDetails.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Interfaces/HousePet.swift', '/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/GraphQLAPI/Schema/Objects/Query.swift' (in target 'GraphQLAPI' from project 'CustomTargetProject')

/Users/yturk/Learning/MyApp/Carthage/Checkouts/apollo-ios/Tests/TestCodeGenConfigurations/Other-CustomTarget/CustomTargetProject.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 16.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'CustomTargetProject' from project 'CustomTargetProject')
** ARCHIVE FAILED **


The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'GraphQLAPI' from project 'CustomTargetProject')
(1 failure)```

**Comment by calvincestari** [comment] 2022-12-05 18:51
Hi @yasirmturk 👋🏻 
* the last of the `0.x` versions ([`0.53.0`](https://github.com/apollographql/apollo-ios/releases/tag/0.53.0)) should be able to build successfully with Carthage.
* `1.x` versions are not compatible with Carthage build tooling. You will instead need to manually build the xcframework and add it to your project. Here an issue with more context into this decision - https://github.com/apollographql/apollo-ios/issues/2555.

I'm going to close this issue as it's not a bug; 1.x versions are not compatible with Carthage build tooling.

**Closed by calvincestari** 2022-12-05 18:51 UTC
