### ISSUE TITLE
Can operationDefinition, operationName, and queryDocument be static?

### ISSUE THREAD

**Issue by danl3v** [apollographql/apollo-ios#2039] opened 2021-11-20 22:32 UTC
## Feature request

I am writing a tool to autogenerate documentation on our GraphQL operations. I would like to be able to access operationDefinition, operationName, and queryDocument. Since these are just strings, I believe that I should be able to access them without creating an instance. Can we convert these properties to be static?

## Motivation

This will enable me to get access to these values without needing an instance of a query. I don't see anything about these variables that seem tied to an instance. This will help me autogenerate documentation around my operations.

## Proposed solution

Make operationDefinition, operationName, and queryDocument static.

## Outstanding Questions

None.

Thanks!

**Comment by AnthonyMDev** [comment] 2021-11-22 19:04
I will look into this. I seem to remember there being a reason why these aren't static, but I don't remember what it was. We are rebuilding codegen right now, so if this is doable, I'll do it!

**Comment by danl3v** [comment] 2021-12-02 16:21
Thank you!!!

**Comment by calvincestari** [comment] 2022-05-23 22:17
Closing as a duplicate of #1645

**Closed by calvincestari** 2022-05-23 22:17 UTC
Labels: codegen
