### ISSUE TITLE
Union-Based Queries Fetch Unnecessary Types

### ISSUE THREAD

**Issue by davefoxy** [apollographql/apollo-ios#2292] opened 2022-06-01 15:55 UTC
## Bug report

I have a schema with a `union` in it like so:

`union Activity = A B C`

However, in my application, I am not interested in type `C`, so I do not specify it in my query, which looks like the following:

```
query MyActivities() {
    myActivities() {
        edges {
            node {
                ... on A {
                    id
                }
                ... on B {
                    id
                }
            }
        }
    }
}
```

However, I notice that the request the Apollo client generates also asks for type `C`, even though I have not requested it. Apollo appears to generate the request based off the union options and not the query I write perhaps?

I'm wondering if this is a bug or expected behaviour. If it's expected, is there any way I can remove unneeded variables from the request myself, perhaps by using an interceptor?

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.51.0
- Xcode version: 13.3
- Swift version: 5
- Package manager: SPM

## Steps to reproduce

Please replace this line with steps to reproduce the problem.

## Further details

Please replace this line with any further details or context necessary to understand the problem. Delete this section if you don't have anything further to add.

**Comment by calvincestari** [comment] 2022-06-01 18:51
Hi @davefoxy 👋🏻 - the generated code is correct because even though your application may not be interested in `node` of type `C` the response data may still include `node` of type `C`, your app will need to filter them out. If you want to reduce the types that can be returned you'll need an argument to specify the desired types or a narrower query that only returns specific types.

I'm going to close this issue because it's not a bug. We can continue the conversation here if you have other questions though.

**Closed as completed by calvincestari** 2022-06-01 18:51 UTC
