### ISSUE TITLE
JSON Serialisation

### ISSUE THREAD

**Issue by netrager** [apollographql/apollo-ios#3260] opened 2023-10-19 08:34 UTC
### Question

I'm using apollo ios client 1.6.0 and I'm missing the .jsonObject property from my generated response data. (see this link: https://www.apollographql.com/docs/ios/v0-legacy/fetching-queries/#json-serialization)

Is there an other possibility to generate a json object out of fetch data? And later create a query data object again from this json data?

**Comment by BobaFetters** [comment] 2023-10-19 14:41
@netrager The `.jsonObject` property that was available in 0.x versions is no longer available in 1.x, I think what you are asking for may be something like [this](https://github.com/apollographql/apollo-ios/issues/3094#issuecomment-1609963273)?

**Comment by AnthonyMDev** [comment] 2023-11-10 18:29
Closing as duplicate of #3196.

**Closed by AnthonyMDev** 2023-11-10 18:29 UTC
Labels: question
