### ISSUE TITLE
Apollo's normalized cache won't return objects from cache

### ISSUE THREAD

**Issue by bpollock-vida** [apollographql/apollo-ios#421] opened 2018-12-10 17:11 UTC
If I make a query on Apollo Client with policy networkOnly and then make that same query with policy cacheOnly the result only shows cached for the query but not the normalized objects it contains. Even though I provide a cache key closure.

Example Response:
 [
 { urn: "value" },
 { urn: "value2" }
]

Procedure:
1. cacheKeyForObject called on array - returns nil, from observation it must fall back onto path-based caching
2. cacheKeyForObject called on first object - returns "value" 
3. cacheKeyForObject called on second object - returns "value2" 

Config:
Xcode 10.1, Swift 4.2, iOS 12.1
Apollo 0.9.0

Simplified Client Config:
```
func getClient() -> ApolloClient {
  // config
  let configuration = URLSessionConfiguration.default
  configuration.httpAdditionalHeaders = [
     headerKeys.accept : "application/json",
     headerKeys.contentType : "application/json",
     headerKeys.userAgent : userAgentString]       
  configuration.httpAdditionalHeaders?[headerKeys.authorization] = token

  // create client
  let client = ApolloClient(networkTransport: HTTPNetworkTransport(url: url, configuration: configuration))

  client.cacheKeyForObject = { $0["urn"] }
  return client
}
```

Query Code:
```
func testCache() {
        let groupQuery = GetTagsQuery(urn: nil,
                                      group: "<redacted>",
                                      name: nil,
                                      size: nil,
                                      start: nil)
        let client = graphQLService.client()
        client?.fetch(query: groupQuery, cachePolicy: .fetchIgnoringCacheData, resultHandler: { (result, error) in
            let groupResult = self.mapToTags(result?.data)
            print("Network Result: \(groupResult)")
            // Network Result: ["<urn_a>", "<urn_b>"]

            client?.fetch(query: groupQuery, cachePolicy: .returnCacheDataDontFetch, resultHandler: { (result, error) in
                let groupCacheResult = self.mapToTags(result?.data)
                print("Group Cache Result: \(groupCacheResult)")
                // Group Cache Result: ["<urn_a>", "<urn_b>"]


                let objectQuery = GetTagsQuery(urn: ["<urn_a>"],
                                               group: nil,
                                               name: nil,
                                               size: nil,
                                               start: nil)
                client?.fetch(query: objectQuery, cachePolicy: .returnCacheDataDontFetch, resultHandler: { (result, error) in
                    let objectCacheResult = self.mapToTags(result?.data)
                    print("Object Cache Result: \(objectCacheResult)")
                    // Object Cache Result: []
                })
            })
        })
```

**Comment by bpollock-vida** [comment] 2018-12-17 23:46
Investigating normalized cache now. FYI for everyone that you will have to reuse the same apolloclient instance to get caching

**Comment by martijnwalraven** [comment] 2019-01-25 07:05
If I understand your issue correctly, that behavior is as expected.

Even though the result of `groupQuery` is cached in the normalized cache, `objectQuery` is a different query and can't be resolved without going through the server. The underlying objects are cached, but there is no way for a GraphQL client to know what objects `GetTagsQuery` will return because that depends on its arguments.

One way of looking at that is that fields (including root fields) are functions, and we can't make any assumptions about what those functions will return for different arguments. We can't even assume a field like `Query.product(id: $id)` returns a product object with `id` `$id`, because theoretically the server-side resolver for that field could do whatever it wants.

We've talked about allowing you to define client-side resolvers for fields that could emulate what the corresponding server-side resolvers would do. But we don't have that feature right now.

That doesn't mean the normalized cache is useless because its primary value lies in consistence: if the second query returns different values for objects that are also part of the result of `groupQuery`, we'll recompute that result from cache and notify watchers.

**Comment by bpollock-vida** [comment] 2019-01-29 15:33
Hey @martijnwalraven thanks for the great explanation. 

I guess I became confused because of how the cache is documented in Apollo's ["GraphQL Concepts Visualized"](https://blog.apollographql.com/the-concepts-of-graphql-bc68bd819be3
) under "Use object identifiers when the path assumption isn’t enough"

There it looked like your second query with the identifier would correctly resolve the cache, but I guess it is just saying that the second query would just update the shared cache object?

**Comment by designatednerd** [comment] 2019-07-15 12:51
@bpollock-vida Yep, that's basically what it's saying. I'm going to close this out as expected behavior. Please feel free to ask any follow up questions in our [Spectrum Chat](https://spectrum.chat/apollo/apollo-ios?tab=posts). Thank you!

**Closed by designatednerd** 2019-07-15 12:51 UTC
Labels: caching
