### ISSUE TITLE
Swift Package Manager dependency resolving with Error: Authentication failed because no credentials were provided.

### ISSUE THREAD

**Issue by veeamd** [apollographql/apollo-ios#1527] opened 2020-11-18 04:20 UTC
## Bug report

I add apollo-ios as a dependency for my Swift package, but it always give me the error when resolving dependencies:
* Error while fetching remote repository: https://github.com/daltoniam/Starscream
    * Authentication failed because no credentials were provided.

Could someone help me figure out if this is actually a bug? Thanks a lot.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 0.36
- Xcode version: 12.2
- Swift version: 5.3
- Package manager: Swift 5.3

## Steps to reproduce

1. Add apollo-ios to dependencies array of my swift package, like so:

```
dependencies: [
    .package(name: "Apollo", url: "git@github.com:apollographql/apollo-ios.git", .upToNextMinor(from: "0.36.0"))]
```

This also reproduces when I open Package.swift in apollo-ios repo.

## Further details

I'm using SSH to authenticate with github. I can clone https://github.com/daltoniam/Starscream separately with git command line without any issue.

**Comment by designatednerd** [comment] 2020-11-18 18:49
Ugh, I've seen this issue transiently but haven't been able to reproduce it consistently - it doesn't make any sense because all of the packages we use are public. It seems like it's an SPM bug. 

Do you mind trying to remove and re-add Apollo? In the past that's helped for some folks.

**Comment by veeamd** [comment] 2020-11-18 22:56
@designatednerd That didn't work out for me. I also removed all the cache or derived data before add back in.

**Comment by veeamd** [comment] 2020-11-18 23:15
Yeah. At this point, I think it might be a bug in SPM

**Comment by designatednerd** [comment] 2020-11-19 00:39
Mayyyybe you could try adding Starscream seperately before adding Apollo? 

It also could be a matter of just coming back to it tomorrow - I'm still not super clear on where this particular gremlin lives in SPM.

**Comment by veeamd** [comment] 2020-11-19 18:18
@designatednerd Thanks your reply.
I think it's a bug in Xcode, as mentioned by circleci: https://support.circleci.com/hc/en-us/articles/360044709573-Swift-Package-Manager-fails-to-clone-from-private-Git-repositories

**Comment by designatednerd** [comment] 2020-11-19 19:50
Blergh. Yeah wish I had a better fix for you. Since this is an 🍎 issue rather than an apollo one, do you mind if we close this out?

**Comment by designatednerd** [comment] 2020-11-23 22:23
Since I haven't heard back over the weekend and this is a known Apple issue, I'm going to close this out. I wish I had a better suggestion than "hit it with a hammer a bunch of times" but unfortunately I don't have a great one.

**Closed by designatednerd** 2020-11-23 22:23 UTC
Labels: dependency-management
