### ISSUE TITLE
Documentation for @import directive. 

### ISSUE THREAD

**Issue by scottasoutherland** [apollographql/apollo-ios#3373] opened 2024-04-29 21:35 UTC
### Use case

I'm looking to understand how to use the @import directive added here: https://github.com/apollographql/apollo-ios-dev/pull/245

But it's unclear to me. 

What i'm hoping to do is have a one graphQL library import another and re-use the fragments there, but I cannot find any documentation on this or how to use it. We currently are copying files and including multiple copies of the same fragments, and building 3 separate graphql libraries which is unideal. I assume the codegen would need to know about all 3 libraries which are are currently built separately ?

**Comment by scottasoutherland** [comment] 2024-04-29 21:44
Making matters difficult is when i try to test this out, i run into this crash

```
GraphQLCompiler/JavaScriptBridge.swift:271: Precondition failed: Expected JavaScript object but found: undefined
```

**Comment by calvincestari** [comment] 2024-04-30 00:29
Hi @scottasoutherland - I agree with should get some specific documentation up for this, I thought we had some already. We'll likely need a new place in the documentation where we can describe custom directives.

That directive is quite easy to use though:
* Add the directive to an operation or fragment, e.g: `query ExampleOperation @import(module: "ModuleName") { .. }`
* `ModuleName` needs to be the name of a defined target/module that is accessible to the code where the operation will be generated.

Note that this is not intended to be a way to link schemas though, so any target/module you want to import into the operation file must have been part of the code generation execution that generated the operation in question.

**Comment by calvincestari** [comment] 2024-04-30 00:30
> Making matters difficult is when i try to test this out, i run into this crash
> 
> ```
> GraphQLCompiler/JavaScriptBridge.swift:271: Precondition failed: Expected JavaScript object but found: undefined
> ```

If you remove `@import` does the error stop?

**Comment by scottasoutherland** [comment] 2024-04-30 15:38
> Note that this is not intended to be a way to link schemas though, so any target/module you want to import into the operation file must have been part of the code generation execution that generated the operation in question.

So in our case we have 1 schema, and we have 3 different libraries we build that each have their own queries against that schema. We use some fragments in all 3 of them but currently we just copy the files so we end up with LibraryOne.myFragment, LibraryTwo.myFragment, LibraryThree.myFragment which are all effectively the same type but not actually interchangeable. What we'd like to do is import LibraryOne into LibraryTwo & LibraryThree and use LibraryOne.MyFragment everywhere. 

If this is *not* what this is for, can you explain the use case for the directive ? In what case would you need to import a library that has nothing to do with the generated code ? 


> If you remove @import does the error stop and codegen succeeds?

After messing with it, the problem was not the imports, the problem was the missing fragments that i moved. It appears to be a volume of errors or something because if only one fragment is missing it flags that correctly but when i removed all of the re-used fragments it crashes instead.

**Comment by calvincestari** [comment] 2024-04-30 17:37
> So in our case we have 1 schema, and we have 3 different libraries we build that each have their own queries against that schema. We use some fragments in all 3 of them but currently we just copy the files so we end up with LibraryOne.myFragment, LibraryTwo.myFragment, LibraryThree.myFragment which are all effectively the same type but not actually interchangeable. What we'd like to do is import LibraryOne into LibraryTwo & LibraryThree and use LibraryOne.MyFragment everywhere.

Yes, this sounds like what it was intended for.

**Comment by calvincestari** [comment] 2024-04-30 17:55
Thanks @AnthonyMDev.

@scottasoutherland I'm going to close this issue now as there doesn't seem to be anything actionable. If you have further issues getting `@import` to work feel free to comment back here and we'll take a look - thanks.

**Closed by calvincestari** 2024-04-30 17:55 UTC
Labels: docs
