### ISSUE TITLE
cache data poisoning on combined keys

### ISSUE THREAD

**Issue by RolandasRazma** [apollographql/apollo-ios#273] opened 2018-05-16 14:23 UTC
cache will have incorrect data if combined `cacheKeyForObject` includes nil

floating recommendation to use `cacheKeyForObject = { [$0["__typename"], $0["id"]] }` as cache key is incorrect as if "id" is nil cache key will collide.

for example in this query `edges` have no id:
```
query WatchBug {
  allTrainers(first: 3, orderBy: FIRSTNAME, condition: {}) {
    edges {
      node {
        id
      }
    }
  }
}
```

I guess best would be to enforce that combined keys can't have nil or just force returned key to be string, so whoever constructs it would instantly realise problem of possible nil

version: head (and 0.8.0)

**Comment by martijnwalraven** [comment] 2018-05-16 15:59
Could you post the relevant parts of your schema and your query?

**Comment by RolandasRazma** [comment] 2018-05-16 18:39
not sure what is relevant, tested it on several queries, easy to reproduce

```son
query WatchBug {
  trainers: allTrainers(first: 3, orderBy: FIRSTNAME, condition: {}) {
    edges {
      node {
        id
      }
    }
  }
}
```

```swift
let watcher = watch(query: WatchBugQuery()) { (result) in
  print("watch", result?.trainers.edges?.compactMap({ $0.node.id }))
}

// In my case will output: 
//   watch [13, 17, 2]

fetch(query: WatchBugQuery()) { (result) in
  print("fetch", result?.trainers.edges?.compactMap({ $0.node.id }))
}

// In my case will output: 
//   fetch [13, 17, 2]
//   watch [2, 2, 2]
  
watcher.refetch()

// In my case will output: 
//   watch [13, 17, 2]
```

**Comment by RolandasRazma** [comment] 2018-05-16 20:29
more info:
if I remove  __typename from cacheKeyForObject it looks like it "working"

**Comment by RolandasRazma** [comment] 2018-05-16 20:38
ok figured out:
`cacheKeyForObject = { [$0["__typename"], $0["id"]] }` fails in my case as edge have no id and generated key collides.

**Comment by RolandasRazma** [comment] 2018-05-16 20:41
I guess its not exactly a bug, but recommendations in other issues are incorrect:

https://github.com/apollographql/apollo-ios/issues/213
https://github.com/apollographql/apollo-ios/issues/73

**Comment by designatednerd** [comment] 2019-07-11 16:54
What you're seeing is essentially expected behavior. While `CacheKeyForObject` does state that `If it returns `nil`, a default cache key based on the field path will be used`, it doesn't really have a great way of saying "If anything in this JSON object is nil, bail out", but as you've seen that can cause some issues. 

Unfortunately, I think forcing the returned key to be a `String` would probably break a significant number of existing implementations, since not everything uses strings as cache keys. 

I don't have a great suggestion for "don't create a cache key if something is null" at the moment beyond maybe looking at the keys in the `resultMap` for whatever type you want to create a key for to make sure something's not null. 

A lot of this *could* be solved by moving to `Codable` for codeGen - That'd at least get us some enums that people can use to access these keys.

In any case, this is a long-winded way of saying that I'm going to close this issue out - at the moment, this is behaving as designed.

**Closed by designatednerd** 2019-07-11 16:54 UTC
Labels: caching
