### ISSUE TITLE
Apollo 1.0 alpha.8 - Array of Input Objects Crash

### ISSUE THREAD

**Issue by jimisaacs** [apollographql/apollo-ios#2354] opened 2022-06-30 19:56 UTC
## Bug report

Currently I'm hitting this error:
<img width="1499" alt="Screen Shot 2022-06-30 at 3 37 04 PM" src="https://user-images.githubusercontent.com/299156/176764378-ef4e2ff8-ae28-436b-9886-969a3c5413f9.png">

Where it is failing to encode an array of input objects that were generated.
The following crash stack trace is the result of a mutation, where the mutation takes and array of inputs, i.e. `myMutation(inputs: [MyInput])`.

I'm not sure Inputs are JSONEncodable.

This seems to be in the middle of the stack:
<img width="803" alt="Screen Shot 2022-06-30 at 3 51 18 PM" src="https://user-images.githubusercontent.com/299156/176765425-e941439e-1b1d-43a4-a176-577ee60c5cbd.png">

Where we were using this to send our requests. The return of `requestBody` is of `JSONEncodableDictionary`, which then we attempt to encode, and there is an array of Input objects in there that fails to encode on the Array.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0 alpha.8
- Xcode version: 13.4.1
- Swift version: 5
- Package manager: SPM

## Steps to reproduce

Create a mutation, where it accepts and array of Inputs and see if it works end to end.

**Comment by calvincestari** [comment] 2022-06-30 20:28
Thanks @jimisaacs, you'll be pleased to know that this is a duplicate of https://github.com/apollographql/apollo-ios/issues/2342 and was fixed this morning. It is working in release/1.0 and will go out in the Beta release planned for tomorrow. 🎉

**Closed as completed by calvincestari** 2022-06-30 20:28 UTC
Labels: alpha-feedback

**Comment by jimisaacs** [comment] 2022-06-30 20:33
That's great! I'll give `release/1.0` a try

**Comment by jimisaacs** [comment] 2022-07-01 00:55
`release/1.0` is working! 🙇
