### ISSUE TITLE
iOS 1.0 installation (Carthage or xcodebuild archive) failures

### ISSUE THREAD

**Issue by irisha8787** [apollographql/apollo-ios#2555] opened 2022-10-07 21:32 UTC
## Bug report

Cannot generate XCFramework for apollo-ios 1.0.0 using either Carthage or building manually. 

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.0
- Xcode version: 13.4.1
- Swift version: N/A
- Package manager: Carthage or manually.

## Steps to reproduce

When using Carthage, the steps are:
```
carthage update --use-xcframeworks --platform ios
*** Fetching apollo-ios
*** Checking out apollo-ios at "1.0.0"
*** xcodebuild output can be found in /var/folders/18/y_v7x80j4v5dyfx8lxfzx1mr0000gq/T/carthage-xcodebuild.I6I81s.log
*** Building scheme "ApolloAPI" in Apollo.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/user/Documents/carthage-project/Carthage/Checkouts/apollo-ios/Apollo.xcodeproj -scheme ApolloAPI -configuration Release -derivedDataPath /Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/18/y_v7x80j4v5dyfx8lxfzx1mr0000gq/T/apollo-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/user/Documents/carthage-project/Carthage/Checkouts/apollo-ios)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/18/y_v7x80j4v5dyfx8lxfzx1mr0000gq/T/carthage-xcodebuild.I6I81s.log
user@R6TJ4Y9F9W carthage-project % open /var/folders/18/y_v7x80j4v5dyfx8lxfzx1mr0000gq/T/carthage-xcodebuild.I6I81s.log
```

Log file:
```
note: Using new build system
note: Using codesigning identity override: 
note: Planning
Analyze workspace

Create build description
Build description signature: 146c2f8adbbd7f0a6aae0cbffa5f47b2
Build description path: /Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ApolloAPI/IntermediateBuildFilesPath/XCBuildData/146c2f8adbbd7f0a6aae0cbffa5f47b2-desc.xcbuild

note: Build preparation complete
note: Building targets in dependency order
/Users/user/Documents/cartage-project/Carthage/Checkouts/apollo-ios/Configuration/Apollo/Apollo-Project-Release.xcconfig:1:1: error: unable to open file (in project "Apollo")
/Users/user/Documents/cartage-project/Carthage/Checkouts/apollo-ios/Configuration/Apollo/Apollo-Target-ApolloAPI.xcconfig:1:1: error: unable to open file (in target "ApolloAPI" in project "Apollo")
/Users/user/Documents/cartage-project/Carthage/Checkouts/apollo-ios/Configuration/Apollo/Apollo-Project-Release.xcconfig:1:1: error: unable to open file (in project "Apollo")
/Users/user/Documents/cartage-project/Carthage/Checkouts/apollo-ios/Configuration/Apollo/Apollo-Target-ApolloAPI.xcconfig:1:1: error: unable to open file (in target "ApolloAPI" in project "Apollo")
/Users/user/Documents/cartage-project/Carthage/Checkouts/apollo-ios/Configuration/Apollo/Apollo-Project-Release.xcconfig:1:1: error: unable to open file (in project "Apollo")
/Users/user/Documents/cartage-project/Carthage/Checkouts/apollo-ios/Configuration/Apollo/Apollo-Target-ApolloAPI.xcconfig:1:1: error: unable to open file (in target "ApolloAPI" in project "Apollo")
error: Multiple commands produce '/Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ApolloAPI/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/.framework'
    note: Target 'ApolloAPI' (project 'Apollo') has link command with output '/Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ApolloAPI/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/.framework'
    note: Target 'ApolloAPI' (project 'Apollo') has create directory command with output '/Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ApolloAPI/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/.framework'
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'ApolloAPI' from project 'Apollo')
error: Value for SWIFT_VERSION cannot be empty. (in target 'ApolloAPI' from project 'Apollo')
warning: duplicate output file '/Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ApolloAPI/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/.framework' on task: MkDir /Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/apollo-ios/1.0.0/Build/Intermediates.noindex/ArchiveIntermediates/ApolloAPI/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/.framework (in target 'ApolloAPI' from project 'Apollo')
** ARCHIVE FAILED **
```

When building manually:
```
xcodebuild archive \
		-configuration Release \
		-project "Apollo.xcodeproj" \
		-scheme "Apollo" \
		SKIP_INSTALL=NO \
		-archivePath "./build/Apollo.framework-iphoneos.xcarchive" \
		-destination generic/platform=iOS \
	    BUILD_LIBRARY_FOR_DISTRIBUTION=YES

/Users/user/Documents/apollo-ios/Sources/ApolloAPI/Selection+Conditions.swift:37:16: note: 'inverted' declared here
    public let inverted: Bool
               ^
/Users/user/Documents/apollo-ios/Sources/ApolloAPI/Selection+Conditions.swift:48:12: error: 'let' property 'variableName' may not be initialized directly; use "self.init(...)" or "self = ..." instead
      self.variableName = value
           ^
/Users/user/Documents/apollo-ios/Sources/ApolloAPI/Selection+Conditions.swift:36:16: note: 'variableName' declared here
    public let variableName: String
               ^
/Users/user/Documents/apollo-ios/Sources/ApolloAPI/Selection+Conditions.swift:49:12: error: 'let' property 'inverted' may not be initialized directly; use "self.init(...)" or "self = ..." instead
      self.inverted = false
           ^
/Users/user/Documents/apollo-ios/Sources/ApolloAPI/Selection+Conditions.swift:37:16: note: 'inverted' declared here
    public let inverted: Bool
               ^

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64 (in target 'ApolloAPI' from project 'Apollo')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ApolloAPI' from project 'Apollo')
(2 failures)
```

Thank you for your time!

**Comment by calvincestari** [comment] 2022-10-08 16:25
Hi @irisha8787, thanks for creating this issue. We're moving away from first-class support for Carthage so whether it works now, or continues to work isn't guaranteed. I tend to agree that manually building xcframeworks should continue to be supported. I have an idea of what is breaking the manual builds and will discuss with @AnthonyMDev next week.

**Comment by AnthonyMDev** [comment] 2022-10-14 19:59
As far as building manually, if we remove `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` from the `xccodebuild` command, it builds just fine.

`BUILD_LIBRARY_FOR_DISTRIBUTION=YES` enables library evolution, which is not a feature that `apollo-ios` supports. We don't currently have any plans to support library evolution in the future. I have not heard any compelling use-cases for supporting this that would warrant the additional restrictions on our future development that it requires.

As for Carthage, I'm not sure exactly what is going on there. As @calvincestari said, we aren't officially supporting Carthage anymore. If you can ensure your Carthage project is set up to have `BUILD_LIBRARY_FOR_DISTRIBUTION=NO`, it should build.

If there is another issue at that point, it likely has to do with our project not being set up with Carthage support in mind. Carthage expects your Xcode Project to be set up in a way that is ideal for being used as a package dependency. Our Xcode Project is set up to be ideal for our development workflow. 

Configuring a package is the job of the `Package.swift` and Podspec files with SPM and CocoaPods. Carthage doesn't provide a way for us to do so without restructuring our project in ways that is not conducive to our development workflow.

Apollo iOS is MIT Licensed open source software. You are always welcome to fork the repo and maintain an Xcode Project that has schemes that only build the frameworks you want with any build settings you prefer.

---

I'm going to close this as a "wont-fix".

@irisha8787 If turning `BUILD_LIBRARY_FOR_DISTRIBUTION` off still doesn't fix your issue and you can provide us with information indicating we have a problem with building the library manually that is not related specifically to Carthage, feel free to commend and we will happily re-open this issue to continue looking into that!

**Comment by irisha8787** [comment] 2022-10-17 17:47
Setting name: BUILD_LIBRARY_FOR_DISTRIBUTION
Ensures that your libraries are built for distribution. For Swift, this enables support for library evolution and generation of a module interface file.

It is required for generating xc framework. Otherwise I am getting 
```
No 'swiftinterface' files found within '/Users/user/Documents/apollo-ios/build/Apollo.framework-iphoneos.xcarchive/Products/@rpath/Apollo.framework/Modules/Apollo.swiftmodule'.
```

**Comment by AnthonyMDev** [comment] 2022-10-17 18:10
Where are you getting that error? On building the library, or on linking it to your project? Running this compiles successfully for me: 
```
xcodebuild archive \
		-configuration Release \
		-project "Apollo.xcodeproj" \
		-scheme "Apollo" \
		SKIP_INSTALL=NO \
		-archivePath "./build/Apollo.framework-iphoneos.xcarchive" \
		-destination generic/platform=iOS
```

**Comment by mmdumi** [comment] 2022-10-19 09:46
Hi @AnthonyMDev 
What @irisha8787 is point to is the following error that you can replicate by running the following commands.

A really basic way of compiling an xcframework for Apollo would be:
```
# Build Apollo target for iphonesimulator
xcodebuild archive -configuration Release -project "Apollo.xcodeproj" -scheme "Apollo" SKIP_INSTALL=NO \
  -sdk iphonesimulator -archivePath "./build/iphonesimulator.xcarchive"

# Build Apollo target for iphone device
xcodebuild archive -configuration Release -project "Apollo.xcodeproj" -scheme "Apollo" SKIP_INSTALL=NO \
  -sdk iphoneos -archivePath "./build/iphoneos.xcarchive"


# Combine frameworks into an xcframework
xcodebuild -create-xcframework -output Apollo.xcframework \
  -framework build/iphonesimulator.xcarchive/Products/@rpath/Apollo.framework \
  -framework build/iphoneos.xcarchive/Products/@rpath/Apollo.framework
```
The result of the `xcodebuild -create-xcframework ` command will be: `No 'swiftinterface' files found within`

In order for us to solve this issue we need to set `BUILD_LIBRARY_FOR_DISTRIBUTION` to YES, but adding this flag results in the following error:
```
note: Run script build phase 'Ensure no build settings are in the Xcode project' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Apollo' from project 'Apollo')
```

**Comment by mmdumi** [comment] 2022-10-19 10:51
As a continuation of the above:
Adding `BUILD_LIBRARY_FOR_DISTRIBUTION = YES` in Apollo-Target-Framework configuration it will result in a valid `Apollo.xcframework` generation with the above scripts.
The problem is with the ApolloAPI framework that doesn't accept the same flag in the `Apollo-Target-ApolloAPI` configuration.
Enabling it results in various erros:
<img width="1239" alt="Screenshot 2022-10-19 at 13 50 15" src="https://user-images.githubusercontent.com/189993/196671366-1f41a601-a75e-4320-bf83-bcd6b8849fcd.png">

BTW: I am happy to compile myself the xcframework variant for my needs, but it will be greatly appreciated if you could help me get these issues sorted.
Thank you.

**Comment by calvincestari** [comment] 2022-10-19 16:51
@mmdumi we may be dealing with a Swift tooling issue here, @AnthonyMDev has more context into this than I do but I believe there is currently no way to separate `swiftinterface` generation from the `BUILD_LIBRARY_FOR_DISTRIBUTION` build setting.

We will not be supporting Library Evolution, which is enabled through the `BUILD_LIBRARY_FOR_DISTRIBUTION` setting - see the "Enabling library evolution support" section of the [Swift documentation](https://www.swift.org/blog/library-evolution/). The reason for this is the performance constraints it creates, namely `@inlinable` usage.

We're currently looking for a way to check during compilation whether Library Evolution is enabled and if so then emit function signatures without `@inlineable`. They will be less performant but should fix this issue because `BUILD_LIBRARY_FOR_DISTRIBUTION` could then be used.

**Comment by mmdumi** [comment] 2022-10-20 10:38
Thank you for looking into this.
Just adding some context here regarding the xcframework support. Hope that everyone agrees that this is not just a preference or a "nice-to-have feature". It's really a timesaver for teams that have larger projects and use continuous integration tools. Build times are horrendous and we are not getting the wait time back across all our teams. 
Looking forward being able to use apollo as xcframework dependency as soon as possible.

**Comment by calvincestari** [comment] 2022-10-20 19:27
@AnthonyMDev and I have talked through this issue at length and are going to reopen this issue to make the following changes:
* Remove `@inlinable` where needed to support building an `xcframework`. PoC changes can be found in https://github.com/apollographql/apollo-ios/commit/d0867b0f8225613e6ab2c80592bb53ab932a9a20. The performance gained from `@inlinable` is expected to be negligible but we will reassess based on feedback.
* This does not change our stance on Library Evolution, it is still not officially supported. If there is a way in the future to disassociate `swiftinterface` generation from the `BUILD_LIBRARY_FOR_DISTRIBUTION` build setting we will likely make that choice.

**Closed** 2022-10-27 04:54 UTC
Labels: bug, build-issue

**Comment by calvincestari** [comment] 2022-10-27 04:57
This issue is fixed and will be included with the next release, `1.0.3`. _There is a [new CI step](https://github.com/apollographql/apollo-ios/blob/main/.circleci/config.yml#L149) that ensures xcframework builds continue to be supported._

**Comment by CraigSiemens** [comment] 2022-11-17 20:53
For anyone else that needs to keep using Carthage in their project, here's what we're doing.

We've got a makefile for building all our dependencies. We split up Carthage checkout and build so we can modify some projects before building them to avoid failures or unneeded schemes being built. For Apollo it looks like this.

```bash
carthage checkout

find -E Carthage/Checkouts/apollo-ios -name "*.xcscheme" -not -regex ".*/Apollo\.xcscheme" -delete
rm -r Carthage/Checkouts/apollo-ios/Tests

carthage build --platform iOS --cache-builds --use-xcframeworks
```

**Comment by calvincestari** [comment] 2022-11-21 18:13
> unneeded schemes being built

This is the the root problem of Carthage.
