### ISSUE TITLE
Crash when adding additional type to interface

### ISSUE THREAD

**Issue by koenpunt** [apollographql/apollo-ios#400] opened 2018-11-05 10:38 UTC
We have generated a Swift API for a schema that includes an interface. 

When we now add an additional type that implements this interface to the server, the app crashes. This can of course be fixed by regenerating the api, but this doesn't help for apps already running on a user's device.

What I think should happen is that the API should ignore any type that is not available in the `possibleTypes` array.

This can be achieved by making `GraphQLSelectionSet.init` a failable initializer, in which we then check if the `possibleTypes` array contains the `__typename` and otherwise return `nil`. To remove the `nil` entries from a result set we can simply call `.compactMap { $0 }`.

**Comment by koenpunt** [comment] 2018-11-05 10:42
Another option is to only update the generator, and filter out any `ResultMap` that has an unknown typename

For an array of objects that would be something like this;

```swift
public var nodes: [Node] {
  get {
    return (resultMap["nodes"] as! [ResultMap]).map { (value: ResultMap) -> Node in Node(unsafeResultMap: value) }.filter({
        Node.possibleTypes.contains($0.__typename)
    })
  }
  set {
    resultMap.updateValue(newValue.map { (value: Node) -> ResultMap in value.resultMap }, forKey: "nodes")
  }
}
```

**Comment by designatednerd** [comment] 2019-07-15 11:01
I'll have to take a deeper look into how we're generating this code but yeah, it at least shouldn't crash 🙃

**Comment by designatednerd** [comment] 2019-07-26 14:13
@koenpunt Can you send me an example of what the current code looks like so I can take a stab at fixing this in the codegen?

**Comment by koenpunt** [comment] 2019-07-26 14:30
> Can you send me an example of what the current code looks like so I can take a stab at fixing this in the codegen?

What kind of example do you mean? It's been a while that this happened, and we've been avoiding union types because of it. 

But you should be able to reproduce the issue by generating a client for a schema that returns a list of a union types, then add a new type to the union, and then run the query in the app (without regenerating the client that is).

**Comment by designatednerd** [comment] 2019-07-26 14:32
Basically what did the getter for `public var nodes: [Node]` look like before - I think I understand what you mean, but I'm still ramping up and it would be helpful to know what it looked like before to make sure I *actually* know what you mean.

**Comment by koenpunt** [comment] 2019-07-26 14:35
It was the same, but without the filter;

```swift
public var nodes: [Node] {
  get {
    return (resultMap["nodes"] as! [ResultMap]).map { (value: ResultMap) -> Node in Node(unsafeResultMap: value) }
  }
  set {
    resultMap.updateValue(newValue.map { (value: Node) -> ResultMap in value.resultMap }, forKey: "nodes")
  }
}
```

Also see my PR on the codegen here: https://github.com/apollographql/apollo-tooling/pull/656

**Comment by designatednerd** [comment] 2019-07-26 14:42
🤦‍♀️Welp, I totally missed that was a PR on the tooling repo. I'll take a look!

**Comment by designatednerd** [comment] 2019-08-07 09:09
@koenpunt When you get the repro, can you post it here? Thanks!

**Comment by designatednerd** [comment] 2019-08-07 16:49
@koenpunt Indicated [on the tooling repo](https://github.com/apollographql/apollo-tooling/pull/1462#issuecomment-519027426) that he is no longer able to reproduce. Closing this, please open a new issue if you run into something like this in the future!

**Closed by designatednerd** 2019-08-07 16:49 UTC
Labels: codegen, crash
