### ISSUE TITLE
  How to get the original JSON string, their own to parse the data into their own custom model.

### ISSUE THREAD

**Issue by milkatgit** [apollographql/apollo-ios#2646] opened 2022-11-07 09:32 UTC
## Question

Before you ask, check a few things to see if there might already be an answer: 

- [`CHANGELOG.md`](https://github.com/apollographql/apollo-ios/blob/main/CHANGELOG.md) has all the most recent changes
- We have [extensive documentation available](https://www.apollographql.com/docs/ios) (though we're always looking for ways to improve it!)

If neither of those have an answer for you, we have [community forums](https://community.apollographql.com) where our users can ask and answer questions - head on over there rather than opening an issue here please!

## Seriously

Use the [community forums](https://community.apollographql.com) for questions, please! 😇

**Comment by calvincestari** [comment] 2022-11-07 18:31
Hi @milkatgit 👋🏻 - it sounds like you want to implement a custom interceptor. You can read about that in the documentation for [Advanced Network Configuration](https://www.apollographql.com/docs/ios/networking/request-pipeline).

I'm going to close this issue since it's not a bug report nor feature request.

**Closed by calvincestari** 2022-11-07 18:31 UTC
Labels: question
