### ISSUE TITLE
[Swift Codegen FR] Interfaces as Protocols

### ISSUE THREAD

**Issue by Mordil** [apollographql/apollo-ios#1706] opened 2021-03-10 06:12 UTC
## Feature request

> ##### I haven't seen this listed anywhere in #939 or #1700, and the code examples in #939 doesn't show this as a direction, so I wanted to raise it here.

When the GraphQL schema defines an interface with implementations, it would be nicer if Apollo would generate a protocol with conformance to the types rather than requiring creation of struct instances from prior values or unwrapping optional properties that do it for us.

## Motivation

Right now, when you have an interface with conforming types, each conforming type is a nested struct definition (ignoring fragments for simplicity of discussion), with the top level interface struct providing factory methods and properties to convert it's value representation into the more specific type.

This causes some problems for extensions that should be valid on every possible type of the interface, as you have to write your own protocol or redefine the extension.

Swift has a native compliment to GraphQL interfaces: protocols.

## Proposed solution

Given the following simple example:

```
query HeroDetails($episode: Episode) {
  hero(episode: $episode) {
    __typename
    id
    name

    ... on Human {
      height
    }

    ... on Droid {
      primaryFunction
    }
  }
}
```

the following (abbreviated) code will be generated:

```swift
protocol HeroDetailsQueryCharacter {
  id: String { get }
  label: String { get }
}

public final class HeroDetailsQuery: GraphQLQuery {
  // ... existing details

  public struct Data {
    public let hero: HeroDetailsQueryCharacter

    public struct HumanHero: HeroDetailsQueryCharacter {
      // definitions matching the protocol
      public let height: Double
    }
  }
}
```

This would allow code like this:

```swift
let droid = response.data.hero as? Droid

if response.data.hero is HeroDetailsQuery.Data.HumanHero {
}
```

## Outstanding Questions

I can't think of any right now, but there's bound to be some that arise.

**Comment by designatednerd** [comment] 2021-03-10 18:25
Unfortunately the biggest question on my end is how this doesn't run into the exact same problem as [the bad news in #1700](https://github.com/apollographql/apollo-ios/issues/1700) about not really being able to do fragments as protocols because of the `self or associated types` problem. This is especially an issue when there are nested interfaces, which would absolutely require associated types. 

I'll ask @AnthonyMDev, who's been heads-down on all this, to take a look and confirm my instincts, but the associated types thing has killed a lot of dreams lately 😭

**Comment by AnthonyMDev** [comment] 2021-03-10 20:55
Thanks for contributing to the conversation @Mordil! So for fragments shared across multiple operations, fragments as protocols won't work well because of the associated types. This looks like it is a suggestion to use protocols for grouped selection sets on root type and type conditions within a single operation. 

That's a direction that hasn't been fully explored yet. From my experiences with all of this stuff so far, I have a suspicion that we are going to run into problems with this in complex queries. Right off the bat, I think this breaks down with nested types. 

If we had a field on the interface for `friends: [Character]`, the protocol would need to have an associated type, and then you have all the problems with generic protocols that make them lose a huge amount of value. (See #1700, I can also explain more about this specific problem if it's not clear what the issue is with associated types.

But even if it could work, I'm not convinced that it is the right direction to go with this.

Both `Human` and `Droid` are going to have the `id` and `name` fields, so that seems like a good candidate for a protocol, but that's really more about the intent of usage than is it about the representation of data. I could see plenty of situations in which this `HeroDetailsQueryCharacter` protocol is useful.  If you want to be able to use the abstract character without knowing if its a `Human` or a `Droid` (or something else perhaps), then the protocol could be useful for consuming the data. However, I can also see lots of situations in which it is not useful to have this abstraction. 

Creating these protocols for every possible selection set is going to add a large number of lines of generated code, it also is going to add complexity which would make the generated data structs harder to reason about quickly. The amount of generated code has been a complaint of many users. Minimizing that is a primary goal of the new code generation work. I'm not against adding functionality like this if it provides a lot of benefit, and if it actually works (ie. associated type issues). But I think that the assumption that every selection set should have a protocol generated for it will result in a huge amount of unnecessary protocols.

The `hero` property having a type of the protocol means that it will always use dynamic dispatch, which is minor, but is a performance hit also. 

My philosophy is that we don't have the ability to understand the intention of each use case. We don't know what your views look like or how you are going to use or reason about the data. We only know the shape of the raw data really. I don't think we should be attempting to make decisions about where abstractions can be made and try to generate neatly defined view models. We are never going to get it right all of the time (likely not even most of the time), and it will add more complexity, both for maintaining Apollo, and for user's reasoning about what Apollo is doing.

For the areas that you want to work with better abstractions, or reshape the data into a view model that makes more sense for your use case, you should create those yourself. And Apollo should do its best to make that easy and stay out of the way.

**Comment by Mordil** [comment] 2021-03-10 23:10
I'm well versed in the idea of PATs and Existentials, as well as their pros/cons.

Perhaps what I'm looking for is the ability to write my own extensions that I say apply to anything that represents a schema type, and Apollo generates the necessary code to make that extension available to all selection sets of that type.

The pain point right now is that if I define an extension on anything representation of a `Hero`, I need to use fragments to have a single definition or I end up adding it to both `HeroDroid` & `HeroHuman`, or define a protocol myself.

**Comment by designatednerd** [comment] 2021-03-10 23:17
Meaning defining something like (Option 1)

```swift
extension Hero {
   var nameAllCaps: String {
      return self.name.uppercased()
   }
}
```

or something more like (Option 2)

```swift
extension Hero {
    var somethingTypeDependent: String {
        if let humanHero = self.asHuman {
         return "\(humanHero.height)"
       } if let droidHero = self.asDroid {
         return droidHero.primaryFunction
       } else {
         return ""
       }
    }
}
```

Or some third option I'm not thinking of?

**Comment by AnthonyMDev** [comment] 2021-03-10 23:20
It's possible that we could use directives to allow you to apply extensions like that in the future! I don't think we should be generating all of that code by default for every selection set. But I could see value in directives that allow you to note that something is being used with a certain intention and then generate the appropriate protocols or extensions.

We aren't supporting custom directives right now, but that is something we are looking at supporting with the new code generation eventually. So I am open to ideas and suggestions on how to utilize that.

**Comment by Mordil** [comment] 2021-03-10 23:22
"Yes", but primarily the 1st option, but now that I think about it... there's just no good way to express this, at least in Swift's type system, because I'd have to express the type as seen by the schema, and only if certain properties are available.

```
// defined by me
extension Hero <if name is available> {
  var nameAllCaps: String { self.name.uppercased() }
}

// Apollo generates for each possible generation of a representation of a Hero
extension HeroDetailsQuery.Data.Hero {
  var nameAllCaps: String { self.name.uppercased() }
  // etc.
}
```

**Comment by AnthonyMDev** [comment] 2021-03-10 23:36
I do agree that there is generally a lot I wish we could do that is limited by Swift's type system. haha I've been banging my head against that every day for weeks now.

Couldn't this be done pretty easily without involving the code generation?

```swift
protocol CharacterName {
    var name: String { get }
}

extension CharacterName {
    var nameAllCaps: String { self.name.uppercased() }
}

extension HeroDetailsQuery.Data.Hero: CharacterName {}
```

You have to just write the conformance extension for each type, but that's not a huge burden.

**Comment by Mordil** [comment] 2021-03-10 23:38
Yes, it's possible - that's the status quo of the day. This is me asking for a way to _automate_ it, because the information is definitely there... I just don't know how we can express it and making it opt-in.

**Comment by AnthonyMDev** [comment] 2021-03-10 23:41
Ah okay. So, I could see using a directive so that we can generate the protocol conformance extension. Making it completely automatic I think is outside of the scope of what Apollo should be trying to do. It's something that we would have to make a lot of assumptions about that would open us up to way too many new edge cases. Or alternatively, the way we expect you to do things would be come too opinionated and less flexible.

**Comment by AnthonyMDev** [comment] 2021-03-11 18:51
To be clearer about my proposal, I mean something like this:

```swift
/// You define this protocol
protocol CharacterName {
    var name: String { get }
}

/// You define this extension
extension CharacterName {
    var nameAllCaps: String { self.name.uppercased() }
}
```

In your graphql query:
```
query {
    hero @extends("CharacterName") {
        id
        name
    }
}
```

```swift
/// The directive would make the generated code add this extension for the generated type.
extension HeroDetailsQuery.Data.Hero: CharacterName {}
```

Would that be adequate for you @Mordil? It's not totally automatic, but it is cleaner and easier than the status quo.

**Comment by Mordil** [comment] 2021-03-11 18:52
Yes! That's exactly what I'd like to see.

**Comment by AnthonyMDev** [comment] 2021-03-11 18:53
Okay, I think something like this is totally reasonable for the new code gen. There needs to be a bit more thought around this to make sure it doesn't break in edge cases. 

Also, we aren't planning on making any additions to the current code gen, so this will need to wait until the new code generation tool is ready. I love this proposal, but just understand it's going to be a while before we implement anything like this!

**Comment by Mordil** [comment] 2021-03-11 18:55
Understandable, that's why I "tagged" this post with `[Swift Codegen FR]` :)

I know y'all are swamped, but I'm still tossing ideas as they come up haha

**Comment by Mordil** [comment] 2021-04-19 16:43
@AnthonyMDev & @designatednerd I think you both might be interested in this next Swift proposal: https://forums.swift.org/t/se-0309-unlock-existential-types-for-all-protocols/47515/8

**Comment by designatednerd** [comment] 2021-04-19 18:01
@Mordil OOOOOOOH. Thanks for the heads up!

**Comment by AnthonyMDev** [comment] 2022-05-23 21:52
We've created a new issue #2279 for the defined behavior that we've agreed on. That will be added in a future release after 1.0 GA. The initial concept of interface protocols is not viable due to the reasons [explained above](https://github.com/apollographql/apollo-ios/issues/1706#issuecomment-796089301). Closing this issue in lieu of the new one.

**Closed by AnthonyMDev** 2022-05-23 21:52 UTC
Labels: feature, codegen
