### ISSUE TITLE
SPM Plugin Command "ApolloCodegenPlugin-Initialize" and "ApolloCodegenPlugin-Generate" don't appear to do anything

### ISSUE THREAD

**Issue by neilZon** [apollographql/apollo-ios#2667] opened 2022-11-16 04:20 UTC
## Bug report
When following the steps in https://www.apollographql.com/docs/ios/get-started/, I get to the part where you need to use the init and generate commands but I don't see a `apollo-codegen-configuration.json` or  a `.graphql.swift` file being made

<img width="1440" alt="Screenshot 2022-11-15 at 8 50 55 PM" src="https://user-images.githubusercontent.com/46465568/202080147-ed057035-45ca-4c2f-bd15-2df454a0f30e.png">

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.3
- Xcode version: 14.1
- Swift version: Swift 5
- Package manager: 

## Steps to reproduce

1. Start a new xcode iOS app project
2. File -> Add package -> add the apollo-ios package with these options and click add package
<img width="1079" alt="Screenshot 2022-11-15 at 9 09 56 PM" src="https://user-images.githubusercontent.com/46465568/202082610-74f4721d-73b5-4c13-9c3e-41cd8be09fb4.png">

3. Choose the "Apollo" package and click "add package"
4. Add graphql schema file from: `https://raw.githubusercontent.com/neilZon/workout-logger-api/main/graph/schema.graphqls` , to the root of the project 
5. Right click on the project and try running `ApolloCodegenPlugin-Initialize` like so:
<img width="554" alt="Screenshot 2022-11-15 at 9 14 20 PM" src="https://user-images.githubusercontent.com/46465568/202082122-ef017752-a2da-4700-9ffa-ea3c63931831.png">

## Further details

OS: MacOS Ventura 13.0.1
Machine: 1.4 GHz Quad-Core Intel Core i5
(only relevant because when I try the alternative route of trying the latest `apollo-ios-cli` binary it says `zsh: bad CPU type in executable: ./apollo-ios-cli`

**Comment by calvincestari** [comment] 2022-11-16 06:02
Hi @neilZon 👋🏻 - if you look in the Report Navigator tab in Xcode, there should be log output for the Plug-in. That may contain the logs needed to figure out what's going on. SPM plug-ins within Xcode are not a very good user experience and `1.0.4` will remove the CLI plug-in commands for exactly this reason.

**Comment by calvincestari** [comment] 2022-11-16 06:03
> `zsh: bad CPU type in executable: ./apollo-ios-cli`

I have not seen that error before, thanks for raising it.

**Comment by neilZon** [comment] 2022-11-16 21:22
@calvincestari It turns out the SPM plugins were working and were generating the files but not where I expected (I'm new to xcode and iOS development in general). So when I run the init command my project directory looks like this, but if I try to reveal in finder, it turns out the codegen config file is there. And then to run the generate command, I create a new empty file in the root of the xcode project, copy the contents of the codegen json stuff into the new empty file and rename it to `apollo-codegen-config.json` and the it generates the graphql stuff in the `TestAPI` folder in the same location as the init command did (as seen in the second picture). Are the locations of where these files are created expected behavior?
<img width="268" alt="Screenshot 2022-11-16 at 2 16 58 PM" src="https://user-images.githubusercontent.com/46465568/202296233-5ad23109-be75-4065-91bb-7e5afe5692e1.png">
<img width="783" alt="Screenshot 2022-11-16 at 2 15 31 PM" src="https://user-images.githubusercontent.com/46465568/202296281-28432623-56c4-4884-9c4f-7157a464b938.png">

**Comment by calvincestari** [comment] 2022-11-17 21:59
> So when I run the init command my project directory looks like this (first photo), but if I try to reveal in finder, it turns out the codegen config file is there.

That's correct because our codegen doesn't manipulate the xcode project file at all. It is a manual process for the generated Swift files to be added to your project. You would never need to add the config JSON file to your xcode project unless you wanted to for ease of editing but you would then need to make sure that it wasn't included in any deployment targets.

This is in contrast to a Swift Package Manager project which has no project file per-se and instead just shows all directories and files in any subpath from the package root. So in this case the JSON file would automatically show up in the project explorer.

> And then to run the generate command, I create a new empty file in the root of the xcode project, copy the contents of the codegen json stuff into the new empty file and rename it to apollo-codegen-config.json and the it generates the graphql stuff in the TestAPI folder in the same location as the init command did (as seen in the second picture). Are the locations of where these files are created expected behavior?

That is also correct because the paths in the config JSON file are relative to the where you run the command from, which is typically from the same directory as the config file. If you wanted the generated Swift files to be placed inside the `Test` folder you'd need to edit the output path to be something like `./Test/TestAPI/`

**Comment by calvincestari** [comment] 2022-11-17 21:59
I'm going to close this issue since it's not a bug but rather configuration related.

**Closed by calvincestari** 2022-11-17 21:59 UTC
Labels: needs investigation

**Comment by calvincestari** [comment] 2022-11-19 16:33
@neilZon, the "bad CPU" error is now fixed too - https://github.com/apollographql/apollo-ios/issues/2680#issuecomment-1320919470
