### ISSUE TITLE
ApolloCodeGen v1.03 XCode compile error

### ISSUE THREAD

**Issue by greenmoon82** [apollographql/apollo-ios#2632] opened 2022-11-02 06:26 UTC
Following "Getting Started documentation" in https://www.apollographql.com/docs/ios/get-started and using SPM with XCode project (no package.swift file for the XCode project). I can't get the app to compile if I select ApolloCodeGen package option. Compiler error shows `No such module `OrderedCollections`. 

<img width="1082" alt="Screen Shot 2022-11-01 at 11 16 52 PM" src="https://user-images.githubusercontent.com/9370927/199412694-4ec79e9e-a76c-4cbf-9fa4-71705f373539.png">

I can exclude `ApolloCodeGen` and get the project to compile but I am stuck in code gen. 
I don't have a Package.swift file in my project... the steps listed under Step 5: Setup and run code generation -> for Swift Package Manager option does not help me, because it is referring to `Package.swift` file. Are there specific steps to use the code gen tool if using SPM with XCode project ?

**Comment by calvincestari** [comment] 2022-11-02 17:54
I'm closing this issue as a duplicate of https://github.com/apollographql/apollo-ios/issues/2611. Let's continue the conversation in there and I'll take note of the +1 in that issue.

**Closed by calvincestari** 2022-11-02 17:54 UTC

**Comment by greenmoon82** [comment] 2022-11-06 05:20
Thank you. should I open a new issue for this part of my question ? 

the steps listed under Step 5: Setup and run code generation -> for Swift Package Manager option does not help me, because it is referring to Package.swift file. Are there specific steps to use the code gen tool if using SPM with XCode project ?

**Comment by calvincestari** [comment] 2022-11-07 17:59
There is a section of the CLI docs that has detail on [using the SwiftPM plugin via Xcode](https://www.apollographql.com/docs/ios/code-generation/codegen-cli#installation). We are going to be removing the SwiftPM plugin though, see #2565. The experience is not good enough for us to continue supporting it. Once it improves in Xcode and the sandbox behaviour is easier to work with we can bring the plugins back.

> I have asked a question in the forum for the following - https://community.apollographql.com/t/how-to-use-code-gen-tool-in-xcode-project-without-a-package-swift-file/4937?u=greenmoon82

I'll repost this answer there too for others to benefit from.
