### ISSUE TITLE
Serialize or recreate mutation

### ISSUE THREAD

**Issue by pggawlowski** [apollographql/apollo-ios#1308] opened 2020-07-10 14:19 UTC
What I am trying to achieve is mutation archivization. 
My first try was NSKeyedArchiver.archivedData, however currently it is impossible. 
So I decided to try to serialize and store jsonObject and/or variables and later, when back online, recreate mutation query.

```
let object = mutation.variables?.jsonObject ?? [:]
do {
     let recreatedMutation = try TestMutation.Data(jsonObject: object, variables: nil)
} catch {
    print(error)
}
```

However it results in `Apollo.JSONDecodingError.missingValue`

Any suggestions how to serialize and store mutations/queries or recreate them from stored data.

**Comment by designatednerd** [comment] 2020-07-10 17:17
It'd probably help for me to understand the use case - why do you need to persist the mutation itself?

**Comment by pgawlowski** [comment] 2020-07-10 18:53
We have to deal with cache sync. So one concept is to introduce mutations persistency. Currently we are successfully mutating cache but we also have to push it away when connection is restored.

**Comment by designatednerd** [comment] 2020-07-10 20:19
I think I'm a bit confused - are you talking about persisting the **result** of a mutation, or the mutation itself? 

What I think is happening is that you're trying to persist the mutation itself so you can push changes you've made locally up to a server. Is that correct?

**Comment by pgawlowski** [comment] 2020-07-11 08:32
Exactly! :)

**Comment by designatednerd** [comment] 2020-07-13 20:01
So part of the problem is that you're trying to use the nested `TestMutation.Data` type - that type is used for recreating the **result** of the mutation, not the mutation itself. 

You basically have to create the mutation the same way you would have if you weren't making it locally. So if your generated initializer is `TestMutation(parameter: String)`, then you want to persist the value of `parameter` and then send that mutation again. 

What you're trying to do is persist the variables JSON object, but there isn't an initializer for queries that takes that JSON object that you can pass what you're saving directly to. You could probably make a throwing initializer (in another file so it doesn't get overwritten by codegen) for the mutation that pulls that JSON back out, then tries to make the appropriate query from the JSON. 

You'd have to have some notion of what query the JSON was for, though - it might be better to have some custom `Codable` types that can persist information about both the query type and the parameter values you need to persist. 

There is definitely not a built-in way to do this, though.

**Comment by designatednerd** [comment] 2020-07-17 17:23
@pgawlowski Anything else I can help with here?

**Comment by pgawlowski** [comment] 2020-07-20 08:55
It's fine. Thank you very much!

**Comment by designatednerd** [comment] 2020-07-20 14:08
Cool - I'm going to close this issue out then. Thanks!

**Closed by designatednerd** 2020-07-20 14:08 UTC
Labels: question
