### ISSUE TITLE
Nil coalescing operator ambiguity

### ISSUE THREAD

**Issue by skreberem** [apollographql/apollo-ios#2619] opened 2022-10-28 13:07 UTC
Nil coalescing operator overload for `GraphQLNullable` results in ambiguity errors where type is not explicitly specified.

Example:

`let width = rect?.width ?? 0`

Error:
> Ambiguous use of operator '??'

**Comment by gsapienza** [comment] 2022-10-30 17:14
I am also experiencing this

**Comment by calvincestari** [comment] 2022-11-01 18:34
I don't know if there is any good way around this. I think it's caused by the fact that `GraphQLNullable` is simply a wrapper around many supported types. So the compiler is correct in telling you that it cannot infer which one it should use without conclusively knowing the property type.

It's resolved by specifying the type of `width` but I can see how that would be annoying if this syntax is used in many places of your existing codebase. Any suggestions?

**Comment by milowyner** [comment] 2022-11-08 00:07
Same issue here, and the codebase I'm working on has a lot of places where nil coalescing is used, so I just had to comment out the operator overload in `GraphQLNullable`, which isn't a great solution.

**Comment by calvincestari** [comment] 2022-11-08 00:55
Instead of commenting it out, try adding `@_disfavoredOverload` above the operator overload and see if it changes how the compiler treats it.

**Comment by milowyner** [comment] 2022-11-08 16:58
Ah thanks. That also works, and it feels like a better temporary solution. I was going to say they should add this to the SDK, but it seems that it's not recommended outside the compiler and standard library 😕 https://github.com/apple/swift/blob/main/docs/ReferenceGuides/UnderscoredAttributes.md

**Closed** 2022-11-08 20:35 UTC
Labels: codegen
