### ISSUE TITLE
No type for 'Value' can satisfy both

### ISSUE THREAD

**Issue by pugachevskiy** [apollographql/apollo-ios#2360] opened 2022-07-03 08:34 UTC
## Bug report

Apollo 1.0.0-beta doesn't compile on Xcode 14 beta. 

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.0-beta.1
- Xcode version: 14 beta 2
- Swift version: 5.7
- Package manager:

## Steps to reproduce
Build project in Xcode 14.

## Further details
No type for 'Value' can satisfy both 'Value == any JSONEncodable' and 'Value : Equatable'
No type for 'Value' can satisfy both 'Value == any JSONEncodable' and 'Value : Hashable'

<img width="1077" alt="Screenshot 2022-07-03 at 10 29 04" src="https://user-images.githubusercontent.com/5255053/177031706-2b0e5f33-4412-4d1b-b066-70105888ff38.png">

**Comment by AnthonyMDev** [comment] 2022-07-06 18:15
Thanks for bringing this to our attention. We haven't tested with Swift 5.7 yet, which seems to be the cause of this. I'll look into it soon!

**Comment by AnthonyMDev** [comment] 2022-08-09 23:48
This should be fixed in the release branch now. Beta 2 release with this will be coming soon!

**Closed by AnthonyMDev** 2022-08-09 23:48 UTC
Labels: bug, beta-xcode
