### ISSUE TITLE
SchemaConfiguration of Cache Keys not being called

### ISSUE THREAD

**Issue by Narayane** [apollographql/apollo-ios#2674] opened 2022-11-17 14:26 UTC
## Bug report

Hi,

I'm trying to migrate Apollo client from 0.53.0 to 1.0.3 into my app Xcode project under CocoaPods.

In my app code, I have some query watchers which work as expected: when a mutation payload updates something in the data of my local cache (which are parts of my query), relative watcher is fired perfectly.

After having upgraded Apollo client to 1.0.3, I notice my all query watchers are not triggered anymore in the cases they were with Apollo client 0.5.3.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.3
- Xcode version: 13.4.1
- Swift version: 5.6.1
- CocoaPods: 1.11.3

## Steps to reproduce

When I try to add or remove a picture to a ride, relative query watcher is not fired when I receive my mutations payloads. Watcher policy doesn't seem to be an investigation lead: both `.returnCacheDataElseFetch` and `.returnCacheDataAndFetch` are affected in my project.

My query (using fragments) and relative mutations
```
query GetRide($rideId: ID!) {
    ride(id: $rideId) {
        ...EndRideFragment
    }
}

fragment EndRideFragment on Ride {
    id
    name
    startTime
    isFavorite
    distance
    duration
    pictures {
        ...PictureFragment
    }
}

fragment PictureFragment on RidePicture {
    id
    url
    thumbnailUrl(height: 340)
}

mutation AddRidePicture($input: AddRidePictureInput!) {
    addRidePicture(input: $input) {
        ride {
            id
            pictures {
                id
            }
        }
        picture {
            ...PictureFragment
        }
    }
}

mutation DeleteRidePicture($id: ID!) {
    removeRidePicture(id: $id) {
        ride {
            id
            pictures {
                id
            }
        }
    }
}
```
My watchers (used with my previous query)
```
func watch<T: GraphQLQuery>(query: T) -> Observable<T.Data> {
    return self.client.rx.watch(query: query)
}

func watchAndFetch<T: GraphQLQuery>(query: T) -> Observable<T.Data> {
    return self.client.rx.watch(query: query, cachePolicy: .returnCacheDataAndFetch)
}
```

**Comment by calvincestari** [comment] 2022-11-29 02:11
Hi @Narayane, thanks for creating this issue. We haven't had any other reports of this so I'll need to take a look and see if I can replicate. If you have a sample project that replicates the issue it would help, thanks.

**Comment by calvincestari** [comment] 2022-12-02 20:40
@Narayane we have a suite of watch query tests that are currently passing on `main`; those indicate that the functionality is still operating the same as before.

Please put together a sample project demonstrating the regression you're experiencing.

**Comment by Narayane** [comment] 2022-12-05 09:33
Hi @calvincestari ,

Thanks for your feedback.

I can not work on it before mid-January 2023, sorry.

Correct me if I am wrong but I saw no unit tests with `.returnCacheDataAndFetch` policy and just [one](https://github.com/apollographql/apollo-ios/blob/main/Tests/ApolloTests/Cache/WatchQueryTests.swift#L955) with `.returnCacheDataDontFetch` policy which does not represent my case.
IMO, to represent my case with this previous one, it misses a payload mutation (from server) which just updates to a friend name into the initial data of R2-D2 to be sure watcher is well triggered after local cache update.
Something like `XCTAssertEqual(updatedWatcherResultExpectation.numberOfFulfillments, 2)` should be noticed: the first for the hero initial fetch and the second for the hero friend name update.

```
client.store.withinReadWriteTransaction({ transaction in
        let data = HeroAndFriendsNamesSelectionSet(
          data: DataDict(
            [
              "hero": [
                "id": "2001",
                "name": "R2-D2",
                "__typename": "Droid",
                "friends": [
                  ["__typename": "Human", "id": "1000", "name": "Luke Skywalker"],
                  ["__typename": "Human", "id": "1002", "name": "Han Solo"],
                  ["__typename": "Human", "id": "1003", "name": "Leia Organa"],
                ]
              ]
            ],
            variables: nil
          ))

        let cacheMutation = MockLocalCacheMutation<HeroAndFriendsNamesSelectionSet>()
        try transaction.write(data: data, for: cacheMutation)
      }) { result in
        XCTAssertSuccessResult(result)
        writeToStoreExpectation.fulfill()
      }
```
By waiting to have time to provide you a project example, I am just not going to update Apollo and keep using v0.53.0.

**Comment by calvincestari** [comment] 2022-12-05 18:53
Hi @Narayane, we're always happy to accept PRs when you get the time.

**Comment by AmadeusK525** [comment] 2023-01-04 20:43
Chiming in here: I also see this problem on my end, but the problem isn't the watcher, it's the mutation.
The mutation doesn't seem to be updating the cache, even with the `publishResultToStore` flag on. I didn't have enough time to study how your test framework functions, but I saw that if I refetch stuff from the server ignoring the cached data, I'll receive the data, the cache will be updated and the watcher will be notified.
If I perform a mutation, the cache isn't being updated, so if I refetch stuff from the server but use the cached data, I'll get outdated objects.

## Expected behavior

- A watcher is watching object `MyObject`
- A mutation is performed, which updates fields in `MyObject`
- Mutation is successfully sent to the server and writes to cache
- Watcher sees cache change and gets notified

## Actual behavior

- A watcher is watching object `MyObject`
- A mutation is performed, which updates fields in `MyObject`
- Mutation is successfully sent to the server but doesn't write to cache, so cache is outdated
- Watcher doesn't get notified at all
- If a Query is made to get some fields from `MyObject`, it'll hit the cache. Since the cache is outdated, the query will return data prior to the mutation being made
  - This Query *does* trigger the Watcher, but with outdated data

**Comment by AmadeusK525** [comment] 2023-01-09 18:29
Hey @calvincestari @AnthonyMDev any updates on this one? I consider this to be a pretty big priority, are there any plans to tackle this one for the next release?

**Comment by calvincestari** [comment] 2023-01-09 18:36
Our plan is to get `1.0.6` out today, there's a few fixes queued up already in there, and then `1.0.7` possibly before the end of the week. I'll add this to the list of things to tackle for `1.0.7` - will that work?

**Comment by AnthonyMDev** [comment] 2023-01-11 22:05
@Narayane @AmadeusK525, I have written a test for this that specifically performs a mutation, and everything seems to work as intended. 

It's important to note that you _must_ be configuring cache keys properly for this to work. Have you [migrated your cache key configuration](https://www.apollographql.com/docs/ios/migrations/1.0#cache-key-configuration) to the 1.0 APIs yet?

If you provide a cache key for your entities, then when they are updated in your mutation response payload, the normalized cache should pick up the changes correctly. But the default cache keys will not match up across the query and mutation responses. This is because the default cache keys are based on the response path. 

So for the `Hero` object in a query you might have the cache key `ROOT_QUERY.hero`, and the mutation you'd have `ROOT_MUTATION.hero`. These cache keys don't match.

If you configure your cache so that objects with the `__typename: Hero` are cached based on their `id` fields, then the cache key for each of these objects will be the same! (Provided you fetch the `id` field in both your query and mutation responses)

---

If you can confirm that you are configuring cache keys correctly and this is still a problem, I'd love to dig deeper into it and figure out a reproduction case! It seems odd that this would have been working in the 0.51 version but not 1.0 unless your cache keys aren't configured correctly...

**Comment by AnthonyMDev** [comment] 2023-01-11 22:08
Here is the unit test I've written that is passing for this case. Note that I had to add the `id` field to the selection sets and provide the same id for the objects in the response data. I also configured our `MockSchemaMetadata` to use a cache key provider that uses the `id` field as the cache key for all entities.

```swift
func testWatchedQueryGetsUpdatedWhenOverlappingMutationReturnsChangedData() throws {
    // given
    class HeroNameSelectionSet: MockSelectionSet {
      override class var __selections: [Selection] { [
        .field("hero", Hero.self)
      ]}

      class Hero: MockSelectionSet {
        override class var __selections: [Selection] {[
          .field("__typename", String.self),
          .field("name", String.self),
          .field("id", String.self)
        ]}
      }
    }

    class HeroAndFriendsNameSelectionSet: MockSelectionSet {
      override class var __selections: [Selection] {[
        .field("hero", Hero?.self)
      ]}

      var hero: Hero? { __data["hero"] }

      class Hero: MockSelectionSet {
        override class var __selections: [Selection] {[
          .field("__typename", String.self),
          .field("name", String.self),
          .field("id", String.self),
          .field("friends", [Friend]?.self),
        ]}

        var friends: [Friend]? { __data["friends"] }

        class Friend: MockSelectionSet {
          override class var __selections: [Selection] {[
            .field("__typename", String.self),
            .field("name", String.self),
          ]}

          var name: String { __data["name"] }
        }
      }
    }

    MockSchemaMetadata.stub_cacheKeyInfoForType_Object = IDCacheKeyProvider.resolver

    // when
    let watchedQuery = MockQuery<HeroAndFriendsNameSelectionSet>()

    let resultObserver = makeResultObserver(for: watchedQuery)

    let watcher = GraphQLQueryWatcher(client: client,
                                      query: watchedQuery,
                                      resultHandler: resultObserver.handler)
    addTeardownBlock { watcher.cancel() }

    runActivity("Initial fetch from server") { _ in
      let serverRequestExpectation =
        server.expect(MockQuery<HeroAndFriendsNameSelectionSet>.self) { request in
        [
          "data": [
            "hero": [
              "id": "123",
              "name": "R2-D2",
              "__typename": "Droid",
              "friends": [
                ["__typename": "Human", "name": "Luke Skywalker"],
                ["__typename": "Human", "name": "Han Solo"],
                ["__typename": "Human", "name": "Leia Organa"],
              ]
            ]
          ]
        ]
      }

      let initialWatcherResultExpectation = resultObserver.expectation(
        description: "Watcher received initial result from server"
      ) { result in
        try XCTAssertSuccessResult(result) { graphQLResult in
          XCTAssertEqual(graphQLResult.source, .server)
          XCTAssertNil(graphQLResult.errors)

          let data = try XCTUnwrap(graphQLResult.data)
          XCTAssertEqual(data.hero?.name, "R2-D2")
          let friendsNames = data.hero?.friends?.compactMap { $0.name }
          XCTAssertEqual(friendsNames, ["Luke Skywalker", "Han Solo", "Leia Organa"])
        }
      }

      watcher.fetch(cachePolicy: .fetchIgnoringCacheData)

      wait(for: [serverRequestExpectation, initialWatcherResultExpectation], timeout: Self.defaultWaitTimeout)
    }

    runActivity("Perform overlapping mutation from server") { _ in
      let serverRequestExpectation =
        server.expect(MockMutation<HeroNameSelectionSet>.self) { request in
        [
          "data": [
            "hero": [
              "id": "123",
              "name": "Artoo",
              "__typename": "Droid"
            ]
          ]
        ]
      }

      let updatedWatcherResultExpectation = resultObserver.expectation(
        description: "Watcher received updated result from cache"
      ) { result in
        try XCTAssertSuccessResult(result) { graphQLResult in
          XCTAssertEqual(graphQLResult.source, .cache)
          XCTAssertNil(graphQLResult.errors)

          let data = try XCTUnwrap(graphQLResult.data)
          XCTAssertEqual(data.hero?.name, "Artoo")
          let friendsNames = data.hero?.friends?.compactMap { $0.name }
          XCTAssertEqual(friendsNames, ["Luke Skywalker", "Han Solo", "Leia Organa"])
        }
      }

      let mutationCompletedExpectation = expectation(description: "Other fetch completed")

      client.perform(mutation: MockMutation<HeroNameSelectionSet>()) { result in
        defer { mutationCompletedExpectation.fulfill() }
        XCTAssertSuccessResult(result)
      }

      wait(for: [serverRequestExpectation, mutationCompletedExpectation, updatedWatcherResultExpectation], timeout: Self.defaultWaitTimeout)
    }
  }
```

**Comment by AmadeusK525** [comment] 2023-01-11 22:31
Hey @AnthonyMDev thanks for your input! I'll investigate our cache key configurations tomorrow morning and get back to you ASAP. Looking at your comments, that's most likely the case, the cache keys may not be configured correctly for 1.0

**Comment by Narayane** [comment] 2023-01-12 09:37
Hi @AnthonyMDev,

Thanks for your support and for yours investigations :)

I normally followed all migration steps from 0.53.0 to 1.0.x, and particularly:
- for cache configuration

from 0.53.0
```
        // Set cache resolving strategy based on id (technical id from postgresql) else uid (for user) by waiting id usage for all objects from backend
        self.client.cacheKeyForObject = {
            if let uid = $0["uid"] {  // case User
                return uid
            } else if let id = $0["id"] {
                if let _ = $0["id"] as? NSNull { // case GenericRideEvent start and stop for now
                    return nil // default strategy
                } else {
                    return id
                }
            } else {
                return nil // default strategy
            }
        }
```
to 1.0.x (`uid` key is now useless in my code, we do not have objects in this case for a while)
```
public extension GraphQLAPI {
    
    static func cacheKeyInfo(for type: Object, object: JSONObject) -> CacheKeyInfo? {
        guard let id = object["id"] as? String else {
            return nil
        }
        return CacheKeyInfo(id: id)
    }
}
```
- for my custom `InterceptorProvider`

```
class LRNetworkInterceptorProvider: InterceptorProvider {
    
    // These properties will remain the same throughout the life of the `InterceptorProvider`, even though they will be handed to different interceptors.
    private let store: ApolloStore
    private let client: URLSessionClient
    
    init(store: ApolloStore, client: URLSessionClient) {
        self.store = store
        self.client = client
    }
    
    deinit {
        self.client.invalidate()
    }
    
    func interceptors<Operation: GraphQLOperation>(for operation: Operation) -> [ApolloInterceptor] {
        return [
            MaxRetryInterceptor(),
            CacheReadInterceptor(store: self.store),
            LRNetworkFetchInterceptor(client: self.client),
            ResponseCodeInterceptor(),
            //JSONResponseParsingInterceptor(cacheKeyForObject: self.store.cacheKeyForObject), // from 0.53.0
            JSONResponseParsingInterceptor(), // to 1.0.x
            AutomaticPersistedQueryInterceptor(),
            CacheWriteInterceptor(store: self.store),
        ]
    }
}
```
I'm sorry, I can not share with you my code directly because it is not open source but let me know if you need more details on my Apollo client config in order to try to reproduce my problem.

Thank you so much 🙏

**Comment by AmadeusK525** [comment] 2023-01-12 13:27
@AnthonyMDev Heyo, it seems like this was overlooked on our side and setting the correct cache keys does indeed work. Thank you very much for your help!

**Comment by AnthonyMDev** [comment] 2023-01-13 19:40
@Narayane I have tried testing every configuration I can come up with here to reproduce this issue. I've put variables on the fields, added new child objects (instead of just changing existing ones), and I am still unable to reproduce this.

Since it's working for @AmadeusK525 now, I'm wondering if there is something else in your project configuration that is causing this bug that I don't have information on.

If you are able to provide me with a unit test or sample project that reproduces this, I am happy to continue to look into it. Or if you want to add some breakpoints and do some debugging yourself in your project and can give me more information about what might be causing this, that could help me out also.

If I don't get any more information from you, I'm going to end up having to close this as "Could not reproduce". If others have the same issue and can provide more info, then we can take another look.

**Comment by Narayane** [comment] 2023-01-16 18:31
Hi @AnthonyMDev ,

I have upgraded Apollo to its last version (1.0.6) and I still have my problem.
I do not know if it is related or not but when I set a Xcode breakpoint in my Apollo cache config function, it is never reached...

<img width="710" alt="Capture d’écran 2023-01-16 à 19 26 24" src="https://user-images.githubusercontent.com/4921308/212745444-87595e04-db58-4cb8-8a2a-fd7522d22526.png">

Would it mean that default strategy is applied even if I have set "correctly" my custom one ?
Thanks.

**Comment by AnthonyMDev** [comment] 2023-01-16 18:44
Yeah if your cache config is not being called, that’s definitely the problem. We need to figure out why that is the case. Something must be wrong with your generated code.

**Comment by Narayane** [comment] 2023-01-17 08:39
Let me know if you need more information upon my Apollo configuration.

**Comment by AnthonyMDev** [comment] 2023-01-24 17:52
I'm not really sure how to help you debug this one at this point... I'm wondering if for some reason this has to do with the usage of your Reactive Framework. We don't support or maintain the community built Reactive Apollo library.

**Comment by Narayane** [comment] 2023-01-25 15:12
Hi,

Here my "reactive extension" for `watch` function.
I would need you to explain to me how rxify the return of your `watch` function could impact Apollo client cache configuration...
Let me know if it was the case because reactive extensions creation on almost everything is, from my PoV, the mainstream way in mobile development nowadays :)
Thanks.

```
/// Watches a query by first fetching an initial result from the server or from the local cache, depending on the current contents of the cache and the specified cache policy. After the initial fetch, the returned `Observable` will emit events whenever any of the data the query result depends on changes in the local cache.
    ///
    /// - Parameters:
    ///   - query: The query to watch.
    ///   - cachePolicy: A cache policy that specifies when results should be fetched from the server and/or from the local cache.
    ///   - queue: A dispatch queue on which the result handler will be called.
    /// - Returns: An `Observable` that emits the results of watching the `query`.
    public func watch<Query: GraphQLQuery>(query: Query, cachePolicy: CachePolicy = .returnCacheDataElseFetch, queue: DispatchQueue = DispatchQueue.global(qos: .default)) -> Observable<Query.Data> {
        return Observable.create { observable in
            let watcher = self.client.watch(query: query, cachePolicy: cachePolicy) { result in
                switch result {
                case .success(let result):
                    if let graphqlErrors = result.errors, result.source == .server { // log and spread only if data come from server
                        let message = graphqlErrors.map{ $0.localizedDescription }.joined(separator: ", ")
                        observable.onError(LRError.graphqlError(graphqlErrors))
                    } else if let data = result.data {
                        observable.onNext(data)
                    }
                case .failure(let error):
                    if let graphqlError = error as? GraphQLResultError {
                        observable.onError(graphqlError)
                    } else if let lrError = error as? LRError {
                        observable.onError(lrError)
                    } else {
                        observable.onError(LRError.dataError)
                    }
                }
            }
            return Disposables.create {
                watcher.cancel()
            }
        }
    }
```

**Comment by AnthonyMDev** [comment] 2023-01-30 17:57
Your code theoretically looks good there. If the `cacheKeyInfo` function is not being called, something is wrong with your project. Without being able to look at your project, I'm not sure what is the next step in debugging this. If you can't give me access to your project, you're going to need to do some more debugging yourself.

Try setting a breakpoint in `ApolloAPI/SchemaMetadata.swift` on line 57 and see what is happening when `cacheKeyInfo(for:object:)` is called. It for some reason is not calling the function on your `GraphQLAPI` object.

**Comment by Narayane** [comment] 2023-01-31 10:20
Hi @AnthonyMDev,

![Capture d’écran 2023-01-31 à 10 52 08](https://user-images.githubusercontent.com/4921308/215726976-3de3868b-ac19-42a0-b61d-14d451b198ee.png)

At each call, it is the breakpoint at line 58 which is reached but it seems quite normal because my generated file `SchemaConfiguration.swift` contains this below so it does not consider my static "cache overriding config"...
```
// @generated
// This file was automatically generated and can be edited to
// provide custom configuration for a generated GraphQL schema.
//
// Any changes to this file will not be overwritten by future
// code generation execution.

import Apollo

enum SchemaConfiguration: Apollo.SchemaConfiguration {
  static func cacheKeyInfo(for type: Object, object: JSONObject) -> CacheKeyInfo? {
    // Implement this function to configure cache key resolution for your schema types.
    return nil
  }
}
```
Below my `apollo-codegen-config.json`
```
{
  "schemaName" : "GraphQLAPI",
  "options" : {
    "apqs": "automaticallyPersist",
    "cocoapodsCompatibleImportStatements" : true,
    "queryStringLiteralFormat": "multiline",
    "deprecatedEnumCases": "include",
    "schemaDocumentation": "include",
    "warningsOnDeprecatedUsage": "include",
    "pruneGeneratedFiles": true
  },
  "schemaDownloadConfiguration": {
    "downloadMethod": {
        "introspection": {
            "endpointURL": "https://mywebsite/graphql",
            "httpMethod": {
                "POST": {}
            },
            "includeDeprecatedInputValues": true,
            "outputFormat": "JSON"
        }
    },
    "downloadTimeout": 60,
    "headers": [],
    "outputPath": "./Liberty Rider/schema.json"
  },
  "input" : {
    "operationSearchPaths" : [
      "**/*.graphql"
    ],
    "schemaSearchPaths" : [
      "./Liberty Rider/schema.json"
    ]
  },
  "output" : {
    "schemaTypes" : {
      "path" : "./Liberty Rider/Services/API/GraphQLAPI",
      "moduleType" : {
        "embeddedInTarget" : {
          "name": "Liberty Rider"
        }
      }
    },
    "operations" : {
      "inSchemaModule" : {
      }
    },
    "testMocks" : {
      "none": {}
    },
    "operationIdentifiersPath": "./Liberty Rider/schemaOperationIdsPath.json"
  }
}
```
I tried to (re)generate my files but with no changes onto my file `SchemaConfiguration.swift`.

Let me know if I do something wrong...
Thanks a lot for debugging 🙏

**Comment by Narayane** [comment] 2023-02-21 08:45
Hi @AnthonyMDev,

Any updates or additional data needs ?

Thanks.

**Comment by AnthonyMDev** [comment] 2023-02-21 18:56
The implementation of the cache key resolution (the one that you show in [this comment](https://github.com/apollographql/apollo-ios/issues/2674#issuecomment-1384425475)) should be in that `SchemaConfiguration.swift` file. That function should be returning the correct `CacheKeyInfo`.

Implementing that function in your `GraphQLAPI` directly is not going to do anything. :)

**Comment by AnthonyMDev** [comment] 2023-02-21 18:57
Looks like I need to make a documentation update to fix this. Sorry for the confusion.

**Comment by AnthonyMDev** [comment] 2023-02-21 19:28
The docs have been updated, and I'm fairly certain that fixing that configuration should solve your issue. If this is still a problem, feel free to re-open this issue.

**Closed by AnthonyMDev** 2023-02-21 19:28 UTC
Labels: bug, awaiting response

**Comment by Narayane** [comment] 2023-02-22 14:16
Hi @AnthonyMDev,

Finally it works 🎉 
Thanks for your time and support.

FYI : You made a mistake into [docs](https://www.apollographql.com/docs/ios/migrations/1.0/#example-1), it is not: public enum SchemaConfiguration: ApolloAPI.SchemaConfiguration {

**Comment by calvincestari** [comment] 2023-02-22 18:21
Thanks for confirming it's working @Narayane. The `ApolloAPI` vs `Apollo` difference is because you're using CocoaPods which bundles everything together in one big module named the same as the pod.

@AnthonyMDev we could possibly do two column code samples for these? Or just a comment on that line in the samples.
