### ISSUE TITLE
Improve @_exported import ApolloAPI in generated files

### ISSUE THREAD

**Issue by simonpierreroy** [apollographql/apollo-ios#2863] opened 2023-03-02 19:28 UTC
### Use case

- ` @_exported` is sharp edge tool. There should be a choice for generating files with and without it.
- The choice should be made by the user:  `@_exported import ApolloAPI` vs `import ApolloAPI`.
- In addition `@_exported import ApolloAPI` should only be there once per module, not on every generate file.

### Describe the solution you'd like

- For folks who want to keep ` @_exported import ApolloAPI`, this line of code should be added to only one file, for example, a file called `apollo_exports.swift` that only contains ` @_exported import ApolloAPI`. It should not be added to each `*.graphql.swift` file, sine they are part of the same module. (Or even never do it, and let the user create that file if needed.)

Why is `@_exported` a sharp edge tool in this use case?
- By adding `@_exported import ApolloAPI` in a `module A`, now `import A` exposes all symbols in `ApolloAPI` and are visible with `A.symbolInApolloAPI ` inside a `module C` without (maybe) knowing they are from `ApolloAPI` . It creates scope confusion in module C for symbols in `A` vs. `ApolloAPI`.
- This removes easy visibility on what linking is needed in `module C` (if `module A` and `ApolloAPI` are built dynamically for example). 
- Technically, if this was built as a binary with `BUILD_LIBRARY_FOR_DISTRIBUTION=YES`, it could create issues if apple removes `@_exported` a directive from the compiler in the future (I know this will probably never happen since Apple uses it a lot). More concretely, this affect the `swift module interface` files of `module C`.

Here is the official info.  In this example `M` is `ApolloAPI`, `N` is a module I am writing (vending), and `P` is a module I do not own. I want a better control on the code `P` sees, and I want `P` to really known when they use an `ApolloAPI` symbol.
https://github.com/apple/swift/blob/main/docs/ReferenceGuides/UnderscoredAttributes.md#_exported 

```swift
// module M
public func f() {}

// module N
@_exported import M

// module P
import N
func g() {
  N.f() // OK
}
```

All of this to say, the choice should be left to the user.
- Do you have any concern with a change like?
- Why was this done in the first? I am missing something important?
- `@_exported` is a really great tool when use internally in the library itself (for example let ApolloAPI expose an internal library seamlessly, but again that is a choice left to the library author). Why this needs to be done externally?

**Comment by AnthonyMDev** [comment] 2023-03-07 20:25
Thank you for all the comments. I didn't expect anyone to have a strong opinion on this usage. I'm not convinced that this is something we should remove or make a configuration option. Let me respond to your points and give my thoughts on why:

## Reason for using `@_exported`:

> Why was this done in the first? I am missing something important?

`ApolloAPI` is a smaller module that was broken out of `Apollo` that includes just the bare minimum of models and protocol extensions to allow the generated models to function. It does not include any of the networking client or caching mechanisms. 

In order for the generated models to be usable, there are a few models in `ApolloAPI` that your code needs access to. Some of the most notable being `GraphQLNullable` and `GraphQLEnum`. We found that without the `@_exported import` we were getting a number of bug reports from confused users who were getting build errors when trying to consume their generated models. The models live in your code, and when you receive them from a GraphQL response, users expect to just be able to use them automatically.

I significant portion of operation models just aren't usable without importing `ApolloAPI`. And user's did not know that they needed to import `ApolloAPI` in every file that is touching these generated models. It seems odd that you would need to import both your module that contains your operation models (if you don't keep them in the same module as the consuming code) and `ApolloAPI` every time. Since you'll need to import `ApolloAPI` a large percentage of the time anyways, the `@_exported import` makes these significantly more user friendly.

## Using Experimental Language Features

Concerns over the usage of underscored attributes and other experimental or unstable language features is definitely understandable. There are two primary concerns I see when using them.

### 1. Stability

I was hesitant to use and of these features at first, because of the concern that they feature would change out from under us and our user's applications would start to crash or have undefined behavior in production. I asked for clarification on this and got [a response from Joe Groff](https://forums.swift.org/t/swift-arc-weak-unowned-performance/37870/27) (who at the time was Apple's community manager for Swift).

> The Swift runtime libraries are ABI-stable, so we wouldn't intentionally make a change that could break existing binaries. We also take source stability seriously. If we were to deprecate that API, we would do so in such a way that wouldn't affect existing shipped binaries, and would hopefully provide a warning when you try to compile your code with a new SDK that introduced the deprecation. - Joe Groff

This means that stability of these functionality should not be a concern. Experimental APIs would be deprecated for a very long time before being obsoleted if that were the decided course of action. For experimental APIs that move to stable, the `_` prefixed version of them would remain usable in binaries compiled with older versions of Swift due to ABI stability. So this is a non-issue.

### 2. Safety

Many of the experimental language features have poor to no documentation. How they actually work and the side effects of them are not completely known, they may cause bugs and have edge cases that haven't been discovered yet. Using experimental APIs must be done with extreme caution and I understand hesitancy towards their usage.

There are a number of experimental attributes that we really want to use but we aren't confident that they won't cause issues for our users. So we are avoiding them for now.

But `@_exported` does not fit into that category. It's usage has been pretty well tested and established, and the functionality that it exposes is clear and well defined. 

We also use `@_disfavoredOverload` a lot internally, which we have done our due diligence to ensure the safety of using.

---

> Technically, if this was built as a binary with BUILD_LIBRARY_FOR_DISTRIBUTION=YES, it could create issues if apple removes @_exported a directive from the compiler in the future (I know this will probably never happen since Apple uses it a lot). More concretely, this affect the swift module interface files of module C.

Firstly, I want to say that we have taken a stance that we *do not officially support library evolution*. You should not be plugging in a compiled artifact of the Apollo client SDKs into a pre-compiled dependency with a different version. The internals of the generated models, which live in your module, are too highly connected to the implementation of `ApolloAPI`. This is another reason why we expect you to re-generate your models after updating your client version. We even have a step in the code generator that checks for a version match between your `Apollo` dependency and your version of the codegen tooling.

On top of that, we really recommend that, if at all possible, you link the Apollo libraries statically. We have a ton of `@inlinable` code and generic functions in `ApolloAPI` that can improve run time performance if statically linked. Inlining and generic specialization optimizations cannot be used if you link to `ApolloAPI` dynamically. We understand that there are situations in which that is not possible, but even if you are using a dynamic library, you shouldn't expect library evolution to continue to work stably for the Apollo iOS libraries.

Even so, `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` does work with Apollo iOS for Carthage support currently. You just need to rebuild the correct version of Apollo and not try to use an old version with a newer version of your binary.

Given that we expect you to compile Apollo iOS for the version of your application you are using, I am unclear what specific problems come about because our code is affecting the swift module interface files of your module.

> I would argue that this maybe shouldn't be an option at all but instead the Apollo SDK shouldn't be using @_exported at all in the generated code. Apple does discourage using this feature (though they do themselves it all over Foundation and UIKit... 🤷).

There is a blanket statement for **all** experimental features that their usage is actively discouraged. But this is really just a CYA thing. If you look around the Swift forums, people who know what they are talking about recommend their usage all over the place all the time. They just want to be able to say "Hey, we told you not to use this, its your problem." when something breaks or you encounter a bug or edge case.

For the specific experimental features we are using we have done the work to feel confident in their usage. 

*For these reasons, we don't believe that the argument to avoid usage of `@_exported import` in the generated models is is justified solely by the fear of using experimental APIs. We have done our due diligence in ensuring our usage of experimental language features is safe.*

## Scope Pollution

> By adding @_exported import ApolloAPI in a module A, now import A exposes all symbols in ApolloAPI and are visible with A.symbolInApolloAPI  inside a module C without (maybe) knowing they are from ApolloAPI . It creates scope confusion in module C for symbols in A vs. ApolloAPI.

I fully understand this point! Because the generated code lives in your modules but must consume APIs that we create, all of those APIs are `public`. It's an unfortunate side effect of generated code here. That is a big part of why we created `ApolloAPI`. By breaking out only the necessary code into `ApolloAPI`, we minimize the scope pollution (rather than exporting all of `Apollo`).

Additionally, we have been careful to prefix all of the parts of `ApolloAPI` that aren't intended for consumer use outside of the generated models usage with an `_`. This hides them from the compiled documentation and acts as an indicator that these are intended for internal use only. We also indicate that in the inline documentation for many of these properties and functions.

But the fact remains that anywhere that you want to actually use the generated models, you're going to need to `import ApolloAPI` and you will get that scope pollution there anyways. With the tradeoff being the `ApolloAPI` scope pollution only exist in those files instead of all of your module in return for you needing to remember to `import ApolloAPI` each time. The tradeoff seems fairly minor to me.

But we are hoping to improve on this in the future with:

## `@_spi` Usage

There is another experimental language feature called [`@_spi`](https://github.com/apple/swift/blob/main/docs/ReferenceGuides/UnderscoredAttributes.md#_spispiname) that could help with this. It was intended for exactly this situation. It allows us to make certain symbols only imported if you use `import @_spi(Internal) ApolloAPI`, which could be used in the generated models.

This helps with the scope pollution, however the intention is that the rest of `ApolloAPI` would still be `@_exported` to continue providing the ease of use I talked about above. This would just ensure that the parts that you aren't intended to use don't show up in your module's scope and in code completion!

However there are some concerns about the safety of using this feature in its current form. I'm doing my research here, but I've yet to get enough information to be comfortable either using `@_spi` or deciding we should not use it. Again, we do our due diligence when using these APIs and I haven't been able to get the information I need to ensure this won't cause issues in certain situations just yet.

## Linking Errors

> This removes easy visibility on what linking is needed in module C (if module A and ApolloAPI are built dynamically for example).

This is a great point! We have actually encountered this problem already with some users and are investigating how we can improve upon this. There are some possible avenues we can go down here to deal with this, but we need to look into it further.

However removing `@_exported` here doesn't actually remove the need to link your module to `ApolloAPI` when using dynamic libraries, it just makes it more obvious because you have to manually write `import ApolloAPI` all over your code. So I don't think it's really a strong argument for removing this.

## Summary

We are really averse to adding more and more configuration options to the codegen config. Everyone has a ton of ideas of things they would like to configure it to do slightly differently for their project. We are trying to avoid a situation where there is massive growth in the complexity and size of the configuration. Unless we believe a new configuration option provides significant value to a broad audience, we are averse to adding it to the library.

I've explained why I don't believe `@_exported import` here is problematic, and for most users, this is just giving them a choice to do something that doesn't provide much value and just adds more scope creep and things to maintain for us.

If you feel strongly about your preferences to avoid this, it is a pretty trivial change that you can make in a fork of Apollo iOS. We re-wrote the code generation engine in Swift to enable Swift developers to easily do this. But our team is not in the business of supporting the individual preferences of every team that uses our library. 

If there is a reason why our usage of `@_exported import` is an actual blocker or is causing bugs in your code that don't have a reasonable other solution, then we are much more inclined to consider adding an option to disable this.

**Comment by simonpierreroy** [comment] 2023-03-08 01:57
@AnthonyMDev thank you for the response. 
Again for the safety and stability point, we are on the same page (I also use a lot of underscore features).  
And like I mentioned before, I see how `@_exported` is useful for library authors (and I use it). 
I really appreciate the detail response.

My issue is still exposing this choice publicly in code generation because of scope confusion. 

In my case, I have a library using Apollo, let us call it, `Helper`. It is a dynamic library wrapper for `Apollo`.  We really wanted folks using `Helper` to have to import `ApolloAPI ` explicitly if they ever use an Apollo (`ApolloAPI`) symbols, because `Helper` could be link up to 100 other libraries in our code base (in theory). Our issue is that at the scale of our app, ownership can be complicated and it helps knowing what the files in your module imports. 

In any case, I already created a script that removes `@_exported import` and replace it with `import` postcode generation. 
The first time I did that change, yes it resulted in many of the compiler errors, where folks using `Helper` needed to `import ApolloAPI` (if they used a symbol), but a lot of those files also where fine (since using wrapper function in `Helper`).  But this is something we do want. I understand we are a special use case, but at this scale it is important for us.
So I guess I am on the complete opposite of the trade off. And I am happy to write custom tooling for it.

At the end of the day, I would still fix code generation to only write `@_exported import ApolloAPI ` in one special file, and not in every file, since it is only needed once per module to export back all symbols of `ApolloAPI ` in the consuming module swift interface.

Thank you again.

**Comment by simonpierreroy** [comment] 2023-03-08 17:44
If anyone needs a similar script!

```shell
#!/usr/bin/env bash
set -euo pipefail

autogenerated_code_folders=(
    path_to_folder_1/autogenerated"
    path_to_folder_2/autogenerated"
)

import_key="@_exported import ApolloAPI"
new_import_key="import ApolloAPI"
for path_folder in "${autogenerated_code_folders[@]}"; do
    find "${path_folder}" -type f -name '*\.graphql\.swift' -print0 | xargs  -0 sed -i '' "s/${import_key}/${new_import_key}/" 
done
```

**Comment by simonpierreroy** [comment] 2023-03-10 00:46
@AnthonyMDev What do you think of those 2 ideas?

- Only write `@_exported import ApolloAPI`  in one special generated  file (that would only contain that code), and not have it at the top of every generated file, since it is only needed once per module (all other generated files can simply do `import ApolloAPI` ).
- I would add in `Apollo ` the same `@_exported import ApolloAPI ` so importing `Apollo` would give you both.

**Comment by AnthonyMDev** [comment] 2023-03-10 18:41
I'm not opposed to either of these suggestions! Thank you for all the awesome discussion on this. I'll keep this issue open and change the issue title to reflect this work that is being considered for a future release.

**Comment by simonpierreroy** [comment] 2023-03-11 04:11
Amazing. Thank you.

**Comment by bignimbus** [comment] 2023-05-12 18:15
We're closing this issue and tracking the intended change here: https://github.com/apollographql/apollo-ios/issues/3010

Thanks! 🙏🏻

**Closed by bignimbus** 2023-05-12 18:15 UTC
Labels: feature

**Comment by simonpierreroy** [comment] 2024-03-25 19:02
Interesting update for swift 6. https://github.com/apple/swift-evolution/blob/main/proposals/0409-access-level-on-imports.md.
