### ISSUE TITLE
Apollo 1.0.x generate multiple files with the same name in the same package

### ISSUE THREAD

**Issue by Dimillian** [apollographql/apollo-ios#2645] opened 2022-11-07 09:23 UTC
Here is our configuration with Apollo 1.0.3
```
let configuration = ApolloCodegenConfiguration(schemaName: "GQL",
                                               input: .init(schemaPath: urlToSchemaFile.absoluteString),
                                               output: .init(schemaTypes: .init(path: outputURL.absoluteString,
                                                                                moduleType: .other),
                                                             operations: .inSchemaModule))
```

I'm using `other` as `moduleType` and `inSchemaModule` because we're already having a package ready to accept the code generated by GraphQL. And we want all the GQL code to be within this package.
Using 0.5.X it was working fine, new codegen split the files using the same file name in different folders, this is not something that is supported in a Swift Package or even the targets in Xcode. 
Xcode fail to compile it with those kind of errors

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/535509/200274169-fef0cfcb-a61d-4826-ac32-aed141edaa9a.png">

**Comment by calvincestari** [comment] 2022-11-07 18:05
Hi 👋🏻 - do you have different GraphQL items, such as Object, Fragment, Interface, etc., all sharing the same name? If not, what are those types of items that get the same filename?

**Comment by Dimillian** [comment] 2022-11-07 18:47
Yes, that's the issue, I have those folders with the same files file names within.

**Comment by calvincestari** [comment] 2022-11-07 19:20
Hmm, I'm not sure what the right solution is here. I don't want to have to suffix every generated item with it's type and there's already too many configuration options to support an option per type. This needs more thought.

> Using 0.5.X it was working fine

Was your previous code being generated into just one file before?

**Comment by Dimillian** [comment] 2022-11-07 20:09
We were using the JavaScript CLI and we were splitting it in different files but there was no overlap in naming.

**Comment by Dimillian** [comment] 2022-11-07 20:13
I do think file prefix or suffix sound fine. It needs to be worked around because it can't work in the current way with the compiler. I don't think I'm doing anything exotic with our configuration?

**Comment by calvincestari** [comment] 2022-11-07 21:28
> We were using the JavaScript CLI and we were splitting it in different files but there was no overlap in naming.

What were the filenames for these same objects before when using the JS CLI?

> I do think file prefix or suffix sound fine. It needs to be worked around because it can't work in the current way with the compiler. I don't think I'm doing anything exotic with our configuration?

It's the schema types that have duplicate filenames right? The schema is the source-of-truth for those and there is no way to alias a type. IMO a better practice is not to name so many things the same but as someone building a client app you may not have control over the schema and type names. So it really has to be the codegen engine that works around it.

**Comment by Dimillian** [comment] 2022-11-08 07:15
Awwwwww I just got it! Yes we indeed have two fragments named the same as one of out schema type. Usually we append data at the end to be sure it'll not collide. I guess we missed those two because the previous codegen was collapsing all of it into one file. Let me check what it was outputting once I'll be back on it. 

So I guess a warning in the codegen debug console could be fine.

**Comment by calvincestari** [comment] 2022-11-08 07:26
Suffixing "Fragment" to the end of fragment names/filenames is something we're already considering. I'm going to close this issue as a duplicate of #2598, you can track it's progress there.

**Closed by calvincestari** 2022-11-08 07:26 UTC
Labels: needs investigation
