### ISSUE TITLE
Very High Memory Allocation

### ISSUE THREAD

**Issue by sam961** [apollographql/apollo-ios#580] opened 2019-06-11 07:05 UTC
I have been working on a project using graphql since 3 month.
I noticed at the time being there is a massive memory allocation when iam using the Apollo
Attached is the image 
<img width="215" alt="Screen Shot 2019-06-11 at 10 02 26 AM" src="https://user-images.githubusercontent.com/4921874/59250539-41b1c900-8c30-11e9-9436-e8ab2f2ecfd4.png">
I couldn't figure out the issue, but it is a very critical one since  the app is crashing on older devices like iphone 6

**Comment by js** [comment] 2019-06-11 08:59
Use the allocation instrument to see what objects you're allocating

**Comment by sam961** [comment] 2019-06-11 11:12
after tracking, it seems  that loading image  inside the app is taking much memory.
Problem solved by reducing image size.
But also  the apollo has memory leaks that is not solved yet .
#230

**Comment by designatednerd** [comment] 2019-07-10 21:18
I'm going to close this as a dupe of #230 and track through that issue, but thanks for filing this and bringing that one to my attention!

**Closed by designatednerd** 2019-07-10 21:18 UTC
