### ISSUE TITLE
Building project in XCode10 returns error `Build input file cannot be found: .../API.swift

### ISSUE THREAD

**Issue by victormihaita** [apollographql/apollo-ios#369] opened 2018-09-20 13:10 UTC
- [x] has-reproduction

### **Problem reproduction**
When trying to compile the project having the schema downloaded, but without having the `API.swift` generated, the compiler returns the error:
`Build input file cannot be found: '/Users/victormihaita/GitHub/ios/Sources/API.swift`

After this error, the` API.swift` is generated, so if we build the project again, everything is fine. The problem in my case, is that the build has to compile the first time in order to pass the CI.

### **Build Phase:** 
`APOLLO_FRAMEWORK_PATH="$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1)"`

`if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
exit 1
fi`

`cd "${SRCROOT}"
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-cli.sh codegen:generate Sources/API.swift --queries="$(find . -name '*.graphql')" --passthroughCustomScalars --schema=Sources/schema.json`

### **Fastlane** for downloading schema
`lane :download_schema do`
 `   sh("npm install -g apollo")`
 `   Dir.chdir("..") do`
 `      sh("apollo schema:download ./Sources/schema.json --endpoint our_private_url")`
 `   end`
 `end`

**Comment by victormihaita** [comment] 2018-09-20 13:58
### **Workaround for this issue**

The compiler needs to have the reference to the `API.swift` file. A solution for this is to remove all the code that is inside the file. In this way, the CI will recognise the reference to the file and will compile the code.

**Comment by victormihaita** [comment] 2018-09-20 13:58
> ### **Workaround for this issue**
> The compiler needs to have the reference to the `API.swift` file. A solution for this is to remove all the code that is inside the file. In this way, the CI will recognise the reference to the file and will compile the code.

**Comment by ashiemke** [comment] 2018-09-21 05:00
My workaround was to add a script step in CI to touch API.swift so the compiler will see something. More of a problem with how CI and source control are set up than anything this project can fix?

**Comment by victormihaita** [comment] 2018-09-21 06:51
we ended up with the same solution as you did @ashiemke. But is still an issue because this behavior can be observed also when you build locally. If the API.swift doesn’t exist, the build crashes also locally first time.

**Comment by georgehadly-marleyspoon** [comment] 2018-10-01 16:10
I believe this is the expected behaviour of xcode 10, based on apple [release note](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes/build_system_release_notes_for_xcode_10) for the new build tool, [WWDC'18 Session #408](https://developer.apple.com/videos/play/wwdc2018/408/)

> If an output file which is generated by a shell script is used as an input elsewhere in the build, then that output must be declared as an explicit output by the script that generates it; otherwise the build system may attempt to search for the file before it has been generated, causing the build to fail.

To solve the problem, under `Generate Apollo GraphQL script` you have an output files click on the `+` and add `API.swift` file in there 🎉.  This solution will work local without any issue and in the CI.

<img width="885" alt="screen shot 2018-10-01 at 18 05 13" src="https://user-images.githubusercontent.com/18592583/46300666-97fc4180-c5a4-11e8-99f4-bbbce7d043a3.png">

The reason of having of having the output files is that Xcode can better determine the dependency graph between targets. 

> It is an error for any individual file in the build to be produced by more than one build command. For example, if two targets each declare the same output file from a shell script phase, factor out the declaration of the output file into a single target.

**Comment by ZevEisenberg** [comment] 2019-06-29 21:14
It would be nice if Apollo generated a .xcfilelist file, which could be used to declare all the .swift files it generates. (This is in cases where you’re generating a folder of files, rather than just a single API.swift file.)

**Comment by designatednerd** [comment] 2019-07-15 10:06
Hey all - the build scripts have been updated in the [docs](https://www.apollographql.com/docs/ios/installation/#adding-a-code-generation-build-step) - I'm going to close this one out but @ZevEisenberg thank you for the suggestion, I'm going to open that as a separate enhancement.

**Closed by designatednerd** 2019-07-15 10:06 UTC
Labels: has-reproduction
