### ISSUE TITLE
Build error: Result namespace clash w/ Alamofire

### ISSUE THREAD

**Issue by lbasile** [apollographql/apollo-ios#670] opened 2019-07-25 18:13 UTC
Upgrade to Apollo 13.0 produced this error when installed with Alamofire:

>Generic type 'Result' specialized with too many type parameters (got 2, but expected 1)

There are two Result types in this setup with the same name:
Apollo.Result
Alamofire.Result

I worked around this in the meanwhile by renaming `Result` to `ApolloResult`. 

Using Cocoapods for dependency management.

**Comment by designatednerd** [comment] 2019-07-25 19:01
omg hi @lbasile! 👋

So two things here - the first is that I removed our custom `Result` type in 0.12.0, so it seems like there might be some gremlins in your system if it's still there. Mind commenting out the pod -> `pod install` -> commenting it back in to see if that gets rid of the old one?

For the error check the [bit of the 0.13.0 release notes about `Result`](https://github.com/apollographql/apollo-ios/releases/tag/0.13.0) - we switched a bunch of things to `Swift.Result` and so they now have just the `Result<Thing, Error>` instead of `(Thing?, Error?)` tuple. 

Hopefully that fixes both your issues! Please feel free to close this if it does.

**Comment by designatednerd** [comment] 2019-07-26 15:58
@lbasile Any luck?

**Comment by Drusy** [comment] 2019-07-30 09:39
Having the same issue here, there is a conflict using Alamofire as NetworkTransport.

Using
```
func send<Operation>(operation: Operation, completionHandler: @escaping (Result<GraphQLResponse<Operation>, Error>) -> Void) -> Cancellable where Operation : GraphQLOperation
```
Result in the following error: `Generic type 'Result' specialized with too many type parameters (got 2, but expected 1)`


And using `Swift.Error` to override `Alamofire.Result`: 

```
func send<Operation>(operation: Operation, completionHandler: @escaping (Swift.Result<GraphQLResponse<Operation>, Error>) -> Void) -> Cancellable where Operation : GraphQLOperation
```
Result in `Type 'AlamofireTransport' does not conform to protocol 'NetworkTransport'`

Here is a minimalist AlamofireTransport to reproduce the error
```
public class AlamofireTransport: NetworkTransport {
    enum Error: Swift.Error {
        case some
    }

    func send<Operation>(operation: Operation, completionHandler: @escaping (Swift.Result<GraphQLResponse<Operation>, Error>) -> Void) -> Cancellable where Operation : GraphQLOperation {
        completionHandler(.failure(Error.some))
    }
}
```

Still investigating...

**Comment by designatednerd** [comment] 2019-07-30 12:01
@Drusy Thanks for clarifying. 

@lbasile Any luck?

**Comment by designatednerd** [comment] 2019-08-12 09:31
Since I haven't heard back on this one for a couple weeks, I'm going to close it out. If you're still running into problems on this, please open a new issue. Thank you!

**Closed by designatednerd** 2019-08-12 09:31 UTC
Labels: build-issue
