### ISSUE TITLE
Allow namespacing of generated Test Mocks

### ISSUE THREAD

**Issue by nathanhosselton** [apollographql/apollo-ios#2826] opened 2023-02-10 23:59 UTC
### Use case

I am upgrading from `0.50.x` to `1.0.x` this week and ran into the same issue described in #2797 where the mock types generated from my schema are conflicting with type names from other modules. Part of my issue is simply from the [continued lack of support for same-name module/type disambiguation in Swift](https://forums.swift.org/t/fixing-modules-that-contain-a-type-with-the-same-name) *(sigh)*. But also, I expected my generated test mocks to be namespaced the same as my generated schema types, or at least that I would have some configuration available to opt into namespacing. It seems this is not currently an option.

I understand that conflicts can be worked around in some cases by isolating the generated test mocks into their own module, but this is insufficient in my usage since, upon importing my TestMocks module alongside the module with the competing type names, Swift is still unable to disambiguate them (prompting the compiler error that the type `is ambiguous for type lookup in this context`). And while I could then disambiguate usage of the test mock types, I still could not for my own types due to the aforementioned Swift limitation. So they remain unreachable.

This leaves me with a choice between renaming my own module (or the matching type within the module) or forgoing Apollo's generated test mocks.

I'm probably going to change the name of my module for now, since it's the least intrusive of the options, and I'd very much like to be able to replace my manually-maintained mocks with the new Apollo generated types. But I could avoid this entirely if there were an option to namespace my generated mocks, which I more than likely would've opted into even without this conflict.

### Describe the solution you'd like

To me, it seems reasonable to default to namespacing the test mocks the same as the schema types for any configuration:

```json
{
  "schemaName" : "Generated",
  "input" : { },
  "output" : {
    "schemaTypes" : {
      "moduleType" : {
        "embeddedInTarget" : {
          "name" : "Model"
        },
      "path" : "./Model/Generated"
      }
    },
    "operations" : { },
    "testMocks" : {
      "absolute" : {
        "path" : "./Mock/Generated"
      }
    }
  }
}
```
In this example, the generated schema types and test mocks (and also operations depending on configuration) would receive the same `Generated` caseless enum namespace within their respective modules. I can't think of any conflicts that could arise from this (aside from the obvious issue of putting the real and mock types into the same target), but perhaps there's a configuration permutation I haven't considered.

Regardless, this would be a breaking change, and not a significant enough one to warrant an immediate major version release. So I expect that this feature would need to be opt-in, at least for now. Plus, there should be a way to manually enable/disable this feature either way. Something like:

```json
{
  "schemaName" : "Generated",
  "input" : { },
  "output" : { },
  "options": {
    "testMocksNamespace": "Generated"
  }
}
```
The presence of the `testMocksNamespace` option would enable the new feature using the provided name. Were this instead default behavior, this option would allow for a custom name, and a mutually exclusive `disableTestMocksNamespace` boolean option could turn off namespacing entirely (defaulting to false if omitted). Alternatively, a `namespace` field could be rolled into `output.testMocks`. Whatever fits the config file best.

I haven't looked at the source for `ApolloCodegenLib` so I don't know how complicated this feature would be to implement, but I'm hoping that much of what's currently used in generating the schema types and operations under the `schemaName` caseless enum could be reused here. I'm happy to take a crack at this myself if so, though I may need to be pointed in the right direction.

**Comment by calvincestari** [comment] 2023-02-13 18:24
Hi @nathanhosselton 👋🏻 

Our design for test mock namespacing was that when using `swiftPackage` it produces a separate product/target in the generated Swift package, and when using `absolute(path:)` the generated files would be namespaced by the test target they're added to. _I see you're using the absolute(path:) configuration option, so is it that you want further and complete isolation of the generated test mock types?_

When using `swiftPackage` the schema name is used but with `"TestMocks"` appended to the end, so with the example `Generated` it would be `GeneratedTestMocks`. We only enclose the generated schema types in the caseless enum for the `embeddedInTarget(name:)` module type so I suppose if were to implement further test mock type namespacing we could apply the same structure to generated test mock classes but only for the `absolute(path:)` configuration option.

Would that give you the isolation you're looking for?

**Comment by nathanhosselton** [comment] 2023-02-13 23:46
> …so is it that you want further and complete isolation of the generated test mock types?

Indeed. Sadly, placing the generated mocks into their own target isn't sufficient to work around my issue (being unable to disambiguate my own types due to Swift breaking module namespacing when a module contains a top level type of the same name, which I expect isn't an entirely rare case). Plus, I think the option to completely isolate generated types (both schema and mock) could find favor even among groups not suffering from naming conflicts.

> When using `swiftPackage` the schema name is used but with `"TestMocks"` appended to the end, so with the example `Generated` it would be `GeneratedTestMocks`.

Oh nice, yeah I like that. So if there were some configuration that created a `GeneratedTestMocks` caseless enum to use for namespacing of the mock types, that would be perfect. No need to complicate with a custom name.

**Comment by AnthonyMDev** [comment] 2023-02-21 20:43
>  (being unable to disambiguate my own types due to Swift breaking module namespacing when a module contains a top level type of the same name, which I expect isn't an entirely rare case)

I am not exactly clear on what problem you're running into here. You are creating types that have the same name as which module? Your application module, the generated schema module? Just trying to wrap my head around what the actual issue you're running into here is. Can you give us a bit more explanation of what your project structure looks like that is causing this issue?

**Comment by nathanhosselton** [comment] 2023-02-21 21:14
> You are creating types that have the same name as which module? Your application module, the generated schema module?

One of my own custom modules, which I simply named `Model`. Inside which is a type also named `Model`. Defining a top-level type with the same name as the enclosing module removes the ability to reference the module directly (you instead begin referencing that type).

Basically, I have top-level types declared within my `Model` module which have names competing with those generated by Apollo. For the schema types this isn't an issue, since I can configure codegen to wrap those in the caseless enum for additional namespacing. But this is not currently possible for the test mock types. So even when those types are placed into their own module separate from my `Model`, contexts where I import both my `Model` and the module containing the generated test mocks will encounter naming conflicts for those overlapping type names. I can disambiguate the test mock types, but not my own.

Not sure if this helps, but here's a rough outline of my project structure:
```
- App
- CustomSwiftPackage
  - Model
  - Services
  - GraphQLDefinitions
  - GeneratedSchemaTypes
  - GeneratedMockTypes
  - MockServices
  - Tests
```

Only the `MockServices` and `Tests` modules import `GeneratedMockTypes`, but they also import `Model`. Thus, the conflicts arise.

**Comment by AnthonyMDev** [comment] 2023-02-21 22:10
Thank you for the explanation. I see now.

This seems like a very specific edge case. I agree it's not too rare to have a type with the same name as its containing module name. But this problem only occurs when that name **_also_** conflicts with the name of a type in your schema **_and_** you're generating test mocks. This is a pretty specific situation.

We're really averse to adding new configuration options that only address very specific situations because the configuration is already pretty complex and the more it grows, the more confusing and daunting it becomes for new users.

This problem isn't _really_ caused by Apollo iOS, it's an unfortunate circumstance, but it's primarily caused by the Swift language's limitation around module/type name disambiguation, as you mentioned. If that gets resolved in a future version of Swift, this configuration option becomes obsolete for the most part.

While the `ApolloCodegenConfiguration` is designed to support a wide variety of project needs, in this case, we feel that the value added here does not outweigh the con's of the additional complexity and maintenance burden of a growing configuration. **We don't intend on implementing this option at this time.**

In this situation, I really would recommend that you change the name of your `Model` module. I feel like your project can just avoid this problem altogether by renaming it. Since all your other modules are pluralized, might I suggest renaming it to `Models` instead of `Model`?

If you are really set on keeping your module naming as is, then you can always fork the repo and make custom modifications to the codegen engine. We re-wrote the whole thing in Swift specifically to make it easier for Swift devs to do this for custom modifications that don't fit into the general purpose needs of the community at large.

Thank you for the feedback and discussion @nathanhosselton. I'm going to close this issue as a wontfix. We are always willing to reconsider if there is a significant number of people all requesting this addition, especially if they can highlight other situations in which this would provide value.

**Closed by AnthonyMDev** 2023-02-21 22:10 UTC
Labels: feature, codegen, awaiting response

**Comment by nathanhosselton** [comment] 2023-02-21 23:09
> This seems like a very specific edge case. I agree it's not too rare to have a type with the same name as its containing module name. **But this problem only occurs when that name also conflicts with the name of a type in your schema** and you're generating test mocks. This is a pretty specific situation.

@AnthonyMDev real quick I want to point out that this isn't entirely correct, and that's on me from not explaining as thoroughly as I could have.

The issue is bigger than a conflict specifically with the type whose name matches the module. The conflicts can occur with any top-level type in the module (my `Model` in this case) that is also defined in the test mocks module. For example:

```swift
// In module `Model`
public class Model {
  //…
}

public class User {
  //…
}

// In module `GeneratedTestMocks`
public class User {
  //…
}
```

The type `User` would conflict where both modules are imported, and only the test mock User type could be disambiguated. Repeat for any additional top level types which conflict.

My reason for opening this feature request wasn't simply to have my own case addressed (I have already renamed my `Model` module to work around it), it was also to recommend a change that I think is sensible and valuable for the Apollo library. I completely agree with and can relate to the desire to minimize the complexity of codegen configuration as much as possible. My hope was that this would be a relatively small lift given that the behavior already exists for generated schema types.

Again, I'm happy to work on this change myself with an initial point in the right direction, assuming that you would consider it for a PR. I want the Apollo library as good as it can be for everyone, and I feel this change would be valuable to others, even absent the impetus of naming conflicts.

**Comment by AnthonyMDev** [comment] 2023-02-22 00:19
Thanks for the additional context!

I don't think the initial work to implement this is that heavy, I'm more concerned with the constantly growing size of the configuration.

I do really appreciate the offer to implement this and your desire to improve Apollo iOS. I still believe I stand by the decision that this isn't valuable enough of an addition to warrant including it at the current time. That may change in the future, but for now, I think renaming your module is the best approach.

Let's cross our fingers that they resolve this limitation of Swift sometime soon!
