### ISSUE TITLE
Use Apollo and buddybuild

### ISSUE THREAD

**Issue by appcelerate** [apollographql/apollo-ios#325] opened 2018-07-24 11:02 UTC
Hi, 

i want to use the client but because of the build script my buddybuild is always failing because of compiling.

```
✗ Command /bin/sh failed with exit code 127
1684
    ** ARCHIVE FAILED **
1685
    The following build commands failed:
1686
    	PhaseScriptExecution Download\ GraphQL\ Schema /tmp/sandbox/59ea1eab89d8e30001a455b3/bbbuild/Build/Intermediates.noindex/ArchiveIntermediates/App\ -\ Release/IntermediateBuildFilesPath/App.build/Release-iphoneos/App\ Rebel.build/Script-11E50E1A21021FD4003732EA.sh
1687
    (1 failure)
```
How can i solve this?

Regards,
Dennis

**Comment by zvonicek** [comment] 2018-07-24 14:49
I have the same issue when running on Bitrise CI. Already spent almost whole day debugging it 😞 . I suspect the 0.90 to 0.9.1 minor (sic!) update causing it where `apollo-codegen` was replaced with `apollo` CLI. This error output from Bitrise might bring more light to the issue.

```
[07:41:30]: ▸  ›   Warning: apollo update available from 1.2.0 to 1.5.0
[07:41:30]: ▸  ›   Warning: generate is not a apollo command.
[07:41:30]: ▸ Did you mean help? [y/n]: 
[07:41:30]: ▸  ›   Error: Run apollo help for a list of available commands.
[07:41:30]: ▸ Command /bin/sh failed with exit code 127
```

**Comment by zvonicek** [comment] 2018-07-24 15:33
I confirm my hypothesis, 0.9.0 works correctly for me. I recommend a downgrade to 0.9.0 till the issue is resolved.

**Comment by martijnwalraven** [comment] 2018-07-29 10:59
Since `apollo-codegen` is now part of the new [`apollo-cli`](https://github.com/apollographql/apollo-cli), the build script used to generate `API.swift` needs to be updated. See [the docs](https://www.apollographql.com/docs/ios/installation.html#adding-build-step) for the updated script.

**Comment by zvonicek** [comment] 2018-07-29 15:00
Updating the script was not the issue for me, I did it and Apollo worked on my machine just fine. But apparently, there is an issue when running the build script in CI environment like Bitrise or Buddybuild.

**Comment by martijnwalraven** [comment] 2018-07-29 15:35
@zvonicek 0.9.2 [includes a change that installs `apollo-cli` locally instead of globally](https://github.com/apollographql/apollo-ios/pull/326). Could you check if that solves your issue?

**Comment by yoxisem544** [comment] 2018-08-01 08:15
Having same issue....

**Comment by martijnwalraven** [comment] 2018-08-01 08:16
@yoxisem544 What is the output you're seeing? What version of Apollo iOS are you running? Did you update the build script to use `run-and-check-apollo-cli`?

**Comment by sean-howard** [comment] 2018-09-19 18:12
@martijnwalraven I'm using `check-and-run-apollo-cli` in my Build Phase and it works perfectly fine in Xcode 10 locally using Apollo 0.9.3.

I am still however seeing this error in buddybuild build server logs.

```
 ▸ Running Phase Script 'Generate Apollo GraphQL API'
4335
    ⚠ Apollo iOS requires version 1.8.x of the Apollo CLI to be installed either globally or in a local node_modules directory.
4336
    ** BUILD FAILED **
4337
    The following build commands failed:
4338
    	PhaseScriptExecution Generate\ Apollo\ GraphQL\ API /tmp/sandbox/59db99bc92b6df0001f951de/bbbuild/Build/Intermediates.noindex/Shutterbug.build/Release-iphoneos/Shutterbug.build/Script-8C3371142052DF9700C092C9.sh
4339
    (1 failure)
```

Is it possible I need to make `check-and-run-apollo-cli.sh` a pre build phase on buddybuild instead?

**Comment by RolandasRazma** [comment] 2018-09-19 21:12
I managed to workaround it on buddybuild by installing Apollo as global first `npm install -g apollo@1.9`

**Comment by RolandasRazma** [comment] 2018-09-19 21:16
> I have the same issue when running on Bitrise CI. Already spent almost whole day debugging it 😞 . I suspect the 0.9.0 to 0.9.1 minor (sic!) update and #304 causing it where `apollo-codegen` was replaced with `apollo` CLI. This error output from Bitrise might bring more light to the issue.
> 
> ```
> [07:41:30]: ▸  ›   Warning: apollo update available from 1.2.0 to 1.5.0
> [07:41:30]: ▸  ›   Warning: generate is not a apollo command.
> [07:41:30]: ▸ Did you mean help? [y/n]: 
> [07:41:30]: ▸  ›   Error: Run apollo help for a list of available commands.
> [07:41:30]: ▸ Command /bin/sh failed with exit code 127
> ```

you need to update your update script to `apollo schema:download $SCHEMA_PATH --endpoint=$SERCVER_PATH`

**Comment by sean-howard** [comment] 2018-09-20 09:04
@RolandasRazma So you'd run `npm install -g apollo@1.9` as a pre-build script?

**Comment by sean-howard** [comment] 2018-09-20 09:48
@RolandasRazma Seems to have done the trick! Thanks for the tip!

**Comment by designatednerd** [comment] 2019-07-10 19:08
Gonna close this one out with @RolandasRazma's [solution for installing NPM](https://github.com/apollographql/apollo-ios/issues/325#issuecomment-422960481) as the recommended one.

**Closed by designatednerd** 2019-07-10 19:08 UTC
